import { test, expect } from '@playwright/test'
import { randomUUID } from 'node:crypto'

test('Direct MCP allowlist, assistant subset, discovery failure, drift review and mobile interaction', async ({ page, request }) => {
  const adapter = process.env.MEASIX_E2E_ADAPTER_URL!
  const mode = async (value: string) => { expect((await request.post(`${adapter}/__mcp_mode`, { data: { mode: value } })).ok()).toBe(true) }
  await page.goto('/admin/')
  await page.locator('[data-cy="login-username"]').fill('admin')
  await page.locator('[data-cy="login-password"]').fill(process.env.MEASIX_E2E_ADMIN_PASSWORD!)
  await page.locator('[data-cy="login-submit"]').click()
  await expect(page).toHaveURL(/\/admin\/(overview)?$/)
  await page.goto('/admin/resources')
  const openMcp = async () => {
    const desktop = page.locator('[data-cy="config-section-mcp"]')
    if ((page.viewportSize()?.width ?? 1280) >= 900) await desktop.click()
    else {
      await page.locator('[data-cy="configuration-section-nav"]').getByRole('combobox').click()
      await page.getByRole('option', { name: 'MCP', exact: true }).click()
    }
    if (!await page.locator('[data-cy="mcp-tools-editor"]').isVisible()) await page.getByText('E2E Test MCP', { exact: true }).first().click()
  }
  await openMcp()
  const tools = page.locator('[data-cy="mcp-tools-editor"]')
  // An unsupported negotiated version has its own safe diagnostic and preserves the catalog.
  await mode('old-version')
  await tools.locator('[data-cy="mcp-discover"]').click()
  await expect(tools.locator('[data-cy="problem-banner"]')).toContainText('2024-11-05')
  await expect(tools.locator('[data-cy="problem-banner"]')).toContainText('2025-11-25, 2025-06-18, 2025-03-26')
  await expect(tools.locator('[data-cy="mcp-previous-catalog-retained"]')).toBeVisible()
  await mode('initial')
  await expect(tools.locator('[data-tool-name="tool-a"] [data-cy="mcp-tool-select"]')).toHaveAttribute('aria-checked', 'true')
  const approval = (name: string) => tools.locator(`[data-tool-name="${name}"] [data-cy="mcp-tool-approval"]`)
  await expect(approval('tool-a')).toContainText('No additional confirmation')
  await approval('tool-a').getByRole('combobox').click()
  await page.getByRole('option', { name: 'Confirm each invocation', exact: true }).click()
  await mode('added')
  await tools.locator('[data-cy="mcp-discover"]').click()
  await expect(tools.locator('[data-tool-name="tool-new"]')).toBeVisible()
  await expect(tools.locator('[data-tool-name="tool-new"] [data-cy="mcp-tool-select"]')).toHaveAttribute('aria-checked', 'false')
  await tools.locator('[data-cy="mcp-tool-search"]').fill('enterprise')
  await expect(tools.locator('[data-tool-name="tool-a"]')).toBeVisible()
  await expect(tools.locator('[data-tool-name="tool-new"]')).toHaveCount(0)
  await tools.locator('[data-cy="mcp-tool-search"]').fill('')
  await mode('failure')
  await tools.locator('[data-cy="mcp-discover"]').click()
  await expect(tools.locator('[data-cy="problem-banner"]')).toBeVisible()
  await expect(tools.locator('[data-tool-name="tool-new"]')).toBeVisible()
  await mode('drift')
  await tools.locator('[data-cy="mcp-discover"]').click()
  await expect(tools.locator('[data-cy="mcp-tool-reapprove"]')).toBeVisible()
  await tools.locator('[data-cy="mcp-tools-select-all"]').click()
  await expect(tools.locator('[data-cy="mcp-tool-reapprove"]')).toBeVisible()
  await tools.locator('[data-cy="mcp-tool-reapprove"]').click()
  await expect(approval('tool-a')).toContainText('Confirm each invocation')
  await expect(approval('tool-new')).toContainText('No additional confirmation')
  await page.locator('[data-cy="draft-save-btn"]').click()
  await expect(page.locator('[data-cy="draft-save-btn"]')).toBeDisabled()
  await page.reload()
  await openMcp()
  await expect(tools.locator('[data-cy="mcp-tool-reapprove"]')).toHaveCount(0)
  await expect(approval('tool-a')).toContainText('Confirm each invocation')
  await expect(approval('tool-new')).toContainText('No additional confirmation')
  await page.locator('[data-cy="draft-preview-btn"]').click()
  const preview = page.locator('[data-cy="snapshot-preview-surface"]')
  await preview.getByText('MCP (1)', { exact: true }).click()
  await expect(preview.locator('[data-cy="preview-mcp-tool"]')).toHaveCount(2)
  await expect(preview.locator('[data-cy="preview-mcp-tool"]').filter({ hasText: 'tool-a' })).toContainText('Confirm each invocation')
  await expect(preview.locator('[data-cy="preview-mcp-tool"]').filter({ hasText: 'tool-new' })).toContainText('No additional confirmation')
  await preview.getByRole('button', { name: 'Close', exact: true }).click()
  await page.locator('[data-cy="draft-review-btn"]').click()
  page.once('dialog', dialog => dialog.accept())
  await page.locator('[data-cy="draft-publish-btn"]').click()
  await expect(page.locator('[data-cy="publish-outcome"]')).toContainText('Configuration published', { timeout: 60_000 })
  await page.reload()
  await openMcp()
  await expect(approval('tool-a')).toContainText('Confirm each invocation')
  await expect(approval('tool-new')).toContainText('No additional confirmation')
  // Removing approvals retains visible assistant references for explicit repair.
  await mode('deleted')
  await tools.locator('[data-cy="mcp-discover"]').click()
  await expect(tools.locator('[data-cy="mcp-tool-missing"]')).toHaveCount(2)
  await tools.locator('[data-cy="mcp-tools-clear"]').click()
  await page.locator('[data-cy="config-section-assistants"]').click()
  await page.getByText('E2E Assistant', { exact: true }).first().click()
  await page.locator('[data-cy="assistant-section-connections"]').click()
  await expect(page.locator('[data-cy="assistant-mcp-tools"]')).toContainText('outside the server allowlist')
  await page.locator('[data-cy="assistant-mcp-tools"]').getByRole('button', { name: 'Clear allowlist', exact: true }).click()
  await expect(page.locator('[data-cy="assistant-tools-empty-error"]')).toBeVisible()
  await mode('initial')
  await openMcp()
  await tools.locator('[data-cy="mcp-discover"]').click()
  await tools.locator('[data-tool-name="tool-a"] [data-cy="mcp-tool-select"]').click()
  await expect(approval('tool-a')).toContainText('No additional confirmation')
  await page.locator('[data-cy="config-section-assistants"]').click()
  await page.locator('[data-cy="assistant-section-connections"]').click()
  await page.locator('[data-cy="assistant-tools-choose"]').click()
  await page.locator('[data-cy="assistant-tools-select-all"]').click()
  await page.locator('[data-cy="assistant-tool-picker-done"]').click()
  await page.locator('[data-cy="draft-save-btn"]').click()
  await expect(page.locator('[data-cy="draft-save-btn"]')).toBeDisabled()
  await page.locator('[data-cy="draft-preview-btn"]').click()
  await preview.getByText('MCP (1)', { exact: true }).click()
  await expect(preview.locator('[data-cy="preview-mcp-tool"]')).toContainText('No additional confirmation')
  await preview.getByRole('button', { name: 'Close', exact: true }).click()
  await page.locator('[data-cy="draft-review-btn"]').click()
  page.once('dialog', dialog => dialog.accept())
  await page.locator('[data-cy="draft-publish-btn"]').click()
  await expect(page.locator('[data-cy="publish-outcome"]')).toContainText('Configuration published', { timeout: 60_000 })
  // All is a deliberate server-level binding, with dynamic discovery and no hidden list.
  await page.reload()
  await openMcp()
  await tools.locator('[data-cy="mcp-tool-mode"]').getByRole('button', { name: 'All tools', exact: true }).click()
  await expect(tools.locator('[data-cy="mcp-tools-all"]')).toBeVisible()
  await expect(tools.locator('[data-cy="mcp-tools-all"]')).toContainText('New tools')
  await expect(tools.locator('[data-tool-name]')).toHaveCount(0)
  await expect(tools.locator('[data-cy="mcp-tools-select-all"]')).toHaveCount(0)
  await expect(tools.locator('[data-cy="mcp-tool-approval"]')).toHaveCount(0)
  await mode('added')
  await tools.locator('[data-cy="mcp-discover"]').click()
  await expect(tools.locator('[data-tool-name="tool-new"]')).toBeVisible()
  await expect(tools.locator('[data-cy="mcp-tool-select"]')).toHaveCount(0)
  await page.locator('[data-cy="config-section-assistants"]').click()
  await page.getByText('E2E Assistant', { exact: true }).first().click()
  await page.locator('[data-cy="assistant-section-connections"]').click()
  const useServer = page.locator('[data-cy="assistant-mcp-use"]')
  await expect(useServer).toContainText('Require this MCP')
  await useServer.click()
  await expect(page.locator('[data-cy="assistant-tool-mode"]')).toHaveCount(0)
  await expect(page.locator('[data-cy="assistant-mcp-optional"]')).toContainText('Users can select')
  await page.locator('[data-cy="draft-save-btn"]').click()
  await expect(page.locator('[data-cy="draft-save-btn"]')).toBeDisabled()
  await page.locator('[data-cy="draft-preview-btn"]').click()
  await preview.getByText('MCP (1)', { exact: true }).click()
  await expect(preview.locator('[data-cy="preview-mcp-all"]')).toBeVisible()
  await preview.getByText('Assistants (1)', { exact: true }).click()
  await expect(preview.locator('[data-cy="preview-assistant-optional"]')).toContainText('No required MCP servers')
  await expect(preview.locator('[data-cy="preview-assistant-tools"]')).toHaveCount(0)
  await preview.getByRole('button', { name: 'Close', exact: true }).click()
  await page.locator('[data-cy="draft-review-btn"]').click()
  page.once('dialog', dialog => dialog.accept())
  await page.locator('[data-cy="draft-publish-btn"]').click()
  await expect(page.locator('[data-cy="publish-outcome"]')).toContainText('Configuration published', { timeout: 60_000 })
  await page.reload()
  await page.locator('[data-cy="config-section-assistants"]').click()
  await page.getByText('E2E Assistant', { exact: true }).first().click()
  await page.locator('[data-cy="assistant-section-connections"]').click()
  await expect(useServer).toHaveAttribute('aria-checked', 'false')
  await useServer.click()
  await expect(page.locator('[data-cy="assistant-tools-all"]')).toBeVisible()
  await page.locator('[data-cy="draft-save-btn"]').click()
  await expect(page.locator('[data-cy="draft-save-btn"]')).toBeDisabled()
  await page.locator('[data-cy="draft-preview-btn"]').click()
  await preview.getByText('MCP (1)', { exact: true }).click()
  await expect(preview.locator('[data-cy="preview-mcp-all"]')).toContainText('including new tools')
  await preview.getByText('Assistants (1)', { exact: true }).click()
  await expect(preview.locator('[data-cy="preview-assistant-tools"]')).toContainText('as its catalog changes')
  await preview.getByRole('button', { name: 'Close', exact: true }).click()
  await page.locator('[data-cy="draft-review-btn"]').click()
  page.once('dialog', dialog => dialog.accept())
  await page.locator('[data-cy="draft-publish-btn"]').click()
  await expect(page.locator('[data-cy="publish-outcome"]')).toContainText('Configuration published', { timeout: 60_000 })
  await page.reload()
  await openMcp()
  await expect(tools.locator('[data-tool-name]')).toHaveCount(0)
  await tools.locator('[data-cy="mcp-catalog-toggle"]').click()
  await tools.locator('[data-cy="mcp-tool-search"]').fill('newly')
  await expect(tools.locator('[data-tool-name="tool-new"]')).toBeVisible()
  await expect(page.locator('[data-cy="draft-save-btn"]')).toBeDisabled()
  await mode('dense')
  await tools.locator('[data-cy="mcp-discover"]').click()
  await tools.locator('[data-cy="mcp-tool-search"]').fill('')
  await expect(tools.locator('[data-tool-name]')).toHaveCount(27)
  await expect(tools.locator('[data-cy="mcp-tools-pages"]')).toHaveCount(0)
  expect(await tools.locator('[data-cy="mcp-catalog-rows"]').evaluate(el => el.clientHeight)).toBeLessThanOrEqual(440)
  expect(await tools.locator('[data-tool-name="firecrawl_agent"]').evaluate(el => el.clientHeight)).toBeLessThan(85)
  await tools.locator('[data-tool-name="firecrawl_agent"] [data-cy="mcp-tool-details"]').click()
  await expect(page.locator('[data-cy="mcp-tool-dialog"]')).toContainText('Complete definition end.')
  await page.locator('[data-cy="mcp-tool-dialog"]').getByRole('button', { name: 'Close', exact: true }).click()
  await page.screenshot({ path: '../.artifacts/mcp-catalog-ux-desktop.png', fullPage: true })
  await page.locator('[data-cy="config-section-assistants"]').click()
  await page.getByText('E2E Assistant', { exact: true }).first().click()
  await page.locator('[data-cy="assistant-section-connections"]').click()
  await page.locator('[data-cy="assistant-tool-mode"]').getByRole('button', { name: 'Selected tools', exact: true }).click()
  await page.locator('[data-cy="assistant-tools-choose"]').click()
  const picker = page.locator('[data-cy="assistant-tool-picker"]')
  const assistantSearch = picker.locator('[data-cy="assistant-tool-search"]')
  await expect(picker).toContainText('E2E Test MCP')
  await assistantSearch.fill('structured website research')
  const researchOption = page.locator('[data-tool-option="firecrawl_agent"]')
  await expect(researchOption).toContainText('Structured website research')
  await researchOption.locator('[data-cy="assistant-tool-details"]').click()
  await expect(page.locator('[data-cy="mcp-tool-dialog"]')).toContainText('Complete definition end.')
  await page.locator('[data-cy="mcp-tool-dialog"]').getByRole('button', { name: 'Close', exact: true }).click()
  await expect(researchOption.locator('[data-cy="assistant-tool-state"]')).toHaveText('Not selected')
  await researchOption.locator('[data-cy="assistant-tool-checkbox"]').click()
  await expect(researchOption.locator('[data-cy="assistant-tool-state"]')).toHaveText('Selected')
  await expect(researchOption.locator('[data-cy="assistant-tool-checkbox"]')).toHaveAttribute('aria-checked', 'true')
  await assistantSearch.fill('')
  await expect(picker.locator('[data-tool-option="research_01"] [data-cy="assistant-tool-state"]')).toHaveText('Not selected')
  await page.locator('[data-cy="assistant-tools-select-all"]').click()
  await expect(picker).toContainText('27 selected')
  expect(await researchOption.locator('.mcp-tool-description').evaluate(el => el.clientWidth < el.scrollWidth)).toBe(true)
  expect(await picker.evaluate(el => { const rect = el.getBoundingClientRect(); return rect.top >= 0 && rect.bottom <= innerHeight && rect.left >= 0 && rect.right <= innerWidth })).toBe(true)
  await page.screenshot({ path: '../.artifacts/mcp-catalog-ux-picker-desktop.png', fullPage: true })
  await picker.press('Escape')
  await expect(picker).toBeHidden()
  await expect(page.locator('[data-cy="assistant-mcp-tools"]')).toContainText('27 selected tools')
  await page.locator('[data-cy="assistant-tools-choose"]').click()
  await expect(picker).toContainText('27 selected')
  await picker.getByRole('button', { name: 'Close', exact: true }).click()
  await expect(picker).toBeHidden()
  await page.locator('[data-cy="assistant-tools-choose"]').click()
  await picker.locator('[data-cy="assistant-tool-picker-done"]').click()
  await expect(page.locator('[data-cy="assistant-tool-summary"] .q-chip')).toHaveCount(2)
  expect(await page.locator('[data-cy="assistant-tool-summary"]').evaluate(el => el.clientHeight)).toBeLessThan(110)
  await page.locator('[data-cy="assistant-tool-mode"]').getByRole('button', { name: 'All tools', exact: true }).click()
  await page.locator('[data-cy="draft-save-btn"]').click()
  await expect(page.locator('[data-cy="draft-save-btn"]')).toBeDisabled()
  await page.setViewportSize({ width: 320, height: 720 })
  await openMcp()
  await mode('large')
  await tools.locator('[data-cy="mcp-discover"]').click()
  await expect(tools.locator('[data-tool-name]')).toHaveCount(50)
  await tools.locator('[data-cy="mcp-tools-pages"]').getByRole('button', { name: '2', exact: true }).click()
  await expect(tools.locator('[data-tool-name="tool-050"]')).toBeVisible()
  await expect(tools.locator('[data-tool-name]')).toHaveCount(14)
  await tools.locator('[data-cy="mcp-tool-search"]').fill('item 62')
  await expect(tools.locator('[data-tool-name="tool-062"]')).toBeVisible()
  await expect(tools.locator('[data-tool-name]')).toHaveCount(1)
  await expect(tools.locator('[data-cy="mcp-tools-pages"]')).toHaveCount(0)
  await tools.locator('[data-cy="mcp-tool-search"]').fill('')
  await expect(tools.locator('[data-tool-name="tool-000"]')).toBeVisible()
  await tools.locator('[data-cy="mcp-tool-details"]').first().click()
  await expect(page.locator('[data-cy="mcp-tool-dialog"]')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: '../.artifacts/mcp-tools-mobile.png', fullPage: true })
  await page.locator('[data-cy="mcp-tool-dialog"]').getByRole('button', { name: 'Close', exact: true }).click()
  await page.locator('[data-cy="configuration-section-nav"]').getByRole('combobox').click()
  await page.getByRole('option', { name: 'Assistants', exact: true }).click()
  await expect(page.locator('[data-cy="assistant-name"]')).toHaveValue('E2E Assistant')
  await page.locator('[data-cy="assistant-section-connections"]').click()
  await page.locator('[data-cy="assistant-tool-mode"]').getByRole('button', { name: 'Selected tools', exact: true }).click()
  await page.locator('[data-cy="assistant-tools-choose"]').click()
  await assistantSearch.fill('tool-062')
  await expect(page.locator('[data-tool-option="tool-062"]')).toBeVisible()
  await expect(picker.locator('[data-tool-option]')).toHaveCount(1)
  await page.locator('[data-tool-option="tool-062"] [data-cy="assistant-tool-checkbox"]').click()
  await expect(picker.locator('[data-cy="assistant-tool-state"]')).toHaveText('Selected')
  expect(await picker.evaluate(el => { const rect = el.getBoundingClientRect(); return rect.top >= 0 && rect.bottom <= innerHeight && document.documentElement.scrollWidth <= innerWidth })).toBe(true)
  await page.screenshot({ path: '../.artifacts/mcp-catalog-ux-picker-mobile.png', fullPage: true })
  await picker.locator('[data-cy="assistant-tool-picker-done"]').click()
  await expect(page.locator('[data-cy="assistant-mcp-tools"]')).toContainText('tool-062')
  await page.locator('[data-cy="assistant-tool-mode"]').getByRole('button', { name: 'All tools', exact: true }).click()
  await mode('initial')
})

test('Workspace discovery separates directory identity from enterprise permissions using real Core APIs', async ({ page, request }) => {
  const adapter = process.env.MEASIX_E2E_ADAPTER_URL!
  await page.goto('/admin/')
  await page.locator('[data-cy="login-username"]').fill('admin')
  await page.locator('[data-cy="login-password"]').fill(process.env.MEASIX_E2E_ADMIN_PASSWORD!)
  await page.locator('[data-cy="login-submit"]').click()
  await expect(page).toHaveURL(/\/admin\/(overview)?$/)
  const session = await page.request.get('/api/admin/v1/session').then(r => r.json())
  const api = async (path: string, method = 'GET', data?: unknown) => {
    const response = await page.request.fetch(path, { method, data, headers: { 'X-CSRF-Token': session.csrfToken, 'Idempotency-Key': `idem_${randomUUID()}` } })
    expect(response.ok(), `${method} ${path}: ${await response.text()}`).toBe(true)
    return response.status() === 204 ? undefined : response.json()
  }
  const complete = async (operation: { operationId: string }) => {
    await expect.poll(async () => (await api(`/api/admin/v1/workspace-operations/${operation.operationId}`)).state, { timeout: 30000 }).toBe('COMPLETED')
  }
  const secret = await api('/api/admin/v1/secrets', 'POST', { name: 'Discovery fixture management', value: 'workspace-management-test' })
  const service = await api('/api/admin/v1/remote-workspace/services', 'POST', { name: 'Discovery workspace', expectedRevision: 0, config: { adminOrigin: adapter, mcpOrigin: adapter, managementSecret: { secretId: secret.secretId, secretVersion: secret.secretVersion }, connectTimeoutMs: 1000, idleTimeoutMs: 1000 } })
  const servicePath = `/api/admin/v1/remote-workspace/services/${service.workspaceServiceId}`
  await complete(await api(`${servicePath}/apply`, 'POST'))
  const originalDraft = await api('/api/admin/v1/draft')
  await api(`${servicePath}/mcp-draft`, 'POST', { expectedDraftRevision: originalDraft.draftRevision })
  const staged = await api('/api/admin/v1/draft')
  const workspaceMcp = staged.content.mcp.find((m: { mcpServerId: string }) => m.mcpServerId === service.mcpServerId)
  Object.assign(workspaceMcp, { displayName: 'Discovery workspace', toolAccessMode: 'ALL', allowedTools: [] })
  await api('/api/admin/v1/draft', 'PUT', { expectedDraftRevision: staged.draftRevision, content: staged.content })
  const users: { userId: string; username: string }[] = []
  const command = async (user: { userId: string }, action: string) => {
    const path = `/api/admin/v1/users/${user.userId}/workspace`
    const view = await api(path)
    await complete(await api(path, 'POST', { action, expectedRevision: view.bindingRevision, ...(action === 'DELETE' ? { confirmation: view.agentSpaceId } : {}) }))
  }
  const openWorkspaceMcp = async () => {
    await page.goto('/admin/resources')
    await page.locator('[data-cy="config-section-mcp"]').click()
    await page.getByText('Discovery workspace', { exact: true }).first().click()
  }
  try {
    await openWorkspaceMcp()
    const tools = page.locator('[data-cy="mcp-tools-editor"]')
    await expect(tools.locator('[data-cy="entity-picker-trigger"]')).toHaveCount(0)
    await tools.locator('[data-cy="mcp-discover"]').click()
    await expect(tools.locator('[data-cy="mcp-discovery-no-connections"]')).toBeVisible()
    await expect(tools.locator('[data-cy="mcp-manage-workspaces"]')).toHaveAttribute('href', '/admin/remote-workspaces')
    for (const name of ['Alice', 'Bob']) {
      const user = await api('/api/admin/v1/users', 'POST', { username: `discovery_${name.toLowerCase()}`, displayName: name, role: 'MEMBER' })
      users.push(user)
      await command(user, 'CREATE')
      if (name === 'Alice') {
        expect((await api(`/api/admin/v1/users/${user.userId}/workspace`)).mcpAvailable).toBe(false)
        expect((await request.post(`${adapter}/__mcp_mode`, { data: { mode: 'old-version' } })).ok()).toBe(true)
        await tools.locator('[data-cy="mcp-discover"]').click()
        await expect(tools.locator('[data-cy="mcp-discovery-connection"]')).toContainText('Alice')
        await expect(tools.locator('[data-cy="problem-banner"]')).toContainText('2024-11-05')
        await expect(tools.locator('[data-cy="mcp-previous-catalog-retained"]')).toHaveCount(0)
        await expect(tools.locator('[data-cy="entity-picker-trigger"]')).toHaveCount(0)
        expect((await request.post(`${adapter}/__mcp_mode`, { data: { mode: 'initial' } })).ok()).toBe(true)
        await tools.locator('[data-cy="mcp-discover"]').click()
        await expect(tools.locator('[data-tool-name="tool-a"]')).toBeVisible()
        const draft = await api('/api/admin/v1/draft')
        expect(draft.content.mcp.find((m: { mcpServerId: string }) => m.mcpServerId === service.mcpServerId).toolDiscovery.userId).toBe(user.userId)
      }
    }
    await tools.locator('[data-cy="mcp-discover"]').click()
    await expect(tools.locator('[data-cy="entity-picker-trigger"]')).toBeVisible()
    await tools.locator('[data-cy="entity-picker-trigger"]').click()
    await expect(page.locator('[data-cy="entity-picker-option"]')).toHaveCount(2)
    await page.locator('[data-cy="entity-picker-option"]').filter({ hasText: 'Bob' }).click()
    await tools.locator('[data-cy="mcp-discover-confirm"]').click()
    await expect(tools.locator('[data-cy="mcp-discovery-connection"]')).toContainText('Bob')
    await expect.poll(async () => {
      const draft = await api('/api/admin/v1/draft')
      return draft.content.mcp.find((m: { mcpServerId: string }) => m.mcpServerId === service.mcpServerId).toolDiscovery.userId
    }).toBe(users[1]!.userId)
    await expect(tools.locator('[data-cy="mcp-discover"]')).toBeEnabled()
    await expect(tools.locator('[data-cy="problem-banner"]')).toHaveCount(0)
    await page.screenshot({ path: '../.artifacts/mcp-workspace-discovery-desktop.png', fullPage: true })
    await page.setViewportSize({ width: 320, height: 720 })
    await tools.locator('[data-cy="mcp-discover"]').click()
    await expect(tools.locator('[data-cy="mcp-discover-confirm"]')).toBeDisabled()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: '../.artifacts/mcp-workspace-discovery-mobile.png', fullPage: true })
  } finally {
    expect((await request.post(`${adapter}/__mcp_mode`, { data: { mode: 'initial' } })).ok()).toBe(true)
    for (const user of users) await command(user, 'DELETE')
    await complete(await api(`${servicePath}/disable`, 'POST'))
    const latest = await api('/api/admin/v1/draft')
    await api('/api/admin/v1/draft', 'PUT', { expectedDraftRevision: latest.draftRevision, content: originalDraft.content })
  }
})
