import { test, expect } from '@playwright/test'

test('Direct MCP allowlist, assistant subset, discovery failure, drift review and mobile interaction', async ({ page, request }) => {
  const adapter = process.env.MEASIX_E2E_ADAPTER_URL!
  const mode = async (value: string) => { expect((await request.post(`${adapter}/__mcp_mode`, { data: { mode: value } })).ok()).toBe(true) }
  await page.goto('/admin/')
  await page.locator('[data-cy="login-username"]').fill('admin')
  await page.locator('[data-cy="login-password"]').fill(process.env.MEASIX_E2E_ADMIN_PASSWORD!)
  await page.locator('[data-cy="login-submit"]').click()
  await expect(page).toHaveURL(/\/admin\/(overview)?$/)
  await page.goto('/admin/resources')
  const openMcp = async () => {
    const desktop = page.locator('[data-cy="config-section-mcp"]')
    if ((page.viewportSize()?.width ?? 1280) >= 900) await desktop.click()
    else {
      await page.locator('[data-cy="configuration-section-nav"]').getByRole('combobox').click()
      await page.getByRole('option', { name: 'MCP', exact: true }).click()
    }
    await page.getByText('E2E Test MCP', { exact: true }).first().click()
  }
  await openMcp()
  const tools = page.locator('[data-cy="mcp-tools-editor"]')
  await expect(tools.locator('[data-tool-name="tool-a"] [data-cy="mcp-tool-select"]')).toHaveAttribute('aria-checked', 'true')
  await mode('added')
  await tools.locator('[data-cy="mcp-discover"]').click()
  await expect(tools.locator('[data-tool-name="tool-new"]')).toBeVisible()
  await expect(tools.locator('[data-tool-name="tool-new"] [data-cy="mcp-tool-select"]')).toHaveAttribute('aria-checked', 'false')
  await tools.locator('[data-cy="mcp-tool-search"]').fill('enterprise')
  await expect(tools.locator('[data-tool-name="tool-a"]')).toBeVisible()
  await expect(tools.locator('[data-tool-name="tool-new"]')).toHaveCount(0)
  await tools.locator('[data-cy="mcp-tool-search"]').fill('')
  await mode('failure')
  await tools.locator('[data-cy="mcp-discover"]').click()
  await expect(tools.locator('[data-cy="problem-banner"]')).toBeVisible()
  await expect(tools.locator('[data-tool-name="tool-new"]')).toBeVisible()
  await mode('drift')
  await tools.locator('[data-cy="mcp-discover"]').click()
  await expect(tools.locator('[data-cy="mcp-tool-reapprove"]')).toBeVisible()
  await tools.locator('[data-cy="mcp-tools-select-all"]').click()
  await expect(tools.locator('[data-cy="mcp-tool-reapprove"]')).toBeVisible()
  await tools.locator('[data-cy="mcp-tool-reapprove"]').click()
  await page.locator('[data-cy="draft-save-btn"]').click()
  await expect(page.locator('[data-cy="draft-save-btn"]')).toBeDisabled()
  await page.reload()
  await openMcp()
  await expect(tools.locator('[data-cy="mcp-tool-reapprove"]')).toHaveCount(0)
  // Removing approvals retains visible assistant references for explicit repair.
  await mode('deleted')
  await tools.locator('[data-cy="mcp-discover"]').click()
  await expect(tools.locator('[data-cy="mcp-tool-missing"]')).toHaveCount(2)
  await tools.locator('[data-cy="mcp-tools-clear"]').click()
  await page.locator('[data-cy="config-section-assistants"]').click()
  await page.getByText('E2E Assistant', { exact: true }).first().click()
  await page.locator('[data-cy="assistant-section-connections"]').click()
  await expect(page.locator('[data-cy="assistant-mcp-tools"]')).toContainText('outside the server allowlist')
  await page.locator('[data-cy="assistant-mcp-tools"]').getByRole('button', { name: 'Clear allowlist', exact: true }).click()
  await expect(page.locator('[data-cy="assistant-tools-empty-error"]')).toBeVisible()
  await mode('initial')
  await openMcp()
  await tools.locator('[data-cy="mcp-discover"]').click()
  await tools.locator('[data-tool-name="tool-a"] [data-cy="mcp-tool-select"]').click()
  await page.locator('[data-cy="config-section-assistants"]').click()
  await page.locator('[data-cy="assistant-section-connections"]').click()
  await page.locator('[data-cy="assistant-tools-select-all"]').click()
  await page.locator('[data-cy="draft-save-btn"]').click()
  await expect(page.locator('[data-cy="draft-save-btn"]')).toBeDisabled()
  await page.locator('[data-cy="draft-preview-btn"]').click()
  const preview = page.locator('[data-cy="snapshot-preview-surface"]')
  await preview.getByText('MCP (1)', { exact: true }).click()
  await expect(preview.locator('[data-cy="preview-mcp-tool"]')).toContainText('Confirm each invocation')
  await preview.getByRole('button', { name: 'Close', exact: true }).click()
  await page.locator('[data-cy="draft-review-btn"]').click()
  page.once('dialog', dialog => dialog.accept())
  await page.locator('[data-cy="draft-publish-btn"]').click()
  await expect(page.locator('[data-cy="publish-outcome"]')).toContainText('Configuration published', { timeout: 60_000 })
  // All is a deliberate server-level binding, with dynamic discovery and no hidden list.
  await page.reload()
  await openMcp()
  await tools.locator('[data-cy="mcp-tool-mode"]').getByRole('button', { name: 'All tools', exact: true }).click()
  await expect(tools.locator('[data-cy="mcp-tools-all"]')).toBeVisible()
  await mode('added')
  await tools.locator('[data-cy="mcp-discover"]').click()
  await expect(tools.locator('[data-tool-name="tool-new"]')).toBeVisible()
  await expect(tools.locator('[data-cy="mcp-tool-select"]')).toHaveCount(0)
  await page.locator('[data-cy="config-section-assistants"]').click()
  await page.getByText('E2E Assistant', { exact: true }).first().click()
  await page.locator('[data-cy="assistant-section-connections"]').click()
  const useServer = page.locator('[data-cy="assistant-mcp-use"]')
  await useServer.click()
  await expect(page.locator('[data-cy="assistant-tool-mode"]')).toHaveCount(0)
  await useServer.click()
  await expect(page.locator('[data-cy="assistant-tools-all"]')).toBeVisible()
  await page.locator('[data-cy="draft-save-btn"]').click()
  await expect(page.locator('[data-cy="draft-save-btn"]')).toBeDisabled()
  await page.locator('[data-cy="draft-preview-btn"]').click()
  await preview.getByText('MCP (1)', { exact: true }).click()
  await expect(preview.locator('[data-cy="preview-mcp-all"]')).toContainText('including new tools')
  await preview.getByText('Assistants (1)', { exact: true }).click()
  await expect(preview.locator('[data-cy="preview-assistant-tools"]')).toContainText('as its catalog changes')
  await preview.getByRole('button', { name: 'Close', exact: true }).click()
  await page.locator('[data-cy="draft-review-btn"]').click()
  page.once('dialog', dialog => dialog.accept())
  await page.locator('[data-cy="draft-publish-btn"]').click()
  await expect(page.locator('[data-cy="publish-outcome"]')).toContainText('Configuration published', { timeout: 60_000 })
  await page.reload()
  await page.setViewportSize({ width: 320, height: 720 })
  await openMcp()
  await mode('large')
  await tools.locator('[data-cy="mcp-discover"]').click()
  await expect(tools.locator('[data-tool-name]')).toHaveCount(25)
  await tools.locator('[data-cy="mcp-tools-pages"]').getByRole('button', { name: '2', exact: true }).click()
  await expect(tools.locator('[data-tool-name="tool-025"]')).toBeVisible()
  await expect(tools.locator('[data-tool-name]')).toHaveCount(25)
  await tools.locator('[data-cy="mcp-tool-search"]').fill('item 62')
  await expect(tools.locator('[data-tool-name="tool-062"]')).toBeVisible()
  await expect(tools.locator('[data-tool-name]')).toHaveCount(1)
  await expect(tools.locator('[data-cy="mcp-tools-pages"]')).toHaveCount(0)
  await tools.locator('[data-cy="mcp-tool-search"]').fill('')
  await expect(tools.locator('[data-tool-name="tool-000"]')).toBeVisible()
  await tools.locator('[data-cy="mcp-tool-details"]').first().click()
  await expect(page.locator('[data-cy="mcp-tool-dialog"]')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: '../.artifacts/mcp-tools-mobile.png', fullPage: true })
  await page.locator('[data-cy="mcp-tool-dialog"]').getByRole('button', { name: 'Close', exact: true }).click()
  await page.locator('[data-cy="configuration-section-nav"]').getByRole('combobox').click()
  await page.getByRole('option', { name: 'Assistants', exact: true }).click()
  await expect(page.locator('[data-cy="assistant-name"]')).toHaveValue('E2E Assistant')
  await page.locator('[data-cy="assistant-section-connections"]').click()
  await page.locator('[data-cy="assistant-tool-mode"]').getByRole('button', { name: 'Selected tools', exact: true }).click()
  await page.getByRole('combobox', { name: 'Tools for this assistant', exact: true }).fill('tool-062')
  await expect(page.getByRole('option', { name: 'tool-062', exact: true })).toBeVisible()
  await expect(page.getByRole('option')).toHaveCount(1)
  await page.getByRole('option', { name: 'tool-062', exact: true }).click()
  await page.keyboard.press('Escape')
  await expect(page.locator('[data-cy="assistant-mcp-tools"]')).toContainText('tool-062')
  await page.locator('[data-cy="assistant-tool-mode"]').getByRole('button', { name: 'All tools', exact: true }).click()
  await mode('initial')
})
