import { test, expect } from '@playwright/test'

test('Direct MCP allowlist, assistant subset, discovery failure, drift review and mobile interaction', async ({ page, request }) => {
  const adapter = process.env.MEASIX_E2E_ADAPTER_URL!
  const mode = async (value: string) => { expect((await request.post(`${adapter}/__mcp_mode`, { data: { mode: value } })).ok()).toBe(true) }
  await page.goto('/admin/')
  await page.locator('[data-cy="login-username"]').fill('admin')
  await page.locator('[data-cy="login-password"]').fill(process.env.MEASIX_E2E_ADMIN_PASSWORD!)
  await page.locator('[data-cy="login-submit"]').click()
  await expect(page).toHaveURL(/\/admin\/(overview)?$/)
  await page.goto('/admin/resources')
  const openMcp = async () => {
    const desktop = page.locator('[data-cy="config-section-mcp"]')
    if ((page.viewportSize()?.width ?? 1280) >= 900) await desktop.click()
    else {
      await page.locator('[data-cy="configuration-section-nav"]').getByRole('combobox').click()
      await page.getByRole('option', { name: 'MCP', exact: true }).click()
    }
    if (!await page.locator('[data-cy="mcp-tools-editor"]').isVisible()) await page.getByText('E2E Test MCP', { exact: true }).first().click()
  }
  await openMcp()
  const tools = page.locator('[data-cy="mcp-tools-editor"]')
  await expect(tools.locator('[data-tool-name="tool-a"] [data-cy="mcp-tool-select"]')).toHaveAttribute('aria-checked', 'true')
  const approval = (name: string) => tools.locator(`[data-tool-name="${name}"] [data-cy="mcp-tool-approval"]`)
  await expect(approval('tool-a')).toContainText('No additional confirmation')
  await approval('tool-a').getByRole('combobox').click()
  await page.getByRole('option', { name: 'Confirm each invocation', exact: true }).click()
  await mode('added')
  await tools.locator('[data-cy="mcp-discover"]').click()
  await expect(tools.locator('[data-tool-name="tool-new"]')).toBeVisible()
  await expect(tools.locator('[data-tool-name="tool-new"] [data-cy="mcp-tool-select"]')).toHaveAttribute('aria-checked', 'false')
  await tools.locator('[data-cy="mcp-tool-search"]').fill('enterprise')
  await expect(tools.locator('[data-tool-name="tool-a"]')).toBeVisible()
  await expect(tools.locator('[data-tool-name="tool-new"]')).toHaveCount(0)
  await tools.locator('[data-cy="mcp-tool-search"]').fill('')
  await mode('failure')
  await tools.locator('[data-cy="mcp-discover"]').click()
  await expect(tools.locator('[data-cy="problem-banner"]')).toBeVisible()
  await expect(tools.locator('[data-tool-name="tool-new"]')).toBeVisible()
  await mode('drift')
  await tools.locator('[data-cy="mcp-discover"]').click()
  await expect(tools.locator('[data-cy="mcp-tool-reapprove"]')).toBeVisible()
  await tools.locator('[data-cy="mcp-tools-select-all"]').click()
  await expect(tools.locator('[data-cy="mcp-tool-reapprove"]')).toBeVisible()
  await tools.locator('[data-cy="mcp-tool-reapprove"]').click()
  await expect(approval('tool-a')).toContainText('Confirm each invocation')
  await expect(approval('tool-new')).toContainText('No additional confirmation')
  await page.locator('[data-cy="draft-save-btn"]').click()
  await expect(page.locator('[data-cy="draft-save-btn"]')).toBeDisabled()
  await page.reload()
  await openMcp()
  await expect(tools.locator('[data-cy="mcp-tool-reapprove"]')).toHaveCount(0)
  await expect(approval('tool-a')).toContainText('Confirm each invocation')
  await expect(approval('tool-new')).toContainText('No additional confirmation')
  await page.locator('[data-cy="draft-preview-btn"]').click()
  const preview = page.locator('[data-cy="snapshot-preview-surface"]')
  await preview.getByText('MCP (1)', { exact: true }).click()
  await expect(preview.locator('[data-cy="preview-mcp-tool"]')).toHaveCount(2)
  await expect(preview.locator('[data-cy="preview-mcp-tool"]').filter({ hasText: 'tool-a' })).toContainText('Confirm each invocation')
  await expect(preview.locator('[data-cy="preview-mcp-tool"]').filter({ hasText: 'tool-new' })).toContainText('No additional confirmation')
  await preview.getByRole('button', { name: 'Close', exact: true }).click()
  await page.locator('[data-cy="draft-review-btn"]').click()
  page.once('dialog', dialog => dialog.accept())
  await page.locator('[data-cy="draft-publish-btn"]').click()
  await expect(page.locator('[data-cy="publish-outcome"]')).toContainText('Configuration published', { timeout: 60_000 })
  await page.reload()
  await openMcp()
  await expect(approval('tool-a')).toContainText('Confirm each invocation')
  await expect(approval('tool-new')).toContainText('No additional confirmation')
  // Removing approvals retains visible assistant references for explicit repair.
  await mode('deleted')
  await tools.locator('[data-cy="mcp-discover"]').click()
  await expect(tools.locator('[data-cy="mcp-tool-missing"]')).toHaveCount(2)
  await tools.locator('[data-cy="mcp-tools-clear"]').click()
  await page.locator('[data-cy="config-section-assistants"]').click()
  await page.getByText('E2E Assistant', { exact: true }).first().click()
  await page.locator('[data-cy="assistant-section-connections"]').click()
  await expect(page.locator('[data-cy="assistant-mcp-tools"]')).toContainText('outside the server allowlist')
  await page.locator('[data-cy="assistant-mcp-tools"]').getByRole('button', { name: 'Clear allowlist', exact: true }).click()
  await expect(page.locator('[data-cy="assistant-tools-empty-error"]')).toBeVisible()
  await mode('initial')
  await openMcp()
  await tools.locator('[data-cy="mcp-discover"]').click()
  await tools.locator('[data-tool-name="tool-a"] [data-cy="mcp-tool-select"]').click()
  await expect(approval('tool-a')).toContainText('No additional confirmation')
  await page.locator('[data-cy="config-section-assistants"]').click()
  await page.locator('[data-cy="assistant-section-connections"]').click()
  await page.locator('[data-cy="assistant-tools-choose"]').click()
  await page.locator('[data-cy="assistant-tools-select-all"]').click()
  await page.locator('[data-cy="assistant-tool-picker-done"]').click()
  await page.locator('[data-cy="draft-save-btn"]').click()
  await expect(page.locator('[data-cy="draft-save-btn"]')).toBeDisabled()
  await page.locator('[data-cy="draft-preview-btn"]').click()
  await preview.getByText('MCP (1)', { exact: true }).click()
  await expect(preview.locator('[data-cy="preview-mcp-tool"]')).toContainText('No additional confirmation')
  await preview.getByRole('button', { name: 'Close', exact: true }).click()
  await page.locator('[data-cy="draft-review-btn"]').click()
  page.once('dialog', dialog => dialog.accept())
  await page.locator('[data-cy="draft-publish-btn"]').click()
  await expect(page.locator('[data-cy="publish-outcome"]')).toContainText('Configuration published', { timeout: 60_000 })
  // All is a deliberate server-level binding, with dynamic discovery and no hidden list.
  await page.reload()
  await openMcp()
  await tools.locator('[data-cy="mcp-tool-mode"]').getByRole('button', { name: 'All tools', exact: true }).click()
  await expect(tools.locator('[data-cy="mcp-tools-all"]')).toBeVisible()
  await expect(tools.locator('[data-cy="mcp-tools-all"]')).toContainText('New tools')
  await expect(tools.locator('[data-tool-name]')).toHaveCount(0)
  await expect(tools.locator('[data-cy="mcp-tools-select-all"]')).toHaveCount(0)
  await expect(tools.locator('[data-cy="mcp-tool-approval"]')).toHaveCount(0)
  await mode('added')
  await tools.locator('[data-cy="mcp-discover"]').click()
  await expect(tools.locator('[data-tool-name="tool-new"]')).toBeVisible()
  await expect(tools.locator('[data-cy="mcp-tool-select"]')).toHaveCount(0)
  await page.locator('[data-cy="config-section-assistants"]').click()
  await page.getByText('E2E Assistant', { exact: true }).first().click()
  await page.locator('[data-cy="assistant-section-connections"]').click()
  const useServer = page.locator('[data-cy="assistant-mcp-use"]')
  await useServer.click()
  await expect(page.locator('[data-cy="assistant-tool-mode"]')).toHaveCount(0)
  await useServer.click()
  await expect(page.locator('[data-cy="assistant-tools-all"]')).toBeVisible()
  await page.locator('[data-cy="draft-save-btn"]').click()
  await expect(page.locator('[data-cy="draft-save-btn"]')).toBeDisabled()
  await page.locator('[data-cy="draft-preview-btn"]').click()
  await preview.getByText('MCP (1)', { exact: true }).click()
  await expect(preview.locator('[data-cy="preview-mcp-all"]')).toContainText('including new tools')
  await preview.getByText('Assistants (1)', { exact: true }).click()
  await expect(preview.locator('[data-cy="preview-assistant-tools"]')).toContainText('as its catalog changes')
  await preview.getByRole('button', { name: 'Close', exact: true }).click()
  await page.locator('[data-cy="draft-review-btn"]').click()
  page.once('dialog', dialog => dialog.accept())
  await page.locator('[data-cy="draft-publish-btn"]').click()
  await expect(page.locator('[data-cy="publish-outcome"]')).toContainText('Configuration published', { timeout: 60_000 })
  await page.reload()
  await openMcp()
  await expect(tools.locator('[data-tool-name]')).toHaveCount(0)
  await tools.locator('[data-cy="mcp-catalog-toggle"]').click()
  await tools.locator('[data-cy="mcp-tool-search"]').fill('newly')
  await expect(tools.locator('[data-tool-name="tool-new"]')).toBeVisible()
  await expect(page.locator('[data-cy="draft-save-btn"]')).toBeDisabled()
  await mode('dense')
  await tools.locator('[data-cy="mcp-discover"]').click()
  await tools.locator('[data-cy="mcp-tool-search"]').fill('')
  await expect(tools.locator('[data-tool-name]')).toHaveCount(27)
  await expect(tools.locator('[data-cy="mcp-tools-pages"]')).toHaveCount(0)
  expect(await tools.locator('[data-cy="mcp-catalog-rows"]').evaluate(el => el.clientHeight)).toBeLessThanOrEqual(440)
  expect(await tools.locator('[data-tool-name="firecrawl_agent"]').evaluate(el => el.clientHeight)).toBeLessThan(85)
  await tools.locator('[data-tool-name="firecrawl_agent"] [data-cy="mcp-tool-details"]').click()
  await expect(page.locator('[data-cy="mcp-tool-dialog"]')).toContainText('Complete definition end.')
  await page.locator('[data-cy="mcp-tool-dialog"]').getByRole('button', { name: 'Close', exact: true }).click()
  await page.screenshot({ path: '../.artifacts/mcp-catalog-ux-desktop.png', fullPage: true })
  await page.locator('[data-cy="config-section-assistants"]').click()
  await page.getByText('E2E Assistant', { exact: true }).first().click()
  await page.locator('[data-cy="assistant-section-connections"]').click()
  await page.locator('[data-cy="assistant-tool-mode"]').getByRole('button', { name: 'Selected tools', exact: true }).click()
  await page.locator('[data-cy="assistant-tools-choose"]').click()
  const picker = page.locator('[data-cy="assistant-tool-picker"]')
  const assistantSearch = picker.locator('[data-cy="assistant-tool-search"]')
  await expect(picker).toContainText('E2E Test MCP')
  await assistantSearch.fill('structured website research')
  const researchOption = page.locator('[data-tool-option="firecrawl_agent"]')
  await expect(researchOption).toContainText('Structured website research')
  await researchOption.locator('[data-cy="assistant-tool-details"]').click()
  await expect(page.locator('[data-cy="mcp-tool-dialog"]')).toContainText('Complete definition end.')
  await page.locator('[data-cy="mcp-tool-dialog"]').getByRole('button', { name: 'Close', exact: true }).click()
  await expect(researchOption.locator('[data-cy="assistant-tool-state"]')).toHaveText('Not selected')
  await researchOption.locator('[data-cy="assistant-tool-checkbox"]').click()
  await expect(researchOption.locator('[data-cy="assistant-tool-state"]')).toHaveText('Selected')
  await expect(researchOption.locator('[data-cy="assistant-tool-checkbox"]')).toHaveAttribute('aria-checked', 'true')
  await assistantSearch.fill('')
  await expect(picker.locator('[data-tool-option="research_01"] [data-cy="assistant-tool-state"]')).toHaveText('Not selected')
  await page.locator('[data-cy="assistant-tools-select-all"]').click()
  await expect(picker).toContainText('27 selected')
  expect(await researchOption.locator('.mcp-tool-description').evaluate(el => el.clientWidth < el.scrollWidth)).toBe(true)
  expect(await picker.evaluate(el => { const rect = el.getBoundingClientRect(); return rect.top >= 0 && rect.bottom <= innerHeight && rect.left >= 0 && rect.right <= innerWidth })).toBe(true)
  await page.screenshot({ path: '../.artifacts/mcp-catalog-ux-picker-desktop.png', fullPage: true })
  await picker.press('Escape')
  await expect(picker).toBeHidden()
  await expect(page.locator('[data-cy="assistant-mcp-tools"]')).toContainText('27 selected tools')
  await page.locator('[data-cy="assistant-tools-choose"]').click()
  await expect(picker).toContainText('27 selected')
  await picker.getByRole('button', { name: 'Close', exact: true }).click()
  await expect(picker).toBeHidden()
  await page.locator('[data-cy="assistant-tools-choose"]').click()
  await picker.locator('[data-cy="assistant-tool-picker-done"]').click()
  await expect(page.locator('[data-cy="assistant-tool-summary"] .q-chip')).toHaveCount(2)
  expect(await page.locator('[data-cy="assistant-tool-summary"]').evaluate(el => el.clientHeight)).toBeLessThan(110)
  await page.locator('[data-cy="assistant-tool-mode"]').getByRole('button', { name: 'All tools', exact: true }).click()
  await page.locator('[data-cy="draft-save-btn"]').click()
  await expect(page.locator('[data-cy="draft-save-btn"]')).toBeDisabled()
  await page.setViewportSize({ width: 320, height: 720 })
  await openMcp()
  await mode('large')
  await tools.locator('[data-cy="mcp-discover"]').click()
  await expect(tools.locator('[data-tool-name]')).toHaveCount(50)
  await tools.locator('[data-cy="mcp-tools-pages"]').getByRole('button', { name: '2', exact: true }).click()
  await expect(tools.locator('[data-tool-name="tool-050"]')).toBeVisible()
  await expect(tools.locator('[data-tool-name]')).toHaveCount(14)
  await tools.locator('[data-cy="mcp-tool-search"]').fill('item 62')
  await expect(tools.locator('[data-tool-name="tool-062"]')).toBeVisible()
  await expect(tools.locator('[data-tool-name]')).toHaveCount(1)
  await expect(tools.locator('[data-cy="mcp-tools-pages"]')).toHaveCount(0)
  await tools.locator('[data-cy="mcp-tool-search"]').fill('')
  await expect(tools.locator('[data-tool-name="tool-000"]')).toBeVisible()
  await tools.locator('[data-cy="mcp-tool-details"]').first().click()
  await expect(page.locator('[data-cy="mcp-tool-dialog"]')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: '../.artifacts/mcp-tools-mobile.png', fullPage: true })
  await page.locator('[data-cy="mcp-tool-dialog"]').getByRole('button', { name: 'Close', exact: true }).click()
  await page.locator('[data-cy="configuration-section-nav"]').getByRole('combobox').click()
  await page.getByRole('option', { name: 'Assistants', exact: true }).click()
  await expect(page.locator('[data-cy="assistant-name"]')).toHaveValue('E2E Assistant')
  await page.locator('[data-cy="assistant-section-connections"]').click()
  await page.locator('[data-cy="assistant-tool-mode"]').getByRole('button', { name: 'Selected tools', exact: true }).click()
  await page.locator('[data-cy="assistant-tools-choose"]').click()
  await assistantSearch.fill('tool-062')
  await expect(page.locator('[data-tool-option="tool-062"]')).toBeVisible()
  await expect(picker.locator('[data-tool-option]')).toHaveCount(1)
  await page.locator('[data-tool-option="tool-062"] [data-cy="assistant-tool-checkbox"]').click()
  await expect(picker.locator('[data-cy="assistant-tool-state"]')).toHaveText('Selected')
  expect(await picker.evaluate(el => { const rect = el.getBoundingClientRect(); return rect.top >= 0 && rect.bottom <= innerHeight && document.documentElement.scrollWidth <= innerWidth })).toBe(true)
  await page.screenshot({ path: '../.artifacts/mcp-catalog-ux-picker-mobile.png', fullPage: true })
  await picker.locator('[data-cy="assistant-tool-picker-done"]').click()
  await expect(page.locator('[data-cy="assistant-mcp-tools"]')).toContainText('tool-062')
  await page.locator('[data-cy="assistant-tool-mode"]').getByRole('button', { name: 'All tools', exact: true }).click()
  await mode('initial')
})
