// Code generated by ent, DO NOT EDIT.

package enterpriseupdate

import (
	"measix/platform/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldContainsFold(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEQ(FieldTitle, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEQ(FieldContent, v))
}

// ContentFormat applies equality check predicate on the "content_format" field. It's identical to ContentFormatEQ.
func ContentFormat(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEQ(FieldContentFormat, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEQ(FieldCategory, v))
}

// Severity applies equality check predicate on the "severity" field. It's identical to SeverityEQ.
func Severity(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEQ(FieldSeverity, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEQ(FieldStatus, v))
}

// PublishedAt applies equality check predicate on the "published_at" field. It's identical to PublishedAtEQ.
func PublishedAt(v time.Time) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEQ(FieldPublishedAt, v))
}

// FeedRevision applies equality check predicate on the "feed_revision" field. It's identical to FeedRevisionEQ.
func FeedRevision(v int64) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEQ(FieldFeedRevision, v))
}

// CreatedByUserID applies equality check predicate on the "created_by_user_id" field. It's identical to CreatedByUserIDEQ.
func CreatedByUserID(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEQ(FieldCreatedByUserID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEQ(FieldUpdatedAt, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldContainsFold(FieldTitle, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldContainsFold(FieldContent, v))
}

// ContentFormatEQ applies the EQ predicate on the "content_format" field.
func ContentFormatEQ(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEQ(FieldContentFormat, v))
}

// ContentFormatNEQ applies the NEQ predicate on the "content_format" field.
func ContentFormatNEQ(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldNEQ(FieldContentFormat, v))
}

// ContentFormatIn applies the In predicate on the "content_format" field.
func ContentFormatIn(vs ...string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldIn(FieldContentFormat, vs...))
}

// ContentFormatNotIn applies the NotIn predicate on the "content_format" field.
func ContentFormatNotIn(vs ...string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldNotIn(FieldContentFormat, vs...))
}

// ContentFormatGT applies the GT predicate on the "content_format" field.
func ContentFormatGT(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldGT(FieldContentFormat, v))
}

// ContentFormatGTE applies the GTE predicate on the "content_format" field.
func ContentFormatGTE(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldGTE(FieldContentFormat, v))
}

// ContentFormatLT applies the LT predicate on the "content_format" field.
func ContentFormatLT(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldLT(FieldContentFormat, v))
}

// ContentFormatLTE applies the LTE predicate on the "content_format" field.
func ContentFormatLTE(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldLTE(FieldContentFormat, v))
}

// ContentFormatContains applies the Contains predicate on the "content_format" field.
func ContentFormatContains(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldContains(FieldContentFormat, v))
}

// ContentFormatHasPrefix applies the HasPrefix predicate on the "content_format" field.
func ContentFormatHasPrefix(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldHasPrefix(FieldContentFormat, v))
}

// ContentFormatHasSuffix applies the HasSuffix predicate on the "content_format" field.
func ContentFormatHasSuffix(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldHasSuffix(FieldContentFormat, v))
}

// ContentFormatEqualFold applies the EqualFold predicate on the "content_format" field.
func ContentFormatEqualFold(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEqualFold(FieldContentFormat, v))
}

// ContentFormatContainsFold applies the ContainsFold predicate on the "content_format" field.
func ContentFormatContainsFold(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldContainsFold(FieldContentFormat, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldContainsFold(FieldCategory, v))
}

// SeverityEQ applies the EQ predicate on the "severity" field.
func SeverityEQ(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEQ(FieldSeverity, v))
}

// SeverityNEQ applies the NEQ predicate on the "severity" field.
func SeverityNEQ(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldNEQ(FieldSeverity, v))
}

// SeverityIn applies the In predicate on the "severity" field.
func SeverityIn(vs ...string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldIn(FieldSeverity, vs...))
}

// SeverityNotIn applies the NotIn predicate on the "severity" field.
func SeverityNotIn(vs ...string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldNotIn(FieldSeverity, vs...))
}

// SeverityGT applies the GT predicate on the "severity" field.
func SeverityGT(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldGT(FieldSeverity, v))
}

// SeverityGTE applies the GTE predicate on the "severity" field.
func SeverityGTE(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldGTE(FieldSeverity, v))
}

// SeverityLT applies the LT predicate on the "severity" field.
func SeverityLT(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldLT(FieldSeverity, v))
}

// SeverityLTE applies the LTE predicate on the "severity" field.
func SeverityLTE(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldLTE(FieldSeverity, v))
}

// SeverityContains applies the Contains predicate on the "severity" field.
func SeverityContains(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldContains(FieldSeverity, v))
}

// SeverityHasPrefix applies the HasPrefix predicate on the "severity" field.
func SeverityHasPrefix(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldHasPrefix(FieldSeverity, v))
}

// SeverityHasSuffix applies the HasSuffix predicate on the "severity" field.
func SeverityHasSuffix(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldHasSuffix(FieldSeverity, v))
}

// SeverityEqualFold applies the EqualFold predicate on the "severity" field.
func SeverityEqualFold(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEqualFold(FieldSeverity, v))
}

// SeverityContainsFold applies the ContainsFold predicate on the "severity" field.
func SeverityContainsFold(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldContainsFold(FieldSeverity, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldContainsFold(FieldStatus, v))
}

// PublishedAtEQ applies the EQ predicate on the "published_at" field.
func PublishedAtEQ(v time.Time) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEQ(FieldPublishedAt, v))
}

// PublishedAtNEQ applies the NEQ predicate on the "published_at" field.
func PublishedAtNEQ(v time.Time) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldNEQ(FieldPublishedAt, v))
}

// PublishedAtIn applies the In predicate on the "published_at" field.
func PublishedAtIn(vs ...time.Time) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldIn(FieldPublishedAt, vs...))
}

// PublishedAtNotIn applies the NotIn predicate on the "published_at" field.
func PublishedAtNotIn(vs ...time.Time) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldNotIn(FieldPublishedAt, vs...))
}

// PublishedAtGT applies the GT predicate on the "published_at" field.
func PublishedAtGT(v time.Time) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldGT(FieldPublishedAt, v))
}

// PublishedAtGTE applies the GTE predicate on the "published_at" field.
func PublishedAtGTE(v time.Time) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldGTE(FieldPublishedAt, v))
}

// PublishedAtLT applies the LT predicate on the "published_at" field.
func PublishedAtLT(v time.Time) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldLT(FieldPublishedAt, v))
}

// PublishedAtLTE applies the LTE predicate on the "published_at" field.
func PublishedAtLTE(v time.Time) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldLTE(FieldPublishedAt, v))
}

// PublishedAtIsNil applies the IsNil predicate on the "published_at" field.
func PublishedAtIsNil() predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldIsNull(FieldPublishedAt))
}

// PublishedAtNotNil applies the NotNil predicate on the "published_at" field.
func PublishedAtNotNil() predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldNotNull(FieldPublishedAt))
}

// FeedRevisionEQ applies the EQ predicate on the "feed_revision" field.
func FeedRevisionEQ(v int64) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEQ(FieldFeedRevision, v))
}

// FeedRevisionNEQ applies the NEQ predicate on the "feed_revision" field.
func FeedRevisionNEQ(v int64) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldNEQ(FieldFeedRevision, v))
}

// FeedRevisionIn applies the In predicate on the "feed_revision" field.
func FeedRevisionIn(vs ...int64) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldIn(FieldFeedRevision, vs...))
}

// FeedRevisionNotIn applies the NotIn predicate on the "feed_revision" field.
func FeedRevisionNotIn(vs ...int64) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldNotIn(FieldFeedRevision, vs...))
}

// FeedRevisionGT applies the GT predicate on the "feed_revision" field.
func FeedRevisionGT(v int64) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldGT(FieldFeedRevision, v))
}

// FeedRevisionGTE applies the GTE predicate on the "feed_revision" field.
func FeedRevisionGTE(v int64) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldGTE(FieldFeedRevision, v))
}

// FeedRevisionLT applies the LT predicate on the "feed_revision" field.
func FeedRevisionLT(v int64) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldLT(FieldFeedRevision, v))
}

// FeedRevisionLTE applies the LTE predicate on the "feed_revision" field.
func FeedRevisionLTE(v int64) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldLTE(FieldFeedRevision, v))
}

// CreatedByUserIDEQ applies the EQ predicate on the "created_by_user_id" field.
func CreatedByUserIDEQ(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEQ(FieldCreatedByUserID, v))
}

// CreatedByUserIDNEQ applies the NEQ predicate on the "created_by_user_id" field.
func CreatedByUserIDNEQ(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldNEQ(FieldCreatedByUserID, v))
}

// CreatedByUserIDIn applies the In predicate on the "created_by_user_id" field.
func CreatedByUserIDIn(vs ...string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldIn(FieldCreatedByUserID, vs...))
}

// CreatedByUserIDNotIn applies the NotIn predicate on the "created_by_user_id" field.
func CreatedByUserIDNotIn(vs ...string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldNotIn(FieldCreatedByUserID, vs...))
}

// CreatedByUserIDGT applies the GT predicate on the "created_by_user_id" field.
func CreatedByUserIDGT(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldGT(FieldCreatedByUserID, v))
}

// CreatedByUserIDGTE applies the GTE predicate on the "created_by_user_id" field.
func CreatedByUserIDGTE(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldGTE(FieldCreatedByUserID, v))
}

// CreatedByUserIDLT applies the LT predicate on the "created_by_user_id" field.
func CreatedByUserIDLT(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldLT(FieldCreatedByUserID, v))
}

// CreatedByUserIDLTE applies the LTE predicate on the "created_by_user_id" field.
func CreatedByUserIDLTE(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldLTE(FieldCreatedByUserID, v))
}

// CreatedByUserIDContains applies the Contains predicate on the "created_by_user_id" field.
func CreatedByUserIDContains(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldContains(FieldCreatedByUserID, v))
}

// CreatedByUserIDHasPrefix applies the HasPrefix predicate on the "created_by_user_id" field.
func CreatedByUserIDHasPrefix(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldHasPrefix(FieldCreatedByUserID, v))
}

// CreatedByUserIDHasSuffix applies the HasSuffix predicate on the "created_by_user_id" field.
func CreatedByUserIDHasSuffix(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldHasSuffix(FieldCreatedByUserID, v))
}

// CreatedByUserIDEqualFold applies the EqualFold predicate on the "created_by_user_id" field.
func CreatedByUserIDEqualFold(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEqualFold(FieldCreatedByUserID, v))
}

// CreatedByUserIDContainsFold applies the ContainsFold predicate on the "created_by_user_id" field.
func CreatedByUserIDContainsFold(v string) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldContainsFold(FieldCreatedByUserID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EnterpriseUpdate) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EnterpriseUpdate) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EnterpriseUpdate) predicate.EnterpriseUpdate {
	return predicate.EnterpriseUpdate(sql.NotPredicates(p))
}
