// Code generated by ent, DO NOT EDIT.

package upstream

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/topabomb/measix-platform-core/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContainsFold(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldName, v))
}

// ConfigRevision applies equality check predicate on the "config_revision" field. It's identical to ConfigRevisionEQ.
func ConfigRevision(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldConfigRevision, v))
}

// ActiveConfigRevision applies equality check predicate on the "active_config_revision" field. It's identical to ActiveConfigRevisionEQ.
func ActiveConfigRevision(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldActiveConfigRevision, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContainsFold(FieldName, v))
}

// ConfigRevisionEQ applies the EQ predicate on the "config_revision" field.
func ConfigRevisionEQ(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldConfigRevision, v))
}

// ConfigRevisionNEQ applies the NEQ predicate on the "config_revision" field.
func ConfigRevisionNEQ(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldConfigRevision, v))
}

// ConfigRevisionIn applies the In predicate on the "config_revision" field.
func ConfigRevisionIn(vs ...int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldConfigRevision, vs...))
}

// ConfigRevisionNotIn applies the NotIn predicate on the "config_revision" field.
func ConfigRevisionNotIn(vs ...int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldConfigRevision, vs...))
}

// ConfigRevisionGT applies the GT predicate on the "config_revision" field.
func ConfigRevisionGT(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldConfigRevision, v))
}

// ConfigRevisionGTE applies the GTE predicate on the "config_revision" field.
func ConfigRevisionGTE(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldConfigRevision, v))
}

// ConfigRevisionLT applies the LT predicate on the "config_revision" field.
func ConfigRevisionLT(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldConfigRevision, v))
}

// ConfigRevisionLTE applies the LTE predicate on the "config_revision" field.
func ConfigRevisionLTE(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldConfigRevision, v))
}

// ActiveConfigRevisionEQ applies the EQ predicate on the "active_config_revision" field.
func ActiveConfigRevisionEQ(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldActiveConfigRevision, v))
}

// ActiveConfigRevisionNEQ applies the NEQ predicate on the "active_config_revision" field.
func ActiveConfigRevisionNEQ(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldActiveConfigRevision, v))
}

// ActiveConfigRevisionIn applies the In predicate on the "active_config_revision" field.
func ActiveConfigRevisionIn(vs ...int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldActiveConfigRevision, vs...))
}

// ActiveConfigRevisionNotIn applies the NotIn predicate on the "active_config_revision" field.
func ActiveConfigRevisionNotIn(vs ...int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldActiveConfigRevision, vs...))
}

// ActiveConfigRevisionGT applies the GT predicate on the "active_config_revision" field.
func ActiveConfigRevisionGT(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldActiveConfigRevision, v))
}

// ActiveConfigRevisionGTE applies the GTE predicate on the "active_config_revision" field.
func ActiveConfigRevisionGTE(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldActiveConfigRevision, v))
}

// ActiveConfigRevisionLT applies the LT predicate on the "active_config_revision" field.
func ActiveConfigRevisionLT(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldActiveConfigRevision, v))
}

// ActiveConfigRevisionLTE applies the LTE predicate on the "active_config_revision" field.
func ActiveConfigRevisionLTE(v int64) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldActiveConfigRevision, v))
}

// ActiveConfigRevisionIsNil applies the IsNil predicate on the "active_config_revision" field.
func ActiveConfigRevisionIsNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldIsNull(FieldActiveConfigRevision))
}

// ActiveConfigRevisionNotNil applies the NotNil predicate on the "active_config_revision" field.
func ActiveConfigRevisionNotNil() predicate.Upstream {
	return predicate.Upstream(sql.FieldNotNull(FieldActiveConfigRevision))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Upstream {
	return predicate.Upstream(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Upstream {
	return predicate.Upstream(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Upstream) predicate.Upstream {
	return predicate.Upstream(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Upstream) predicate.Upstream {
	return predicate.Upstream(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Upstream) predicate.Upstream {
	return predicate.Upstream(sql.NotPredicates(p))
}
