// Code generated by ent, DO NOT EDIT.

package upstreamconfigrevision

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the upstreamconfigrevision type in the database.
	Label = "upstream_config_revision"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUpstreamID holds the string denoting the upstream_id field in the database.
	FieldUpstreamID = "upstream_id"
	// FieldRevision holds the string denoting the revision field in the database.
	FieldRevision = "revision"
	// FieldConfigJSON holds the string denoting the config_json field in the database.
	FieldConfigJSON = "config_json"
	// FieldCreatedByUserID holds the string denoting the created_by_user_id field in the database.
	FieldCreatedByUserID = "created_by_user_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the upstreamconfigrevision in the database.
	Table = "upstream_config_revisions"
)

// Columns holds all SQL columns for upstreamconfigrevision fields.
var Columns = []string{
	FieldID,
	FieldUpstreamID,
	FieldRevision,
	FieldConfigJSON,
	FieldCreatedByUserID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the UpstreamConfigRevision queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUpstreamID orders the results by the upstream_id field.
func ByUpstreamID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamID, opts...).ToFunc()
}

// ByRevision orders the results by the revision field.
func ByRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevision, opts...).ToFunc()
}

// ByCreatedByUserID orders the results by the created_by_user_id field.
func ByCreatedByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedByUserID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
