// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"measix/platform/ent/budgettemplateassignment"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BudgetTemplateAssignmentCreate is the builder for creating a BudgetTemplateAssignment entity.
type BudgetTemplateAssignmentCreate struct {
	config
	mutation *BudgetTemplateAssignmentMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *BudgetTemplateAssignmentCreate) SetUserID(v string) *BudgetTemplateAssignmentCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetBudgetTemplateID sets the "budget_template_id" field.
func (_c *BudgetTemplateAssignmentCreate) SetBudgetTemplateID(v string) *BudgetTemplateAssignmentCreate {
	_c.mutation.SetBudgetTemplateID(v)
	return _c
}

// SetRevision sets the "revision" field.
func (_c *BudgetTemplateAssignmentCreate) SetRevision(v int64) *BudgetTemplateAssignmentCreate {
	_c.mutation.SetRevision(v)
	return _c
}

// SetAssignedAt sets the "assigned_at" field.
func (_c *BudgetTemplateAssignmentCreate) SetAssignedAt(v time.Time) *BudgetTemplateAssignmentCreate {
	_c.mutation.SetAssignedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BudgetTemplateAssignmentCreate) SetUpdatedAt(v time.Time) *BudgetTemplateAssignmentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetUpdatedByUserID sets the "updated_by_user_id" field.
func (_c *BudgetTemplateAssignmentCreate) SetUpdatedByUserID(v string) *BudgetTemplateAssignmentCreate {
	_c.mutation.SetUpdatedByUserID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *BudgetTemplateAssignmentCreate) SetID(v int) *BudgetTemplateAssignmentCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the BudgetTemplateAssignmentMutation object of the builder.
func (_c *BudgetTemplateAssignmentCreate) Mutation() *BudgetTemplateAssignmentMutation {
	return _c.mutation
}

// Save creates the BudgetTemplateAssignment in the database.
func (_c *BudgetTemplateAssignmentCreate) Save(ctx context.Context) (*BudgetTemplateAssignment, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BudgetTemplateAssignmentCreate) SaveX(ctx context.Context) *BudgetTemplateAssignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BudgetTemplateAssignmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BudgetTemplateAssignmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BudgetTemplateAssignmentCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "BudgetTemplateAssignment.user_id"`)}
	}
	if _, ok := _c.mutation.BudgetTemplateID(); !ok {
		return &ValidationError{Name: "budget_template_id", err: errors.New(`ent: missing required field "BudgetTemplateAssignment.budget_template_id"`)}
	}
	if _, ok := _c.mutation.Revision(); !ok {
		return &ValidationError{Name: "revision", err: errors.New(`ent: missing required field "BudgetTemplateAssignment.revision"`)}
	}
	if v, ok := _c.mutation.Revision(); ok {
		if err := budgettemplateassignment.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "BudgetTemplateAssignment.revision": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AssignedAt(); !ok {
		return &ValidationError{Name: "assigned_at", err: errors.New(`ent: missing required field "BudgetTemplateAssignment.assigned_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BudgetTemplateAssignment.updated_at"`)}
	}
	if _, ok := _c.mutation.UpdatedByUserID(); !ok {
		return &ValidationError{Name: "updated_by_user_id", err: errors.New(`ent: missing required field "BudgetTemplateAssignment.updated_by_user_id"`)}
	}
	return nil
}

func (_c *BudgetTemplateAssignmentCreate) sqlSave(ctx context.Context) (*BudgetTemplateAssignment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BudgetTemplateAssignmentCreate) createSpec() (*BudgetTemplateAssignment, *sqlgraph.CreateSpec) {
	var (
		_node = &BudgetTemplateAssignment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(budgettemplateassignment.Table, sqlgraph.NewFieldSpec(budgettemplateassignment.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(budgettemplateassignment.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.BudgetTemplateID(); ok {
		_spec.SetField(budgettemplateassignment.FieldBudgetTemplateID, field.TypeString, value)
		_node.BudgetTemplateID = value
	}
	if value, ok := _c.mutation.Revision(); ok {
		_spec.SetField(budgettemplateassignment.FieldRevision, field.TypeInt64, value)
		_node.Revision = value
	}
	if value, ok := _c.mutation.AssignedAt(); ok {
		_spec.SetField(budgettemplateassignment.FieldAssignedAt, field.TypeTime, value)
		_node.AssignedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(budgettemplateassignment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UpdatedByUserID(); ok {
		_spec.SetField(budgettemplateassignment.FieldUpdatedByUserID, field.TypeString, value)
		_node.UpdatedByUserID = value
	}
	return _node, _spec
}

// BudgetTemplateAssignmentCreateBulk is the builder for creating many BudgetTemplateAssignment entities in bulk.
type BudgetTemplateAssignmentCreateBulk struct {
	config
	err      error
	builders []*BudgetTemplateAssignmentCreate
}

// Save creates the BudgetTemplateAssignment entities in the database.
func (_c *BudgetTemplateAssignmentCreateBulk) Save(ctx context.Context) ([]*BudgetTemplateAssignment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BudgetTemplateAssignment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BudgetTemplateAssignmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BudgetTemplateAssignmentCreateBulk) SaveX(ctx context.Context) []*BudgetTemplateAssignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BudgetTemplateAssignmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BudgetTemplateAssignmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
