// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"measix/platform/ent/budgetallocation"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BudgetAllocationCreate is the builder for creating a BudgetAllocation entity.
type BudgetAllocationCreate struct {
	config
	mutation *BudgetAllocationMutation
	hooks    []Hook
}

// SetRequestID sets the "request_id" field.
func (_c *BudgetAllocationCreate) SetRequestID(v string) *BudgetAllocationCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetBudgetLimitID sets the "budget_limit_id" field.
func (_c *BudgetAllocationCreate) SetBudgetLimitID(v int) *BudgetAllocationCreate {
	_c.mutation.SetBudgetLimitID(v)
	return _c
}

// SetBudgetBucketID sets the "budget_bucket_id" field.
func (_c *BudgetAllocationCreate) SetBudgetBucketID(v int) *BudgetAllocationCreate {
	_c.mutation.SetBudgetBucketID(v)
	return _c
}

// SetScopeKey sets the "scope_key" field.
func (_c *BudgetAllocationCreate) SetScopeKey(v string) *BudgetAllocationCreate {
	_c.mutation.SetScopeKey(v)
	return _c
}

// SetPeriod sets the "period" field.
func (_c *BudgetAllocationCreate) SetPeriod(v budgetallocation.Period) *BudgetAllocationCreate {
	_c.mutation.SetPeriod(v)
	return _c
}

// SetMeter sets the "meter" field.
func (_c *BudgetAllocationCreate) SetMeter(v budgetallocation.Meter) *BudgetAllocationCreate {
	_c.mutation.SetMeter(v)
	return _c
}

// SetReservedQuantity sets the "reserved_quantity" field.
func (_c *BudgetAllocationCreate) SetReservedQuantity(v int64) *BudgetAllocationCreate {
	_c.mutation.SetReservedQuantity(v)
	return _c
}

// SetNillableReservedQuantity sets the "reserved_quantity" field if the given value is not nil.
func (_c *BudgetAllocationCreate) SetNillableReservedQuantity(v *int64) *BudgetAllocationCreate {
	if v != nil {
		_c.SetReservedQuantity(*v)
	}
	return _c
}

// SetReservationReleased sets the "reservation_released" field.
func (_c *BudgetAllocationCreate) SetReservationReleased(v bool) *BudgetAllocationCreate {
	_c.mutation.SetReservationReleased(v)
	return _c
}

// SetNillableReservationReleased sets the "reservation_released" field if the given value is not nil.
func (_c *BudgetAllocationCreate) SetNillableReservationReleased(v *bool) *BudgetAllocationCreate {
	if v != nil {
		_c.SetReservationReleased(*v)
	}
	return _c
}

// SetSettledQuantity sets the "settled_quantity" field.
func (_c *BudgetAllocationCreate) SetSettledQuantity(v int64) *BudgetAllocationCreate {
	_c.mutation.SetSettledQuantity(v)
	return _c
}

// SetNillableSettledQuantity sets the "settled_quantity" field if the given value is not nil.
func (_c *BudgetAllocationCreate) SetNillableSettledQuantity(v *int64) *BudgetAllocationCreate {
	if v != nil {
		_c.SetSettledQuantity(*v)
	}
	return _c
}

// SetResolved sets the "resolved" field.
func (_c *BudgetAllocationCreate) SetResolved(v bool) *BudgetAllocationCreate {
	_c.mutation.SetResolved(v)
	return _c
}

// SetNillableResolved sets the "resolved" field if the given value is not nil.
func (_c *BudgetAllocationCreate) SetNillableResolved(v *bool) *BudgetAllocationCreate {
	if v != nil {
		_c.SetResolved(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BudgetAllocationCreate) SetCreatedAt(v time.Time) *BudgetAllocationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BudgetAllocationCreate) SetUpdatedAt(v time.Time) *BudgetAllocationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *BudgetAllocationCreate) SetID(v int) *BudgetAllocationCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the BudgetAllocationMutation object of the builder.
func (_c *BudgetAllocationCreate) Mutation() *BudgetAllocationMutation {
	return _c.mutation
}

// Save creates the BudgetAllocation in the database.
func (_c *BudgetAllocationCreate) Save(ctx context.Context) (*BudgetAllocation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BudgetAllocationCreate) SaveX(ctx context.Context) *BudgetAllocation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BudgetAllocationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BudgetAllocationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BudgetAllocationCreate) defaults() {
	if _, ok := _c.mutation.ReservedQuantity(); !ok {
		v := budgetallocation.DefaultReservedQuantity
		_c.mutation.SetReservedQuantity(v)
	}
	if _, ok := _c.mutation.ReservationReleased(); !ok {
		v := budgetallocation.DefaultReservationReleased
		_c.mutation.SetReservationReleased(v)
	}
	if _, ok := _c.mutation.SettledQuantity(); !ok {
		v := budgetallocation.DefaultSettledQuantity
		_c.mutation.SetSettledQuantity(v)
	}
	if _, ok := _c.mutation.Resolved(); !ok {
		v := budgetallocation.DefaultResolved
		_c.mutation.SetResolved(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BudgetAllocationCreate) check() error {
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "BudgetAllocation.request_id"`)}
	}
	if _, ok := _c.mutation.BudgetLimitID(); !ok {
		return &ValidationError{Name: "budget_limit_id", err: errors.New(`ent: missing required field "BudgetAllocation.budget_limit_id"`)}
	}
	if _, ok := _c.mutation.BudgetBucketID(); !ok {
		return &ValidationError{Name: "budget_bucket_id", err: errors.New(`ent: missing required field "BudgetAllocation.budget_bucket_id"`)}
	}
	if _, ok := _c.mutation.ScopeKey(); !ok {
		return &ValidationError{Name: "scope_key", err: errors.New(`ent: missing required field "BudgetAllocation.scope_key"`)}
	}
	if _, ok := _c.mutation.Period(); !ok {
		return &ValidationError{Name: "period", err: errors.New(`ent: missing required field "BudgetAllocation.period"`)}
	}
	if v, ok := _c.mutation.Period(); ok {
		if err := budgetallocation.PeriodValidator(v); err != nil {
			return &ValidationError{Name: "period", err: fmt.Errorf(`ent: validator failed for field "BudgetAllocation.period": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Meter(); !ok {
		return &ValidationError{Name: "meter", err: errors.New(`ent: missing required field "BudgetAllocation.meter"`)}
	}
	if v, ok := _c.mutation.Meter(); ok {
		if err := budgetallocation.MeterValidator(v); err != nil {
			return &ValidationError{Name: "meter", err: fmt.Errorf(`ent: validator failed for field "BudgetAllocation.meter": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReservedQuantity(); !ok {
		return &ValidationError{Name: "reserved_quantity", err: errors.New(`ent: missing required field "BudgetAllocation.reserved_quantity"`)}
	}
	if v, ok := _c.mutation.ReservedQuantity(); ok {
		if err := budgetallocation.ReservedQuantityValidator(v); err != nil {
			return &ValidationError{Name: "reserved_quantity", err: fmt.Errorf(`ent: validator failed for field "BudgetAllocation.reserved_quantity": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReservationReleased(); !ok {
		return &ValidationError{Name: "reservation_released", err: errors.New(`ent: missing required field "BudgetAllocation.reservation_released"`)}
	}
	if _, ok := _c.mutation.SettledQuantity(); !ok {
		return &ValidationError{Name: "settled_quantity", err: errors.New(`ent: missing required field "BudgetAllocation.settled_quantity"`)}
	}
	if v, ok := _c.mutation.SettledQuantity(); ok {
		if err := budgetallocation.SettledQuantityValidator(v); err != nil {
			return &ValidationError{Name: "settled_quantity", err: fmt.Errorf(`ent: validator failed for field "BudgetAllocation.settled_quantity": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Resolved(); !ok {
		return &ValidationError{Name: "resolved", err: errors.New(`ent: missing required field "BudgetAllocation.resolved"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BudgetAllocation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BudgetAllocation.updated_at"`)}
	}
	return nil
}

func (_c *BudgetAllocationCreate) sqlSave(ctx context.Context) (*BudgetAllocation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BudgetAllocationCreate) createSpec() (*BudgetAllocation, *sqlgraph.CreateSpec) {
	var (
		_node = &BudgetAllocation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(budgetallocation.Table, sqlgraph.NewFieldSpec(budgetallocation.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(budgetallocation.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.BudgetLimitID(); ok {
		_spec.SetField(budgetallocation.FieldBudgetLimitID, field.TypeInt, value)
		_node.BudgetLimitID = value
	}
	if value, ok := _c.mutation.BudgetBucketID(); ok {
		_spec.SetField(budgetallocation.FieldBudgetBucketID, field.TypeInt, value)
		_node.BudgetBucketID = value
	}
	if value, ok := _c.mutation.ScopeKey(); ok {
		_spec.SetField(budgetallocation.FieldScopeKey, field.TypeString, value)
		_node.ScopeKey = value
	}
	if value, ok := _c.mutation.Period(); ok {
		_spec.SetField(budgetallocation.FieldPeriod, field.TypeEnum, value)
		_node.Period = value
	}
	if value, ok := _c.mutation.Meter(); ok {
		_spec.SetField(budgetallocation.FieldMeter, field.TypeEnum, value)
		_node.Meter = value
	}
	if value, ok := _c.mutation.ReservedQuantity(); ok {
		_spec.SetField(budgetallocation.FieldReservedQuantity, field.TypeInt64, value)
		_node.ReservedQuantity = value
	}
	if value, ok := _c.mutation.ReservationReleased(); ok {
		_spec.SetField(budgetallocation.FieldReservationReleased, field.TypeBool, value)
		_node.ReservationReleased = value
	}
	if value, ok := _c.mutation.SettledQuantity(); ok {
		_spec.SetField(budgetallocation.FieldSettledQuantity, field.TypeInt64, value)
		_node.SettledQuantity = value
	}
	if value, ok := _c.mutation.Resolved(); ok {
		_spec.SetField(budgetallocation.FieldResolved, field.TypeBool, value)
		_node.Resolved = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(budgetallocation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(budgetallocation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// BudgetAllocationCreateBulk is the builder for creating many BudgetAllocation entities in bulk.
type BudgetAllocationCreateBulk struct {
	config
	err      error
	builders []*BudgetAllocationCreate
}

// Save creates the BudgetAllocation entities in the database.
func (_c *BudgetAllocationCreateBulk) Save(ctx context.Context) ([]*BudgetAllocation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BudgetAllocation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BudgetAllocationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BudgetAllocationCreateBulk) SaveX(ctx context.Context) []*BudgetAllocation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BudgetAllocationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BudgetAllocationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
