// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"measix/platform/ent/budgetreconciliation"
	"measix/platform/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BudgetReconciliationUpdate is the builder for updating BudgetReconciliation entities.
type BudgetReconciliationUpdate struct {
	config
	hooks    []Hook
	mutation *BudgetReconciliationMutation
}

// Where appends a list predicates to the BudgetReconciliationUpdate builder.
func (_u *BudgetReconciliationUpdate) Where(ps ...predicate.BudgetReconciliation) *BudgetReconciliationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetState sets the "state" field.
func (_u *BudgetReconciliationUpdate) SetState(v budgetreconciliation.State) *BudgetReconciliationUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *BudgetReconciliationUpdate) SetNillableState(v *budgetreconciliation.State) *BudgetReconciliationUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetResolvedAt sets the "resolved_at" field.
func (_u *BudgetReconciliationUpdate) SetResolvedAt(v time.Time) *BudgetReconciliationUpdate {
	_u.mutation.SetResolvedAt(v)
	return _u
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_u *BudgetReconciliationUpdate) SetNillableResolvedAt(v *time.Time) *BudgetReconciliationUpdate {
	if v != nil {
		_u.SetResolvedAt(*v)
	}
	return _u
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (_u *BudgetReconciliationUpdate) ClearResolvedAt() *BudgetReconciliationUpdate {
	_u.mutation.ClearResolvedAt()
	return _u
}

// SetResolvedByActor sets the "resolved_by_actor" field.
func (_u *BudgetReconciliationUpdate) SetResolvedByActor(v string) *BudgetReconciliationUpdate {
	_u.mutation.SetResolvedByActor(v)
	return _u
}

// SetNillableResolvedByActor sets the "resolved_by_actor" field if the given value is not nil.
func (_u *BudgetReconciliationUpdate) SetNillableResolvedByActor(v *string) *BudgetReconciliationUpdate {
	if v != nil {
		_u.SetResolvedByActor(*v)
	}
	return _u
}

// ClearResolvedByActor clears the value of the "resolved_by_actor" field.
func (_u *BudgetReconciliationUpdate) ClearResolvedByActor() *BudgetReconciliationUpdate {
	_u.mutation.ClearResolvedByActor()
	return _u
}

// SetResolutionAction sets the "resolution_action" field.
func (_u *BudgetReconciliationUpdate) SetResolutionAction(v budgetreconciliation.ResolutionAction) *BudgetReconciliationUpdate {
	_u.mutation.SetResolutionAction(v)
	return _u
}

// SetNillableResolutionAction sets the "resolution_action" field if the given value is not nil.
func (_u *BudgetReconciliationUpdate) SetNillableResolutionAction(v *budgetreconciliation.ResolutionAction) *BudgetReconciliationUpdate {
	if v != nil {
		_u.SetResolutionAction(*v)
	}
	return _u
}

// ClearResolutionAction clears the value of the "resolution_action" field.
func (_u *BudgetReconciliationUpdate) ClearResolutionAction() *BudgetReconciliationUpdate {
	_u.mutation.ClearResolutionAction()
	return _u
}

// SetResolutionReason sets the "resolution_reason" field.
func (_u *BudgetReconciliationUpdate) SetResolutionReason(v string) *BudgetReconciliationUpdate {
	_u.mutation.SetResolutionReason(v)
	return _u
}

// SetNillableResolutionReason sets the "resolution_reason" field if the given value is not nil.
func (_u *BudgetReconciliationUpdate) SetNillableResolutionReason(v *string) *BudgetReconciliationUpdate {
	if v != nil {
		_u.SetResolutionReason(*v)
	}
	return _u
}

// ClearResolutionReason clears the value of the "resolution_reason" field.
func (_u *BudgetReconciliationUpdate) ClearResolutionReason() *BudgetReconciliationUpdate {
	_u.mutation.ClearResolutionReason()
	return _u
}

// Mutation returns the BudgetReconciliationMutation object of the builder.
func (_u *BudgetReconciliationUpdate) Mutation() *BudgetReconciliationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BudgetReconciliationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BudgetReconciliationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BudgetReconciliationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BudgetReconciliationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BudgetReconciliationUpdate) check() error {
	if v, ok := _u.mutation.State(); ok {
		if err := budgetreconciliation.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "BudgetReconciliation.state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResolutionAction(); ok {
		if err := budgetreconciliation.ResolutionActionValidator(v); err != nil {
			return &ValidationError{Name: "resolution_action", err: fmt.Errorf(`ent: validator failed for field "BudgetReconciliation.resolution_action": %w`, err)}
		}
	}
	if _u.mutation.RequestCleared() && len(_u.mutation.RequestIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BudgetReconciliation.request"`)
	}
	return nil
}

func (_u *BudgetReconciliationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(budgetreconciliation.Table, budgetreconciliation.Columns, sqlgraph.NewFieldSpec(budgetreconciliation.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(budgetreconciliation.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ResolvedAt(); ok {
		_spec.SetField(budgetreconciliation.FieldResolvedAt, field.TypeTime, value)
	}
	if _u.mutation.ResolvedAtCleared() {
		_spec.ClearField(budgetreconciliation.FieldResolvedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ResolvedByActor(); ok {
		_spec.SetField(budgetreconciliation.FieldResolvedByActor, field.TypeString, value)
	}
	if _u.mutation.ResolvedByActorCleared() {
		_spec.ClearField(budgetreconciliation.FieldResolvedByActor, field.TypeString)
	}
	if value, ok := _u.mutation.ResolutionAction(); ok {
		_spec.SetField(budgetreconciliation.FieldResolutionAction, field.TypeEnum, value)
	}
	if _u.mutation.ResolutionActionCleared() {
		_spec.ClearField(budgetreconciliation.FieldResolutionAction, field.TypeEnum)
	}
	if value, ok := _u.mutation.ResolutionReason(); ok {
		_spec.SetField(budgetreconciliation.FieldResolutionReason, field.TypeString, value)
	}
	if _u.mutation.ResolutionReasonCleared() {
		_spec.ClearField(budgetreconciliation.FieldResolutionReason, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{budgetreconciliation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BudgetReconciliationUpdateOne is the builder for updating a single BudgetReconciliation entity.
type BudgetReconciliationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BudgetReconciliationMutation
}

// SetState sets the "state" field.
func (_u *BudgetReconciliationUpdateOne) SetState(v budgetreconciliation.State) *BudgetReconciliationUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *BudgetReconciliationUpdateOne) SetNillableState(v *budgetreconciliation.State) *BudgetReconciliationUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetResolvedAt sets the "resolved_at" field.
func (_u *BudgetReconciliationUpdateOne) SetResolvedAt(v time.Time) *BudgetReconciliationUpdateOne {
	_u.mutation.SetResolvedAt(v)
	return _u
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_u *BudgetReconciliationUpdateOne) SetNillableResolvedAt(v *time.Time) *BudgetReconciliationUpdateOne {
	if v != nil {
		_u.SetResolvedAt(*v)
	}
	return _u
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (_u *BudgetReconciliationUpdateOne) ClearResolvedAt() *BudgetReconciliationUpdateOne {
	_u.mutation.ClearResolvedAt()
	return _u
}

// SetResolvedByActor sets the "resolved_by_actor" field.
func (_u *BudgetReconciliationUpdateOne) SetResolvedByActor(v string) *BudgetReconciliationUpdateOne {
	_u.mutation.SetResolvedByActor(v)
	return _u
}

// SetNillableResolvedByActor sets the "resolved_by_actor" field if the given value is not nil.
func (_u *BudgetReconciliationUpdateOne) SetNillableResolvedByActor(v *string) *BudgetReconciliationUpdateOne {
	if v != nil {
		_u.SetResolvedByActor(*v)
	}
	return _u
}

// ClearResolvedByActor clears the value of the "resolved_by_actor" field.
func (_u *BudgetReconciliationUpdateOne) ClearResolvedByActor() *BudgetReconciliationUpdateOne {
	_u.mutation.ClearResolvedByActor()
	return _u
}

// SetResolutionAction sets the "resolution_action" field.
func (_u *BudgetReconciliationUpdateOne) SetResolutionAction(v budgetreconciliation.ResolutionAction) *BudgetReconciliationUpdateOne {
	_u.mutation.SetResolutionAction(v)
	return _u
}

// SetNillableResolutionAction sets the "resolution_action" field if the given value is not nil.
func (_u *BudgetReconciliationUpdateOne) SetNillableResolutionAction(v *budgetreconciliation.ResolutionAction) *BudgetReconciliationUpdateOne {
	if v != nil {
		_u.SetResolutionAction(*v)
	}
	return _u
}

// ClearResolutionAction clears the value of the "resolution_action" field.
func (_u *BudgetReconciliationUpdateOne) ClearResolutionAction() *BudgetReconciliationUpdateOne {
	_u.mutation.ClearResolutionAction()
	return _u
}

// SetResolutionReason sets the "resolution_reason" field.
func (_u *BudgetReconciliationUpdateOne) SetResolutionReason(v string) *BudgetReconciliationUpdateOne {
	_u.mutation.SetResolutionReason(v)
	return _u
}

// SetNillableResolutionReason sets the "resolution_reason" field if the given value is not nil.
func (_u *BudgetReconciliationUpdateOne) SetNillableResolutionReason(v *string) *BudgetReconciliationUpdateOne {
	if v != nil {
		_u.SetResolutionReason(*v)
	}
	return _u
}

// ClearResolutionReason clears the value of the "resolution_reason" field.
func (_u *BudgetReconciliationUpdateOne) ClearResolutionReason() *BudgetReconciliationUpdateOne {
	_u.mutation.ClearResolutionReason()
	return _u
}

// Mutation returns the BudgetReconciliationMutation object of the builder.
func (_u *BudgetReconciliationUpdateOne) Mutation() *BudgetReconciliationMutation {
	return _u.mutation
}

// Where appends a list predicates to the BudgetReconciliationUpdate builder.
func (_u *BudgetReconciliationUpdateOne) Where(ps ...predicate.BudgetReconciliation) *BudgetReconciliationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BudgetReconciliationUpdateOne) Select(field string, fields ...string) *BudgetReconciliationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BudgetReconciliation entity.
func (_u *BudgetReconciliationUpdateOne) Save(ctx context.Context) (*BudgetReconciliation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BudgetReconciliationUpdateOne) SaveX(ctx context.Context) *BudgetReconciliation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BudgetReconciliationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BudgetReconciliationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BudgetReconciliationUpdateOne) check() error {
	if v, ok := _u.mutation.State(); ok {
		if err := budgetreconciliation.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "BudgetReconciliation.state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResolutionAction(); ok {
		if err := budgetreconciliation.ResolutionActionValidator(v); err != nil {
			return &ValidationError{Name: "resolution_action", err: fmt.Errorf(`ent: validator failed for field "BudgetReconciliation.resolution_action": %w`, err)}
		}
	}
	if _u.mutation.RequestCleared() && len(_u.mutation.RequestIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BudgetReconciliation.request"`)
	}
	return nil
}

func (_u *BudgetReconciliationUpdateOne) sqlSave(ctx context.Context) (_node *BudgetReconciliation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(budgetreconciliation.Table, budgetreconciliation.Columns, sqlgraph.NewFieldSpec(budgetreconciliation.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BudgetReconciliation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, budgetreconciliation.FieldID)
		for _, f := range fields {
			if !budgetreconciliation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != budgetreconciliation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(budgetreconciliation.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ResolvedAt(); ok {
		_spec.SetField(budgetreconciliation.FieldResolvedAt, field.TypeTime, value)
	}
	if _u.mutation.ResolvedAtCleared() {
		_spec.ClearField(budgetreconciliation.FieldResolvedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ResolvedByActor(); ok {
		_spec.SetField(budgetreconciliation.FieldResolvedByActor, field.TypeString, value)
	}
	if _u.mutation.ResolvedByActorCleared() {
		_spec.ClearField(budgetreconciliation.FieldResolvedByActor, field.TypeString)
	}
	if value, ok := _u.mutation.ResolutionAction(); ok {
		_spec.SetField(budgetreconciliation.FieldResolutionAction, field.TypeEnum, value)
	}
	if _u.mutation.ResolutionActionCleared() {
		_spec.ClearField(budgetreconciliation.FieldResolutionAction, field.TypeEnum)
	}
	if value, ok := _u.mutation.ResolutionReason(); ok {
		_spec.SetField(budgetreconciliation.FieldResolutionReason, field.TypeString, value)
	}
	if _u.mutation.ResolutionReasonCleared() {
		_spec.ClearField(budgetreconciliation.FieldResolutionReason, field.TypeString)
	}
	_node = &BudgetReconciliation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{budgetreconciliation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
