// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"measix/platform/ent/budgettemplateaudit"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// BudgetTemplateAudit is the model entity for the BudgetTemplateAudit schema.
type BudgetTemplateAudit struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// BudgetTemplateID holds the value of the "budget_template_id" field.
	BudgetTemplateID *string `json:"budget_template_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID *string `json:"user_id,omitempty"`
	// TemplateRevision holds the value of the "template_revision" field.
	TemplateRevision int64 `json:"template_revision,omitempty"`
	// AssignmentRevision holds the value of the "assignment_revision" field.
	AssignmentRevision int64 `json:"assignment_revision,omitempty"`
	// ActorUserID holds the value of the "actor_user_id" field.
	ActorUserID string `json:"actor_user_id,omitempty"`
	// Action holds the value of the "action" field.
	Action budgettemplateaudit.Action `json:"action,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// BeforeJSON holds the value of the "before_json" field.
	BeforeJSON *[]byte `json:"before_json,omitempty"`
	// AfterJSON holds the value of the "after_json" field.
	AfterJSON *[]byte `json:"after_json,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BudgetTemplateAudit) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case budgettemplateaudit.FieldBeforeJSON, budgettemplateaudit.FieldAfterJSON:
			values[i] = new([]byte)
		case budgettemplateaudit.FieldID, budgettemplateaudit.FieldTemplateRevision, budgettemplateaudit.FieldAssignmentRevision:
			values[i] = new(sql.NullInt64)
		case budgettemplateaudit.FieldBudgetTemplateID, budgettemplateaudit.FieldUserID, budgettemplateaudit.FieldActorUserID, budgettemplateaudit.FieldAction, budgettemplateaudit.FieldReason:
			values[i] = new(sql.NullString)
		case budgettemplateaudit.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BudgetTemplateAudit fields.
func (_m *BudgetTemplateAudit) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case budgettemplateaudit.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case budgettemplateaudit.FieldBudgetTemplateID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field budget_template_id", values[i])
			} else if value.Valid {
				_m.BudgetTemplateID = new(string)
				*_m.BudgetTemplateID = value.String
			}
		case budgettemplateaudit.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(string)
				*_m.UserID = value.String
			}
		case budgettemplateaudit.FieldTemplateRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field template_revision", values[i])
			} else if value.Valid {
				_m.TemplateRevision = value.Int64
			}
		case budgettemplateaudit.FieldAssignmentRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field assignment_revision", values[i])
			} else if value.Valid {
				_m.AssignmentRevision = value.Int64
			}
		case budgettemplateaudit.FieldActorUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor_user_id", values[i])
			} else if value.Valid {
				_m.ActorUserID = value.String
			}
		case budgettemplateaudit.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = budgettemplateaudit.Action(value.String)
			}
		case budgettemplateaudit.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case budgettemplateaudit.FieldBeforeJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field before_json", values[i])
			} else if value != nil {
				_m.BeforeJSON = value
			}
		case budgettemplateaudit.FieldAfterJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field after_json", values[i])
			} else if value != nil {
				_m.AfterJSON = value
			}
		case budgettemplateaudit.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BudgetTemplateAudit.
// This includes values selected through modifiers, order, etc.
func (_m *BudgetTemplateAudit) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this BudgetTemplateAudit.
// Note that you need to call BudgetTemplateAudit.Unwrap() before calling this method if this BudgetTemplateAudit
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BudgetTemplateAudit) Update() *BudgetTemplateAuditUpdateOne {
	return NewBudgetTemplateAuditClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BudgetTemplateAudit entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BudgetTemplateAudit) Unwrap() *BudgetTemplateAudit {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BudgetTemplateAudit is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BudgetTemplateAudit) String() string {
	var builder strings.Builder
	builder.WriteString("BudgetTemplateAudit(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.BudgetTemplateID; v != nil {
		builder.WriteString("budget_template_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("template_revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.TemplateRevision))
	builder.WriteString(", ")
	builder.WriteString("assignment_revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.AssignmentRevision))
	builder.WriteString(", ")
	builder.WriteString("actor_user_id=")
	builder.WriteString(_m.ActorUserID)
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(fmt.Sprintf("%v", _m.Action))
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	if v := _m.BeforeJSON; v != nil {
		builder.WriteString("before_json=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AfterJSON; v != nil {
		builder.WriteString("after_json=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BudgetTemplateAudits is a parsable slice of BudgetTemplateAudit.
type BudgetTemplateAudits []*BudgetTemplateAudit
