// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"measix/platform/ent/budgetrequest"
	"measix/platform/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BudgetRequestDelete is the builder for deleting a BudgetRequest entity.
type BudgetRequestDelete struct {
	config
	hooks    []Hook
	mutation *BudgetRequestMutation
}

// Where appends a list predicates to the BudgetRequestDelete builder.
func (_d *BudgetRequestDelete) Where(ps ...predicate.BudgetRequest) *BudgetRequestDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BudgetRequestDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BudgetRequestDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BudgetRequestDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(budgetrequest.Table, sqlgraph.NewFieldSpec(budgetrequest.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BudgetRequestDeleteOne is the builder for deleting a single BudgetRequest entity.
type BudgetRequestDeleteOne struct {
	_d *BudgetRequestDelete
}

// Where appends a list predicates to the BudgetRequestDelete builder.
func (_d *BudgetRequestDeleteOne) Where(ps ...predicate.BudgetRequest) *BudgetRequestDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BudgetRequestDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{budgetrequest.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BudgetRequestDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
