// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"measix/platform/ent/budgetbucket"
	"measix/platform/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BudgetBucketUpdate is the builder for updating BudgetBucket entities.
type BudgetBucketUpdate struct {
	config
	hooks    []Hook
	mutation *BudgetBucketMutation
}

// Where appends a list predicates to the BudgetBucketUpdate builder.
func (_u *BudgetBucketUpdate) Where(ps ...predicate.BudgetBucket) *BudgetBucketUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetScopeKey sets the "scope_key" field.
func (_u *BudgetBucketUpdate) SetScopeKey(v string) *BudgetBucketUpdate {
	_u.mutation.SetScopeKey(v)
	return _u
}

// SetNillableScopeKey sets the "scope_key" field if the given value is not nil.
func (_u *BudgetBucketUpdate) SetNillableScopeKey(v *string) *BudgetBucketUpdate {
	if v != nil {
		_u.SetScopeKey(*v)
	}
	return _u
}

// SetPeriod sets the "period" field.
func (_u *BudgetBucketUpdate) SetPeriod(v budgetbucket.Period) *BudgetBucketUpdate {
	_u.mutation.SetPeriod(v)
	return _u
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (_u *BudgetBucketUpdate) SetNillablePeriod(v *budgetbucket.Period) *BudgetBucketUpdate {
	if v != nil {
		_u.SetPeriod(*v)
	}
	return _u
}

// SetPeriodStart sets the "period_start" field.
func (_u *BudgetBucketUpdate) SetPeriodStart(v time.Time) *BudgetBucketUpdate {
	_u.mutation.SetPeriodStart(v)
	return _u
}

// SetNillablePeriodStart sets the "period_start" field if the given value is not nil.
func (_u *BudgetBucketUpdate) SetNillablePeriodStart(v *time.Time) *BudgetBucketUpdate {
	if v != nil {
		_u.SetPeriodStart(*v)
	}
	return _u
}

// SetPeriodEnd sets the "period_end" field.
func (_u *BudgetBucketUpdate) SetPeriodEnd(v time.Time) *BudgetBucketUpdate {
	_u.mutation.SetPeriodEnd(v)
	return _u
}

// SetNillablePeriodEnd sets the "period_end" field if the given value is not nil.
func (_u *BudgetBucketUpdate) SetNillablePeriodEnd(v *time.Time) *BudgetBucketUpdate {
	if v != nil {
		_u.SetPeriodEnd(*v)
	}
	return _u
}

// ClearPeriodEnd clears the value of the "period_end" field.
func (_u *BudgetBucketUpdate) ClearPeriodEnd() *BudgetBucketUpdate {
	_u.mutation.ClearPeriodEnd()
	return _u
}

// SetMeter sets the "meter" field.
func (_u *BudgetBucketUpdate) SetMeter(v budgetbucket.Meter) *BudgetBucketUpdate {
	_u.mutation.SetMeter(v)
	return _u
}

// SetNillableMeter sets the "meter" field if the given value is not nil.
func (_u *BudgetBucketUpdate) SetNillableMeter(v *budgetbucket.Meter) *BudgetBucketUpdate {
	if v != nil {
		_u.SetMeter(*v)
	}
	return _u
}

// SetSettledQuantity sets the "settled_quantity" field.
func (_u *BudgetBucketUpdate) SetSettledQuantity(v int64) *BudgetBucketUpdate {
	_u.mutation.ResetSettledQuantity()
	_u.mutation.SetSettledQuantity(v)
	return _u
}

// SetNillableSettledQuantity sets the "settled_quantity" field if the given value is not nil.
func (_u *BudgetBucketUpdate) SetNillableSettledQuantity(v *int64) *BudgetBucketUpdate {
	if v != nil {
		_u.SetSettledQuantity(*v)
	}
	return _u
}

// AddSettledQuantity adds value to the "settled_quantity" field.
func (_u *BudgetBucketUpdate) AddSettledQuantity(v int64) *BudgetBucketUpdate {
	_u.mutation.AddSettledQuantity(v)
	return _u
}

// SetReservedQuantity sets the "reserved_quantity" field.
func (_u *BudgetBucketUpdate) SetReservedQuantity(v int64) *BudgetBucketUpdate {
	_u.mutation.ResetReservedQuantity()
	_u.mutation.SetReservedQuantity(v)
	return _u
}

// SetNillableReservedQuantity sets the "reserved_quantity" field if the given value is not nil.
func (_u *BudgetBucketUpdate) SetNillableReservedQuantity(v *int64) *BudgetBucketUpdate {
	if v != nil {
		_u.SetReservedQuantity(*v)
	}
	return _u
}

// AddReservedQuantity adds value to the "reserved_quantity" field.
func (_u *BudgetBucketUpdate) AddReservedQuantity(v int64) *BudgetBucketUpdate {
	_u.mutation.AddReservedQuantity(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BudgetBucketUpdate) SetUpdatedAt(v time.Time) *BudgetBucketUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *BudgetBucketUpdate) SetNillableUpdatedAt(v *time.Time) *BudgetBucketUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the BudgetBucketMutation object of the builder.
func (_u *BudgetBucketUpdate) Mutation() *BudgetBucketMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BudgetBucketUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BudgetBucketUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BudgetBucketUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BudgetBucketUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BudgetBucketUpdate) check() error {
	if v, ok := _u.mutation.Period(); ok {
		if err := budgetbucket.PeriodValidator(v); err != nil {
			return &ValidationError{Name: "period", err: fmt.Errorf(`ent: validator failed for field "BudgetBucket.period": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Meter(); ok {
		if err := budgetbucket.MeterValidator(v); err != nil {
			return &ValidationError{Name: "meter", err: fmt.Errorf(`ent: validator failed for field "BudgetBucket.meter": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SettledQuantity(); ok {
		if err := budgetbucket.SettledQuantityValidator(v); err != nil {
			return &ValidationError{Name: "settled_quantity", err: fmt.Errorf(`ent: validator failed for field "BudgetBucket.settled_quantity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReservedQuantity(); ok {
		if err := budgetbucket.ReservedQuantityValidator(v); err != nil {
			return &ValidationError{Name: "reserved_quantity", err: fmt.Errorf(`ent: validator failed for field "BudgetBucket.reserved_quantity": %w`, err)}
		}
	}
	return nil
}

func (_u *BudgetBucketUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(budgetbucket.Table, budgetbucket.Columns, sqlgraph.NewFieldSpec(budgetbucket.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ScopeKey(); ok {
		_spec.SetField(budgetbucket.FieldScopeKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Period(); ok {
		_spec.SetField(budgetbucket.FieldPeriod, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PeriodStart(); ok {
		_spec.SetField(budgetbucket.FieldPeriodStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PeriodEnd(); ok {
		_spec.SetField(budgetbucket.FieldPeriodEnd, field.TypeTime, value)
	}
	if _u.mutation.PeriodEndCleared() {
		_spec.ClearField(budgetbucket.FieldPeriodEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.Meter(); ok {
		_spec.SetField(budgetbucket.FieldMeter, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SettledQuantity(); ok {
		_spec.SetField(budgetbucket.FieldSettledQuantity, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSettledQuantity(); ok {
		_spec.AddField(budgetbucket.FieldSettledQuantity, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ReservedQuantity(); ok {
		_spec.SetField(budgetbucket.FieldReservedQuantity, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReservedQuantity(); ok {
		_spec.AddField(budgetbucket.FieldReservedQuantity, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(budgetbucket.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{budgetbucket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BudgetBucketUpdateOne is the builder for updating a single BudgetBucket entity.
type BudgetBucketUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BudgetBucketMutation
}

// SetScopeKey sets the "scope_key" field.
func (_u *BudgetBucketUpdateOne) SetScopeKey(v string) *BudgetBucketUpdateOne {
	_u.mutation.SetScopeKey(v)
	return _u
}

// SetNillableScopeKey sets the "scope_key" field if the given value is not nil.
func (_u *BudgetBucketUpdateOne) SetNillableScopeKey(v *string) *BudgetBucketUpdateOne {
	if v != nil {
		_u.SetScopeKey(*v)
	}
	return _u
}

// SetPeriod sets the "period" field.
func (_u *BudgetBucketUpdateOne) SetPeriod(v budgetbucket.Period) *BudgetBucketUpdateOne {
	_u.mutation.SetPeriod(v)
	return _u
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (_u *BudgetBucketUpdateOne) SetNillablePeriod(v *budgetbucket.Period) *BudgetBucketUpdateOne {
	if v != nil {
		_u.SetPeriod(*v)
	}
	return _u
}

// SetPeriodStart sets the "period_start" field.
func (_u *BudgetBucketUpdateOne) SetPeriodStart(v time.Time) *BudgetBucketUpdateOne {
	_u.mutation.SetPeriodStart(v)
	return _u
}

// SetNillablePeriodStart sets the "period_start" field if the given value is not nil.
func (_u *BudgetBucketUpdateOne) SetNillablePeriodStart(v *time.Time) *BudgetBucketUpdateOne {
	if v != nil {
		_u.SetPeriodStart(*v)
	}
	return _u
}

// SetPeriodEnd sets the "period_end" field.
func (_u *BudgetBucketUpdateOne) SetPeriodEnd(v time.Time) *BudgetBucketUpdateOne {
	_u.mutation.SetPeriodEnd(v)
	return _u
}

// SetNillablePeriodEnd sets the "period_end" field if the given value is not nil.
func (_u *BudgetBucketUpdateOne) SetNillablePeriodEnd(v *time.Time) *BudgetBucketUpdateOne {
	if v != nil {
		_u.SetPeriodEnd(*v)
	}
	return _u
}

// ClearPeriodEnd clears the value of the "period_end" field.
func (_u *BudgetBucketUpdateOne) ClearPeriodEnd() *BudgetBucketUpdateOne {
	_u.mutation.ClearPeriodEnd()
	return _u
}

// SetMeter sets the "meter" field.
func (_u *BudgetBucketUpdateOne) SetMeter(v budgetbucket.Meter) *BudgetBucketUpdateOne {
	_u.mutation.SetMeter(v)
	return _u
}

// SetNillableMeter sets the "meter" field if the given value is not nil.
func (_u *BudgetBucketUpdateOne) SetNillableMeter(v *budgetbucket.Meter) *BudgetBucketUpdateOne {
	if v != nil {
		_u.SetMeter(*v)
	}
	return _u
}

// SetSettledQuantity sets the "settled_quantity" field.
func (_u *BudgetBucketUpdateOne) SetSettledQuantity(v int64) *BudgetBucketUpdateOne {
	_u.mutation.ResetSettledQuantity()
	_u.mutation.SetSettledQuantity(v)
	return _u
}

// SetNillableSettledQuantity sets the "settled_quantity" field if the given value is not nil.
func (_u *BudgetBucketUpdateOne) SetNillableSettledQuantity(v *int64) *BudgetBucketUpdateOne {
	if v != nil {
		_u.SetSettledQuantity(*v)
	}
	return _u
}

// AddSettledQuantity adds value to the "settled_quantity" field.
func (_u *BudgetBucketUpdateOne) AddSettledQuantity(v int64) *BudgetBucketUpdateOne {
	_u.mutation.AddSettledQuantity(v)
	return _u
}

// SetReservedQuantity sets the "reserved_quantity" field.
func (_u *BudgetBucketUpdateOne) SetReservedQuantity(v int64) *BudgetBucketUpdateOne {
	_u.mutation.ResetReservedQuantity()
	_u.mutation.SetReservedQuantity(v)
	return _u
}

// SetNillableReservedQuantity sets the "reserved_quantity" field if the given value is not nil.
func (_u *BudgetBucketUpdateOne) SetNillableReservedQuantity(v *int64) *BudgetBucketUpdateOne {
	if v != nil {
		_u.SetReservedQuantity(*v)
	}
	return _u
}

// AddReservedQuantity adds value to the "reserved_quantity" field.
func (_u *BudgetBucketUpdateOne) AddReservedQuantity(v int64) *BudgetBucketUpdateOne {
	_u.mutation.AddReservedQuantity(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BudgetBucketUpdateOne) SetUpdatedAt(v time.Time) *BudgetBucketUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *BudgetBucketUpdateOne) SetNillableUpdatedAt(v *time.Time) *BudgetBucketUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the BudgetBucketMutation object of the builder.
func (_u *BudgetBucketUpdateOne) Mutation() *BudgetBucketMutation {
	return _u.mutation
}

// Where appends a list predicates to the BudgetBucketUpdate builder.
func (_u *BudgetBucketUpdateOne) Where(ps ...predicate.BudgetBucket) *BudgetBucketUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BudgetBucketUpdateOne) Select(field string, fields ...string) *BudgetBucketUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BudgetBucket entity.
func (_u *BudgetBucketUpdateOne) Save(ctx context.Context) (*BudgetBucket, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BudgetBucketUpdateOne) SaveX(ctx context.Context) *BudgetBucket {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BudgetBucketUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BudgetBucketUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BudgetBucketUpdateOne) check() error {
	if v, ok := _u.mutation.Period(); ok {
		if err := budgetbucket.PeriodValidator(v); err != nil {
			return &ValidationError{Name: "period", err: fmt.Errorf(`ent: validator failed for field "BudgetBucket.period": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Meter(); ok {
		if err := budgetbucket.MeterValidator(v); err != nil {
			return &ValidationError{Name: "meter", err: fmt.Errorf(`ent: validator failed for field "BudgetBucket.meter": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SettledQuantity(); ok {
		if err := budgetbucket.SettledQuantityValidator(v); err != nil {
			return &ValidationError{Name: "settled_quantity", err: fmt.Errorf(`ent: validator failed for field "BudgetBucket.settled_quantity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReservedQuantity(); ok {
		if err := budgetbucket.ReservedQuantityValidator(v); err != nil {
			return &ValidationError{Name: "reserved_quantity", err: fmt.Errorf(`ent: validator failed for field "BudgetBucket.reserved_quantity": %w`, err)}
		}
	}
	return nil
}

func (_u *BudgetBucketUpdateOne) sqlSave(ctx context.Context) (_node *BudgetBucket, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(budgetbucket.Table, budgetbucket.Columns, sqlgraph.NewFieldSpec(budgetbucket.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BudgetBucket.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, budgetbucket.FieldID)
		for _, f := range fields {
			if !budgetbucket.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != budgetbucket.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ScopeKey(); ok {
		_spec.SetField(budgetbucket.FieldScopeKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Period(); ok {
		_spec.SetField(budgetbucket.FieldPeriod, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PeriodStart(); ok {
		_spec.SetField(budgetbucket.FieldPeriodStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PeriodEnd(); ok {
		_spec.SetField(budgetbucket.FieldPeriodEnd, field.TypeTime, value)
	}
	if _u.mutation.PeriodEndCleared() {
		_spec.ClearField(budgetbucket.FieldPeriodEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.Meter(); ok {
		_spec.SetField(budgetbucket.FieldMeter, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SettledQuantity(); ok {
		_spec.SetField(budgetbucket.FieldSettledQuantity, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSettledQuantity(); ok {
		_spec.AddField(budgetbucket.FieldSettledQuantity, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ReservedQuantity(); ok {
		_spec.SetField(budgetbucket.FieldReservedQuantity, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReservedQuantity(); ok {
		_spec.AddField(budgetbucket.FieldReservedQuantity, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(budgetbucket.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &BudgetBucket{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{budgetbucket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
