// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"measix/platform/ent/budgetsettlement"
	"measix/platform/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BudgetSettlementDelete is the builder for deleting a BudgetSettlement entity.
type BudgetSettlementDelete struct {
	config
	hooks    []Hook
	mutation *BudgetSettlementMutation
}

// Where appends a list predicates to the BudgetSettlementDelete builder.
func (_d *BudgetSettlementDelete) Where(ps ...predicate.BudgetSettlement) *BudgetSettlementDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BudgetSettlementDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BudgetSettlementDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BudgetSettlementDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(budgetsettlement.Table, sqlgraph.NewFieldSpec(budgetsettlement.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BudgetSettlementDeleteOne is the builder for deleting a single BudgetSettlement entity.
type BudgetSettlementDeleteOne struct {
	_d *BudgetSettlementDelete
}

// Where appends a list predicates to the BudgetSettlementDelete builder.
func (_d *BudgetSettlementDeleteOne) Where(ps ...predicate.BudgetSettlement) *BudgetSettlementDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BudgetSettlementDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{budgetsettlement.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BudgetSettlementDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
