// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"measix/platform/ent/deletedcredential"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// DeletedCredential is the model entity for the DeletedCredential schema.
type DeletedCredential struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Digest holds the value of the "digest" field.
	Digest []byte `json:"digest,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt    time.Time `json:"deleted_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DeletedCredential) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case deletedcredential.FieldDigest:
			values[i] = new([]byte)
		case deletedcredential.FieldID:
			values[i] = new(sql.NullInt64)
		case deletedcredential.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DeletedCredential fields.
func (_m *DeletedCredential) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case deletedcredential.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case deletedcredential.FieldDigest:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field digest", values[i])
			} else if value != nil {
				_m.Digest = *value
			}
		case deletedcredential.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DeletedCredential.
// This includes values selected through modifiers, order, etc.
func (_m *DeletedCredential) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DeletedCredential.
// Note that you need to call DeletedCredential.Unwrap() before calling this method if this DeletedCredential
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DeletedCredential) Update() *DeletedCredentialUpdateOne {
	return NewDeletedCredentialClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DeletedCredential entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DeletedCredential) Unwrap() *DeletedCredential {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DeletedCredential is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DeletedCredential) String() string {
	var builder strings.Builder
	builder.WriteString("DeletedCredential(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("digest=")
	builder.WriteString(fmt.Sprintf("%v", _m.Digest))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(_m.DeletedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DeletedCredentials is a parsable slice of DeletedCredential.
type DeletedCredentials []*DeletedCredential
