// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"measix/platform/ent/deletedprincipal"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// DeletedPrincipal is the model entity for the DeletedPrincipal schema.
type DeletedPrincipal struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt    time.Time `json:"deleted_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DeletedPrincipal) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case deletedprincipal.FieldID:
			values[i] = new(sql.NullString)
		case deletedprincipal.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DeletedPrincipal fields.
func (_m *DeletedPrincipal) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case deletedprincipal.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case deletedprincipal.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DeletedPrincipal.
// This includes values selected through modifiers, order, etc.
func (_m *DeletedPrincipal) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DeletedPrincipal.
// Note that you need to call DeletedPrincipal.Unwrap() before calling this method if this DeletedPrincipal
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DeletedPrincipal) Update() *DeletedPrincipalUpdateOne {
	return NewDeletedPrincipalClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DeletedPrincipal entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DeletedPrincipal) Unwrap() *DeletedPrincipal {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DeletedPrincipal is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DeletedPrincipal) String() string {
	var builder strings.Builder
	builder.WriteString("DeletedPrincipal(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("deleted_at=")
	builder.WriteString(_m.DeletedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DeletedPrincipals is a parsable slice of DeletedPrincipal.
type DeletedPrincipals []*DeletedPrincipal
