// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"measix/platform/ent/deploymentsettingaudit"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// DeploymentSettingAudit is the model entity for the DeploymentSettingAudit schema.
type DeploymentSettingAudit struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// DeploymentID holds the value of the "deployment_id" field.
	DeploymentID string `json:"deployment_id,omitempty"`
	// ActorUserID holds the value of the "actor_user_id" field.
	ActorUserID string `json:"actor_user_id,omitempty"`
	// OldName holds the value of the "old_name" field.
	OldName string `json:"old_name,omitempty"`
	// NewName holds the value of the "new_name" field.
	NewName string `json:"new_name,omitempty"`
	// OldPublicOrigin holds the value of the "old_public_origin" field.
	OldPublicOrigin string `json:"old_public_origin,omitempty"`
	// NewPublicOrigin holds the value of the "new_public_origin" field.
	NewPublicOrigin string `json:"new_public_origin,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DeploymentSettingAudit) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case deploymentsettingaudit.FieldID:
			values[i] = new(sql.NullInt64)
		case deploymentsettingaudit.FieldDeploymentID, deploymentsettingaudit.FieldActorUserID, deploymentsettingaudit.FieldOldName, deploymentsettingaudit.FieldNewName, deploymentsettingaudit.FieldOldPublicOrigin, deploymentsettingaudit.FieldNewPublicOrigin:
			values[i] = new(sql.NullString)
		case deploymentsettingaudit.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DeploymentSettingAudit fields.
func (_m *DeploymentSettingAudit) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case deploymentsettingaudit.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case deploymentsettingaudit.FieldDeploymentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field deployment_id", values[i])
			} else if value.Valid {
				_m.DeploymentID = value.String
			}
		case deploymentsettingaudit.FieldActorUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor_user_id", values[i])
			} else if value.Valid {
				_m.ActorUserID = value.String
			}
		case deploymentsettingaudit.FieldOldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field old_name", values[i])
			} else if value.Valid {
				_m.OldName = value.String
			}
		case deploymentsettingaudit.FieldNewName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field new_name", values[i])
			} else if value.Valid {
				_m.NewName = value.String
			}
		case deploymentsettingaudit.FieldOldPublicOrigin:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field old_public_origin", values[i])
			} else if value.Valid {
				_m.OldPublicOrigin = value.String
			}
		case deploymentsettingaudit.FieldNewPublicOrigin:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field new_public_origin", values[i])
			} else if value.Valid {
				_m.NewPublicOrigin = value.String
			}
		case deploymentsettingaudit.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DeploymentSettingAudit.
// This includes values selected through modifiers, order, etc.
func (_m *DeploymentSettingAudit) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DeploymentSettingAudit.
// Note that you need to call DeploymentSettingAudit.Unwrap() before calling this method if this DeploymentSettingAudit
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DeploymentSettingAudit) Update() *DeploymentSettingAuditUpdateOne {
	return NewDeploymentSettingAuditClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DeploymentSettingAudit entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DeploymentSettingAudit) Unwrap() *DeploymentSettingAudit {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DeploymentSettingAudit is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DeploymentSettingAudit) String() string {
	var builder strings.Builder
	builder.WriteString("DeploymentSettingAudit(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("deployment_id=")
	builder.WriteString(_m.DeploymentID)
	builder.WriteString(", ")
	builder.WriteString("actor_user_id=")
	builder.WriteString(_m.ActorUserID)
	builder.WriteString(", ")
	builder.WriteString("old_name=")
	builder.WriteString(_m.OldName)
	builder.WriteString(", ")
	builder.WriteString("new_name=")
	builder.WriteString(_m.NewName)
	builder.WriteString(", ")
	builder.WriteString("old_public_origin=")
	builder.WriteString(_m.OldPublicOrigin)
	builder.WriteString(", ")
	builder.WriteString("new_public_origin=")
	builder.WriteString(_m.NewPublicOrigin)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DeploymentSettingAudits is a parsable slice of DeploymentSettingAudit.
type DeploymentSettingAudits []*DeploymentSettingAudit
