// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/topabomb/measix-platform-core/backend/ent/device"
	"github.com/topabomb/measix-platform-core/backend/ent/predicate"
)

// DeviceUpdate is the builder for updating Device entities.
type DeviceUpdate struct {
	config
	hooks    []Hook
	mutation *DeviceMutation
}

// Where appends a list predicates to the DeviceUpdate builder.
func (_u *DeviceUpdate) Where(ps ...predicate.Device) *DeviceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DeviceUpdate) SetUserID(v string) *DeviceUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableUserID(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetInstallationID sets the "installation_id" field.
func (_u *DeviceUpdate) SetInstallationID(v string) *DeviceUpdate {
	_u.mutation.SetInstallationID(v)
	return _u
}

// SetNillableInstallationID sets the "installation_id" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableInstallationID(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetInstallationID(*v)
	}
	return _u
}

// ClearInstallationID clears the value of the "installation_id" field.
func (_u *DeviceUpdate) ClearInstallationID() *DeviceUpdate {
	_u.mutation.ClearInstallationID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *DeviceUpdate) SetStatus(v string) *DeviceUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableStatus(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAppVersion sets the "app_version" field.
func (_u *DeviceUpdate) SetAppVersion(v string) *DeviceUpdate {
	_u.mutation.SetAppVersion(v)
	return _u
}

// SetNillableAppVersion sets the "app_version" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableAppVersion(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetAppVersion(*v)
	}
	return _u
}

// ClearAppVersion clears the value of the "app_version" field.
func (_u *DeviceUpdate) ClearAppVersion() *DeviceUpdate {
	_u.mutation.ClearAppVersion()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DeviceUpdate) SetCreatedAt(v time.Time) *DeviceUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableCreatedAt(v *time.Time) *DeviceUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *DeviceUpdate) SetLastSeenAt(v time.Time) *DeviceUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableLastSeenAt(v *time.Time) *DeviceUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (_u *DeviceUpdate) ClearLastSeenAt() *DeviceUpdate {
	_u.mutation.ClearLastSeenAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *DeviceUpdate) SetRevokedAt(v time.Time) *DeviceUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableRevokedAt(v *time.Time) *DeviceUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *DeviceUpdate) ClearRevokedAt() *DeviceUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// Mutation returns the DeviceMutation object of the builder.
func (_u *DeviceUpdate) Mutation() *DeviceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeviceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeviceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *DeviceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(device.Table, device.Columns, sqlgraph.NewFieldSpec(device.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(device.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.InstallationID(); ok {
		_spec.SetField(device.FieldInstallationID, field.TypeString, value)
	}
	if _u.mutation.InstallationIDCleared() {
		_spec.ClearField(device.FieldInstallationID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(device.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppVersion(); ok {
		_spec.SetField(device.FieldAppVersion, field.TypeString, value)
	}
	if _u.mutation.AppVersionCleared() {
		_spec.ClearField(device.FieldAppVersion, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(device.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(device.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.LastSeenAtCleared() {
		_spec.ClearField(device.FieldLastSeenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(device.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(device.FieldRevokedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeviceUpdateOne is the builder for updating a single Device entity.
type DeviceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeviceMutation
}

// SetUserID sets the "user_id" field.
func (_u *DeviceUpdateOne) SetUserID(v string) *DeviceUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableUserID(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetInstallationID sets the "installation_id" field.
func (_u *DeviceUpdateOne) SetInstallationID(v string) *DeviceUpdateOne {
	_u.mutation.SetInstallationID(v)
	return _u
}

// SetNillableInstallationID sets the "installation_id" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableInstallationID(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetInstallationID(*v)
	}
	return _u
}

// ClearInstallationID clears the value of the "installation_id" field.
func (_u *DeviceUpdateOne) ClearInstallationID() *DeviceUpdateOne {
	_u.mutation.ClearInstallationID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *DeviceUpdateOne) SetStatus(v string) *DeviceUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableStatus(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAppVersion sets the "app_version" field.
func (_u *DeviceUpdateOne) SetAppVersion(v string) *DeviceUpdateOne {
	_u.mutation.SetAppVersion(v)
	return _u
}

// SetNillableAppVersion sets the "app_version" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableAppVersion(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetAppVersion(*v)
	}
	return _u
}

// ClearAppVersion clears the value of the "app_version" field.
func (_u *DeviceUpdateOne) ClearAppVersion() *DeviceUpdateOne {
	_u.mutation.ClearAppVersion()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DeviceUpdateOne) SetCreatedAt(v time.Time) *DeviceUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableCreatedAt(v *time.Time) *DeviceUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *DeviceUpdateOne) SetLastSeenAt(v time.Time) *DeviceUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableLastSeenAt(v *time.Time) *DeviceUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (_u *DeviceUpdateOne) ClearLastSeenAt() *DeviceUpdateOne {
	_u.mutation.ClearLastSeenAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *DeviceUpdateOne) SetRevokedAt(v time.Time) *DeviceUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableRevokedAt(v *time.Time) *DeviceUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *DeviceUpdateOne) ClearRevokedAt() *DeviceUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// Mutation returns the DeviceMutation object of the builder.
func (_u *DeviceUpdateOne) Mutation() *DeviceMutation {
	return _u.mutation
}

// Where appends a list predicates to the DeviceUpdate builder.
func (_u *DeviceUpdateOne) Where(ps ...predicate.Device) *DeviceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeviceUpdateOne) Select(field string, fields ...string) *DeviceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Device entity.
func (_u *DeviceUpdateOne) Save(ctx context.Context) (*Device, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceUpdateOne) SaveX(ctx context.Context) *Device {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeviceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *DeviceUpdateOne) sqlSave(ctx context.Context) (_node *Device, err error) {
	_spec := sqlgraph.NewUpdateSpec(device.Table, device.Columns, sqlgraph.NewFieldSpec(device.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Device.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, device.FieldID)
		for _, f := range fields {
			if !device.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != device.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(device.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.InstallationID(); ok {
		_spec.SetField(device.FieldInstallationID, field.TypeString, value)
	}
	if _u.mutation.InstallationIDCleared() {
		_spec.ClearField(device.FieldInstallationID, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(device.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppVersion(); ok {
		_spec.SetField(device.FieldAppVersion, field.TypeString, value)
	}
	if _u.mutation.AppVersionCleared() {
		_spec.ClearField(device.FieldAppVersion, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(device.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(device.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.LastSeenAtCleared() {
		_spec.ClearField(device.FieldLastSeenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(device.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(device.FieldRevokedAt, field.TypeTime)
	}
	_node = &Device{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
