// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"measix/platform/ent/managedstate"
	"measix/platform/ent/predicate"
)

// ManagedStateUpdate is the builder for updating ManagedState entities.
type ManagedStateUpdate struct {
	config
	hooks    []Hook
	mutation *ManagedStateMutation
}

// Where appends a list predicates to the ManagedStateUpdate builder.
func (_u *ManagedStateUpdate) Where(ps ...predicate.ManagedState) *ManagedStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetActiveReleaseID sets the "active_release_id" field.
func (_u *ManagedStateUpdate) SetActiveReleaseID(v string) *ManagedStateUpdate {
	_u.mutation.SetActiveReleaseID(v)
	return _u
}

// SetNillableActiveReleaseID sets the "active_release_id" field if the given value is not nil.
func (_u *ManagedStateUpdate) SetNillableActiveReleaseID(v *string) *ManagedStateUpdate {
	if v != nil {
		_u.SetActiveReleaseID(*v)
	}
	return _u
}

// ClearActiveReleaseID clears the value of the "active_release_id" field.
func (_u *ManagedStateUpdate) ClearActiveReleaseID() *ManagedStateUpdate {
	_u.mutation.ClearActiveReleaseID()
	return _u
}

// SetActiveManagedGeneration sets the "active_managed_generation" field.
func (_u *ManagedStateUpdate) SetActiveManagedGeneration(v int64) *ManagedStateUpdate {
	_u.mutation.ResetActiveManagedGeneration()
	_u.mutation.SetActiveManagedGeneration(v)
	return _u
}

// SetNillableActiveManagedGeneration sets the "active_managed_generation" field if the given value is not nil.
func (_u *ManagedStateUpdate) SetNillableActiveManagedGeneration(v *int64) *ManagedStateUpdate {
	if v != nil {
		_u.SetActiveManagedGeneration(*v)
	}
	return _u
}

// AddActiveManagedGeneration adds value to the "active_managed_generation" field.
func (_u *ManagedStateUpdate) AddActiveManagedGeneration(v int64) *ManagedStateUpdate {
	_u.mutation.AddActiveManagedGeneration(v)
	return _u
}

// SetDesiredControlRevision sets the "desired_control_revision" field.
func (_u *ManagedStateUpdate) SetDesiredControlRevision(v int64) *ManagedStateUpdate {
	_u.mutation.ResetDesiredControlRevision()
	_u.mutation.SetDesiredControlRevision(v)
	return _u
}

// SetNillableDesiredControlRevision sets the "desired_control_revision" field if the given value is not nil.
func (_u *ManagedStateUpdate) SetNillableDesiredControlRevision(v *int64) *ManagedStateUpdate {
	if v != nil {
		_u.SetDesiredControlRevision(*v)
	}
	return _u
}

// AddDesiredControlRevision adds value to the "desired_control_revision" field.
func (_u *ManagedStateUpdate) AddDesiredControlRevision(v int64) *ManagedStateUpdate {
	_u.mutation.AddDesiredControlRevision(v)
	return _u
}

// SetDesiredBundleHash sets the "desired_bundle_hash" field.
func (_u *ManagedStateUpdate) SetDesiredBundleHash(v string) *ManagedStateUpdate {
	_u.mutation.SetDesiredBundleHash(v)
	return _u
}

// SetNillableDesiredBundleHash sets the "desired_bundle_hash" field if the given value is not nil.
func (_u *ManagedStateUpdate) SetNillableDesiredBundleHash(v *string) *ManagedStateUpdate {
	if v != nil {
		_u.SetDesiredBundleHash(*v)
	}
	return _u
}

// ClearDesiredBundleHash clears the value of the "desired_bundle_hash" field.
func (_u *ManagedStateUpdate) ClearDesiredBundleHash() *ManagedStateUpdate {
	_u.mutation.ClearDesiredBundleHash()
	return _u
}

// SetManagedStateRevision sets the "managed_state_revision" field.
func (_u *ManagedStateUpdate) SetManagedStateRevision(v int64) *ManagedStateUpdate {
	_u.mutation.ResetManagedStateRevision()
	_u.mutation.SetManagedStateRevision(v)
	return _u
}

// SetNillableManagedStateRevision sets the "managed_state_revision" field if the given value is not nil.
func (_u *ManagedStateUpdate) SetNillableManagedStateRevision(v *int64) *ManagedStateUpdate {
	if v != nil {
		_u.SetManagedStateRevision(*v)
	}
	return _u
}

// AddManagedStateRevision adds value to the "managed_state_revision" field.
func (_u *ManagedStateUpdate) AddManagedStateRevision(v int64) *ManagedStateUpdate {
	_u.mutation.AddManagedStateRevision(v)
	return _u
}

// SetRuntimeStatus sets the "runtime_status" field.
func (_u *ManagedStateUpdate) SetRuntimeStatus(v string) *ManagedStateUpdate {
	_u.mutation.SetRuntimeStatus(v)
	return _u
}

// SetNillableRuntimeStatus sets the "runtime_status" field if the given value is not nil.
func (_u *ManagedStateUpdate) SetNillableRuntimeStatus(v *string) *ManagedStateUpdate {
	if v != nil {
		_u.SetRuntimeStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ManagedStateUpdate) SetUpdatedAt(v time.Time) *ManagedStateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ManagedStateUpdate) SetNillableUpdatedAt(v *time.Time) *ManagedStateUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the ManagedStateMutation object of the builder.
func (_u *ManagedStateUpdate) Mutation() *ManagedStateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ManagedStateUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ManagedStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ManagedStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ManagedStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ManagedStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(managedstate.Table, managedstate.Columns, sqlgraph.NewFieldSpec(managedstate.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ActiveReleaseID(); ok {
		_spec.SetField(managedstate.FieldActiveReleaseID, field.TypeString, value)
	}
	if _u.mutation.ActiveReleaseIDCleared() {
		_spec.ClearField(managedstate.FieldActiveReleaseID, field.TypeString)
	}
	if value, ok := _u.mutation.ActiveManagedGeneration(); ok {
		_spec.SetField(managedstate.FieldActiveManagedGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedActiveManagedGeneration(); ok {
		_spec.AddField(managedstate.FieldActiveManagedGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DesiredControlRevision(); ok {
		_spec.SetField(managedstate.FieldDesiredControlRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDesiredControlRevision(); ok {
		_spec.AddField(managedstate.FieldDesiredControlRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DesiredBundleHash(); ok {
		_spec.SetField(managedstate.FieldDesiredBundleHash, field.TypeString, value)
	}
	if _u.mutation.DesiredBundleHashCleared() {
		_spec.ClearField(managedstate.FieldDesiredBundleHash, field.TypeString)
	}
	if value, ok := _u.mutation.ManagedStateRevision(); ok {
		_spec.SetField(managedstate.FieldManagedStateRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedManagedStateRevision(); ok {
		_spec.AddField(managedstate.FieldManagedStateRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RuntimeStatus(); ok {
		_spec.SetField(managedstate.FieldRuntimeStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(managedstate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{managedstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ManagedStateUpdateOne is the builder for updating a single ManagedState entity.
type ManagedStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ManagedStateMutation
}

// SetActiveReleaseID sets the "active_release_id" field.
func (_u *ManagedStateUpdateOne) SetActiveReleaseID(v string) *ManagedStateUpdateOne {
	_u.mutation.SetActiveReleaseID(v)
	return _u
}

// SetNillableActiveReleaseID sets the "active_release_id" field if the given value is not nil.
func (_u *ManagedStateUpdateOne) SetNillableActiveReleaseID(v *string) *ManagedStateUpdateOne {
	if v != nil {
		_u.SetActiveReleaseID(*v)
	}
	return _u
}

// ClearActiveReleaseID clears the value of the "active_release_id" field.
func (_u *ManagedStateUpdateOne) ClearActiveReleaseID() *ManagedStateUpdateOne {
	_u.mutation.ClearActiveReleaseID()
	return _u
}

// SetActiveManagedGeneration sets the "active_managed_generation" field.
func (_u *ManagedStateUpdateOne) SetActiveManagedGeneration(v int64) *ManagedStateUpdateOne {
	_u.mutation.ResetActiveManagedGeneration()
	_u.mutation.SetActiveManagedGeneration(v)
	return _u
}

// SetNillableActiveManagedGeneration sets the "active_managed_generation" field if the given value is not nil.
func (_u *ManagedStateUpdateOne) SetNillableActiveManagedGeneration(v *int64) *ManagedStateUpdateOne {
	if v != nil {
		_u.SetActiveManagedGeneration(*v)
	}
	return _u
}

// AddActiveManagedGeneration adds value to the "active_managed_generation" field.
func (_u *ManagedStateUpdateOne) AddActiveManagedGeneration(v int64) *ManagedStateUpdateOne {
	_u.mutation.AddActiveManagedGeneration(v)
	return _u
}

// SetDesiredControlRevision sets the "desired_control_revision" field.
func (_u *ManagedStateUpdateOne) SetDesiredControlRevision(v int64) *ManagedStateUpdateOne {
	_u.mutation.ResetDesiredControlRevision()
	_u.mutation.SetDesiredControlRevision(v)
	return _u
}

// SetNillableDesiredControlRevision sets the "desired_control_revision" field if the given value is not nil.
func (_u *ManagedStateUpdateOne) SetNillableDesiredControlRevision(v *int64) *ManagedStateUpdateOne {
	if v != nil {
		_u.SetDesiredControlRevision(*v)
	}
	return _u
}

// AddDesiredControlRevision adds value to the "desired_control_revision" field.
func (_u *ManagedStateUpdateOne) AddDesiredControlRevision(v int64) *ManagedStateUpdateOne {
	_u.mutation.AddDesiredControlRevision(v)
	return _u
}

// SetDesiredBundleHash sets the "desired_bundle_hash" field.
func (_u *ManagedStateUpdateOne) SetDesiredBundleHash(v string) *ManagedStateUpdateOne {
	_u.mutation.SetDesiredBundleHash(v)
	return _u
}

// SetNillableDesiredBundleHash sets the "desired_bundle_hash" field if the given value is not nil.
func (_u *ManagedStateUpdateOne) SetNillableDesiredBundleHash(v *string) *ManagedStateUpdateOne {
	if v != nil {
		_u.SetDesiredBundleHash(*v)
	}
	return _u
}

// ClearDesiredBundleHash clears the value of the "desired_bundle_hash" field.
func (_u *ManagedStateUpdateOne) ClearDesiredBundleHash() *ManagedStateUpdateOne {
	_u.mutation.ClearDesiredBundleHash()
	return _u
}

// SetManagedStateRevision sets the "managed_state_revision" field.
func (_u *ManagedStateUpdateOne) SetManagedStateRevision(v int64) *ManagedStateUpdateOne {
	_u.mutation.ResetManagedStateRevision()
	_u.mutation.SetManagedStateRevision(v)
	return _u
}

// SetNillableManagedStateRevision sets the "managed_state_revision" field if the given value is not nil.
func (_u *ManagedStateUpdateOne) SetNillableManagedStateRevision(v *int64) *ManagedStateUpdateOne {
	if v != nil {
		_u.SetManagedStateRevision(*v)
	}
	return _u
}

// AddManagedStateRevision adds value to the "managed_state_revision" field.
func (_u *ManagedStateUpdateOne) AddManagedStateRevision(v int64) *ManagedStateUpdateOne {
	_u.mutation.AddManagedStateRevision(v)
	return _u
}

// SetRuntimeStatus sets the "runtime_status" field.
func (_u *ManagedStateUpdateOne) SetRuntimeStatus(v string) *ManagedStateUpdateOne {
	_u.mutation.SetRuntimeStatus(v)
	return _u
}

// SetNillableRuntimeStatus sets the "runtime_status" field if the given value is not nil.
func (_u *ManagedStateUpdateOne) SetNillableRuntimeStatus(v *string) *ManagedStateUpdateOne {
	if v != nil {
		_u.SetRuntimeStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ManagedStateUpdateOne) SetUpdatedAt(v time.Time) *ManagedStateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ManagedStateUpdateOne) SetNillableUpdatedAt(v *time.Time) *ManagedStateUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the ManagedStateMutation object of the builder.
func (_u *ManagedStateUpdateOne) Mutation() *ManagedStateMutation {
	return _u.mutation
}

// Where appends a list predicates to the ManagedStateUpdate builder.
func (_u *ManagedStateUpdateOne) Where(ps ...predicate.ManagedState) *ManagedStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ManagedStateUpdateOne) Select(field string, fields ...string) *ManagedStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ManagedState entity.
func (_u *ManagedStateUpdateOne) Save(ctx context.Context) (*ManagedState, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ManagedStateUpdateOne) SaveX(ctx context.Context) *ManagedState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ManagedStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ManagedStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ManagedStateUpdateOne) sqlSave(ctx context.Context) (_node *ManagedState, err error) {
	_spec := sqlgraph.NewUpdateSpec(managedstate.Table, managedstate.Columns, sqlgraph.NewFieldSpec(managedstate.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ManagedState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, managedstate.FieldID)
		for _, f := range fields {
			if !managedstate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != managedstate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ActiveReleaseID(); ok {
		_spec.SetField(managedstate.FieldActiveReleaseID, field.TypeString, value)
	}
	if _u.mutation.ActiveReleaseIDCleared() {
		_spec.ClearField(managedstate.FieldActiveReleaseID, field.TypeString)
	}
	if value, ok := _u.mutation.ActiveManagedGeneration(); ok {
		_spec.SetField(managedstate.FieldActiveManagedGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedActiveManagedGeneration(); ok {
		_spec.AddField(managedstate.FieldActiveManagedGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DesiredControlRevision(); ok {
		_spec.SetField(managedstate.FieldDesiredControlRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDesiredControlRevision(); ok {
		_spec.AddField(managedstate.FieldDesiredControlRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DesiredBundleHash(); ok {
		_spec.SetField(managedstate.FieldDesiredBundleHash, field.TypeString, value)
	}
	if _u.mutation.DesiredBundleHashCleared() {
		_spec.ClearField(managedstate.FieldDesiredBundleHash, field.TypeString)
	}
	if value, ok := _u.mutation.ManagedStateRevision(); ok {
		_spec.SetField(managedstate.FieldManagedStateRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedManagedStateRevision(); ok {
		_spec.AddField(managedstate.FieldManagedStateRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RuntimeStatus(); ok {
		_spec.SetField(managedstate.FieldRuntimeStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(managedstate.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ManagedState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{managedstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
