// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"measix/platform/ent/portalsession"
	"measix/platform/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PortalSessionUpdate is the builder for updating PortalSession entities.
type PortalSessionUpdate struct {
	config
	hooks    []Hook
	mutation *PortalSessionMutation
}

// Where appends a list predicates to the PortalSessionUpdate builder.
func (_u *PortalSessionUpdate) Where(ps ...predicate.PortalSession) *PortalSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCookieDigest sets the "cookie_digest" field.
func (_u *PortalSessionUpdate) SetCookieDigest(v []byte) *PortalSessionUpdate {
	_u.mutation.SetCookieDigest(v)
	return _u
}

// ClearCookieDigest clears the value of the "cookie_digest" field.
func (_u *PortalSessionUpdate) ClearCookieDigest() *PortalSessionUpdate {
	_u.mutation.ClearCookieDigest()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *PortalSessionUpdate) SetExpiresAt(v time.Time) *PortalSessionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *PortalSessionUpdate) SetNillableExpiresAt(v *time.Time) *PortalSessionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumed sets the "consumed" field.
func (_u *PortalSessionUpdate) SetConsumed(v bool) *PortalSessionUpdate {
	_u.mutation.SetConsumed(v)
	return _u
}

// SetNillableConsumed sets the "consumed" field if the given value is not nil.
func (_u *PortalSessionUpdate) SetNillableConsumed(v *bool) *PortalSessionUpdate {
	if v != nil {
		_u.SetConsumed(*v)
	}
	return _u
}

// SetRevoked sets the "revoked" field.
func (_u *PortalSessionUpdate) SetRevoked(v bool) *PortalSessionUpdate {
	_u.mutation.SetRevoked(v)
	return _u
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_u *PortalSessionUpdate) SetNillableRevoked(v *bool) *PortalSessionUpdate {
	if v != nil {
		_u.SetRevoked(*v)
	}
	return _u
}

// Mutation returns the PortalSessionMutation object of the builder.
func (_u *PortalSessionUpdate) Mutation() *PortalSessionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PortalSessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PortalSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PortalSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PortalSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PortalSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(portalsession.Table, portalsession.Columns, sqlgraph.NewFieldSpec(portalsession.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CookieDigest(); ok {
		_spec.SetField(portalsession.FieldCookieDigest, field.TypeBytes, value)
	}
	if _u.mutation.CookieDigestCleared() {
		_spec.ClearField(portalsession.FieldCookieDigest, field.TypeBytes)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(portalsession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Consumed(); ok {
		_spec.SetField(portalsession.FieldConsumed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Revoked(); ok {
		_spec.SetField(portalsession.FieldRevoked, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{portalsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PortalSessionUpdateOne is the builder for updating a single PortalSession entity.
type PortalSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PortalSessionMutation
}

// SetCookieDigest sets the "cookie_digest" field.
func (_u *PortalSessionUpdateOne) SetCookieDigest(v []byte) *PortalSessionUpdateOne {
	_u.mutation.SetCookieDigest(v)
	return _u
}

// ClearCookieDigest clears the value of the "cookie_digest" field.
func (_u *PortalSessionUpdateOne) ClearCookieDigest() *PortalSessionUpdateOne {
	_u.mutation.ClearCookieDigest()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *PortalSessionUpdateOne) SetExpiresAt(v time.Time) *PortalSessionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *PortalSessionUpdateOne) SetNillableExpiresAt(v *time.Time) *PortalSessionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumed sets the "consumed" field.
func (_u *PortalSessionUpdateOne) SetConsumed(v bool) *PortalSessionUpdateOne {
	_u.mutation.SetConsumed(v)
	return _u
}

// SetNillableConsumed sets the "consumed" field if the given value is not nil.
func (_u *PortalSessionUpdateOne) SetNillableConsumed(v *bool) *PortalSessionUpdateOne {
	if v != nil {
		_u.SetConsumed(*v)
	}
	return _u
}

// SetRevoked sets the "revoked" field.
func (_u *PortalSessionUpdateOne) SetRevoked(v bool) *PortalSessionUpdateOne {
	_u.mutation.SetRevoked(v)
	return _u
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_u *PortalSessionUpdateOne) SetNillableRevoked(v *bool) *PortalSessionUpdateOne {
	if v != nil {
		_u.SetRevoked(*v)
	}
	return _u
}

// Mutation returns the PortalSessionMutation object of the builder.
func (_u *PortalSessionUpdateOne) Mutation() *PortalSessionMutation {
	return _u.mutation
}

// Where appends a list predicates to the PortalSessionUpdate builder.
func (_u *PortalSessionUpdateOne) Where(ps ...predicate.PortalSession) *PortalSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PortalSessionUpdateOne) Select(field string, fields ...string) *PortalSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PortalSession entity.
func (_u *PortalSessionUpdateOne) Save(ctx context.Context) (*PortalSession, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PortalSessionUpdateOne) SaveX(ctx context.Context) *PortalSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PortalSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PortalSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PortalSessionUpdateOne) sqlSave(ctx context.Context) (_node *PortalSession, err error) {
	_spec := sqlgraph.NewUpdateSpec(portalsession.Table, portalsession.Columns, sqlgraph.NewFieldSpec(portalsession.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PortalSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, portalsession.FieldID)
		for _, f := range fields {
			if !portalsession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != portalsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CookieDigest(); ok {
		_spec.SetField(portalsession.FieldCookieDigest, field.TypeBytes, value)
	}
	if _u.mutation.CookieDigestCleared() {
		_spec.ClearField(portalsession.FieldCookieDigest, field.TypeBytes)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(portalsession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Consumed(); ok {
		_spec.SetField(portalsession.FieldConsumed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Revoked(); ok {
		_spec.SetField(portalsession.FieldRevoked, field.TypeBool, value)
	}
	_node = &PortalSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{portalsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
