// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"measix/platform/ent/predicate"
	"measix/platform/ent/requestusage"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RequestUsageDelete is the builder for deleting a RequestUsage entity.
type RequestUsageDelete struct {
	config
	hooks    []Hook
	mutation *RequestUsageMutation
}

// Where appends a list predicates to the RequestUsageDelete builder.
func (_d *RequestUsageDelete) Where(ps ...predicate.RequestUsage) *RequestUsageDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RequestUsageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RequestUsageDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RequestUsageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(requestusage.Table, sqlgraph.NewFieldSpec(requestusage.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RequestUsageDeleteOne is the builder for deleting a single RequestUsage entity.
type RequestUsageDeleteOne struct {
	_d *RequestUsageDelete
}

// Where appends a list predicates to the RequestUsageDelete builder.
func (_d *RequestUsageDeleteOne) Where(ps ...predicate.RequestUsage) *RequestUsageDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RequestUsageDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{requestusage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RequestUsageDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
