// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/topabomb/measix-platform-core/backend/ent/upstream"
)

// UpstreamCreate is the builder for creating a Upstream entity.
type UpstreamCreate struct {
	config
	mutation *UpstreamMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *UpstreamCreate) SetName(v string) *UpstreamCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetConfigRevision sets the "config_revision" field.
func (_c *UpstreamCreate) SetConfigRevision(v int64) *UpstreamCreate {
	_c.mutation.SetConfigRevision(v)
	return _c
}

// SetActiveConfigRevision sets the "active_config_revision" field.
func (_c *UpstreamCreate) SetActiveConfigRevision(v int64) *UpstreamCreate {
	_c.mutation.SetActiveConfigRevision(v)
	return _c
}

// SetNillableActiveConfigRevision sets the "active_config_revision" field if the given value is not nil.
func (_c *UpstreamCreate) SetNillableActiveConfigRevision(v *int64) *UpstreamCreate {
	if v != nil {
		_c.SetActiveConfigRevision(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *UpstreamCreate) SetStatus(v string) *UpstreamCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UpstreamCreate) SetCreatedAt(v time.Time) *UpstreamCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UpstreamCreate) SetUpdatedAt(v time.Time) *UpstreamCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *UpstreamCreate) SetID(v string) *UpstreamCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the UpstreamMutation object of the builder.
func (_c *UpstreamCreate) Mutation() *UpstreamMutation {
	return _c.mutation
}

// Save creates the Upstream in the database.
func (_c *UpstreamCreate) Save(ctx context.Context) (*Upstream, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UpstreamCreate) SaveX(ctx context.Context) *Upstream {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UpstreamCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Upstream.name"`)}
	}
	if _, ok := _c.mutation.ConfigRevision(); !ok {
		return &ValidationError{Name: "config_revision", err: errors.New(`ent: missing required field "Upstream.config_revision"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Upstream.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Upstream.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Upstream.updated_at"`)}
	}
	return nil
}

func (_c *UpstreamCreate) sqlSave(ctx context.Context) (*Upstream, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Upstream.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UpstreamCreate) createSpec() (*Upstream, *sqlgraph.CreateSpec) {
	var (
		_node = &Upstream{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(upstream.Table, sqlgraph.NewFieldSpec(upstream.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(upstream.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.ConfigRevision(); ok {
		_spec.SetField(upstream.FieldConfigRevision, field.TypeInt64, value)
		_node.ConfigRevision = value
	}
	if value, ok := _c.mutation.ActiveConfigRevision(); ok {
		_spec.SetField(upstream.FieldActiveConfigRevision, field.TypeInt64, value)
		_node.ActiveConfigRevision = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(upstream.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(upstream.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(upstream.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// UpstreamCreateBulk is the builder for creating many Upstream entities in bulk.
type UpstreamCreateBulk struct {
	config
	err      error
	builders []*UpstreamCreate
}

// Save creates the Upstream entities in the database.
func (_c *UpstreamCreateBulk) Save(ctx context.Context) ([]*Upstream, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Upstream, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpstreamMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UpstreamCreateBulk) SaveX(ctx context.Context) []*Upstream {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
