// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"measix/platform/ent/usageevent"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UsageEventCreate is the builder for creating a UsageEvent entity.
type UsageEventCreate struct {
	config
	mutation *UsageEventMutation
	hooks    []Hook
}

// SetRequestID sets the "request_id" field.
func (_c *UsageEventCreate) SetRequestID(v string) *UsageEventCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetRevision sets the "revision" field.
func (_c *UsageEventCreate) SetRevision(v int64) *UsageEventCreate {
	_c.mutation.SetRevision(v)
	return _c
}

// SetEventHash sets the "event_hash" field.
func (_c *UsageEventCreate) SetEventHash(v string) *UsageEventCreate {
	_c.mutation.SetEventHash(v)
	return _c
}

// SetSourceEventID sets the "source_event_id" field.
func (_c *UsageEventCreate) SetSourceEventID(v string) *UsageEventCreate {
	_c.mutation.SetSourceEventID(v)
	return _c
}

// SetPayloadJSON sets the "payload_json" field.
func (_c *UsageEventCreate) SetPayloadJSON(v []byte) *UsageEventCreate {
	_c.mutation.SetPayloadJSON(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UsageEventCreate) SetCreatedAt(v time.Time) *UsageEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *UsageEventCreate) SetID(v int) *UsageEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the UsageEventMutation object of the builder.
func (_c *UsageEventCreate) Mutation() *UsageEventMutation {
	return _c.mutation
}

// Save creates the UsageEvent in the database.
func (_c *UsageEventCreate) Save(ctx context.Context) (*UsageEvent, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UsageEventCreate) SaveX(ctx context.Context) *UsageEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UsageEventCreate) check() error {
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "UsageEvent.request_id"`)}
	}
	if _, ok := _c.mutation.Revision(); !ok {
		return &ValidationError{Name: "revision", err: errors.New(`ent: missing required field "UsageEvent.revision"`)}
	}
	if v, ok := _c.mutation.Revision(); ok {
		if err := usageevent.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "UsageEvent.revision": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EventHash(); !ok {
		return &ValidationError{Name: "event_hash", err: errors.New(`ent: missing required field "UsageEvent.event_hash"`)}
	}
	if _, ok := _c.mutation.SourceEventID(); !ok {
		return &ValidationError{Name: "source_event_id", err: errors.New(`ent: missing required field "UsageEvent.source_event_id"`)}
	}
	if _, ok := _c.mutation.PayloadJSON(); !ok {
		return &ValidationError{Name: "payload_json", err: errors.New(`ent: missing required field "UsageEvent.payload_json"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UsageEvent.created_at"`)}
	}
	return nil
}

func (_c *UsageEventCreate) sqlSave(ctx context.Context) (*UsageEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UsageEventCreate) createSpec() (*UsageEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &UsageEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usageevent.Table, sqlgraph.NewFieldSpec(usageevent.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(usageevent.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.Revision(); ok {
		_spec.SetField(usageevent.FieldRevision, field.TypeInt64, value)
		_node.Revision = value
	}
	if value, ok := _c.mutation.EventHash(); ok {
		_spec.SetField(usageevent.FieldEventHash, field.TypeString, value)
		_node.EventHash = value
	}
	if value, ok := _c.mutation.SourceEventID(); ok {
		_spec.SetField(usageevent.FieldSourceEventID, field.TypeString, value)
		_node.SourceEventID = value
	}
	if value, ok := _c.mutation.PayloadJSON(); ok {
		_spec.SetField(usageevent.FieldPayloadJSON, field.TypeBytes, value)
		_node.PayloadJSON = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usageevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// UsageEventCreateBulk is the builder for creating many UsageEvent entities in bulk.
type UsageEventCreateBulk struct {
	config
	err      error
	builders []*UsageEventCreate
}

// Save creates the UsageEvent entities in the database.
func (_c *UsageEventCreateBulk) Save(ctx context.Context) ([]*UsageEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UsageEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UsageEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UsageEventCreateBulk) SaveX(ctx context.Context) []*UsageEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
