// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"measix/platform/ent/predicate"
	"measix/platform/ent/workspaceservice"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkspaceServiceUpdate is the builder for updating WorkspaceService entities.
type WorkspaceServiceUpdate struct {
	config
	hooks    []Hook
	mutation *WorkspaceServiceMutation
}

// Where appends a list predicates to the WorkspaceServiceUpdate builder.
func (_u *WorkspaceServiceUpdate) Where(ps ...predicate.WorkspaceService) *WorkspaceServiceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *WorkspaceServiceUpdate) SetName(v string) *WorkspaceServiceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WorkspaceServiceUpdate) SetNillableName(v *string) *WorkspaceServiceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetConfigRevision sets the "config_revision" field.
func (_u *WorkspaceServiceUpdate) SetConfigRevision(v int64) *WorkspaceServiceUpdate {
	_u.mutation.ResetConfigRevision()
	_u.mutation.SetConfigRevision(v)
	return _u
}

// SetNillableConfigRevision sets the "config_revision" field if the given value is not nil.
func (_u *WorkspaceServiceUpdate) SetNillableConfigRevision(v *int64) *WorkspaceServiceUpdate {
	if v != nil {
		_u.SetConfigRevision(*v)
	}
	return _u
}

// AddConfigRevision adds value to the "config_revision" field.
func (_u *WorkspaceServiceUpdate) AddConfigRevision(v int64) *WorkspaceServiceUpdate {
	_u.mutation.AddConfigRevision(v)
	return _u
}

// SetActiveConfigRevision sets the "active_config_revision" field.
func (_u *WorkspaceServiceUpdate) SetActiveConfigRevision(v int64) *WorkspaceServiceUpdate {
	_u.mutation.ResetActiveConfigRevision()
	_u.mutation.SetActiveConfigRevision(v)
	return _u
}

// SetNillableActiveConfigRevision sets the "active_config_revision" field if the given value is not nil.
func (_u *WorkspaceServiceUpdate) SetNillableActiveConfigRevision(v *int64) *WorkspaceServiceUpdate {
	if v != nil {
		_u.SetActiveConfigRevision(*v)
	}
	return _u
}

// AddActiveConfigRevision adds value to the "active_config_revision" field.
func (_u *WorkspaceServiceUpdate) AddActiveConfigRevision(v int64) *WorkspaceServiceUpdate {
	_u.mutation.AddActiveConfigRevision(v)
	return _u
}

// ClearActiveConfigRevision clears the value of the "active_config_revision" field.
func (_u *WorkspaceServiceUpdate) ClearActiveConfigRevision() *WorkspaceServiceUpdate {
	_u.mutation.ClearActiveConfigRevision()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *WorkspaceServiceUpdate) SetEnabled(v bool) *WorkspaceServiceUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *WorkspaceServiceUpdate) SetNillableEnabled(v *bool) *WorkspaceServiceUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *WorkspaceServiceUpdate) SetState(v string) *WorkspaceServiceUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *WorkspaceServiceUpdate) SetNillableState(v *string) *WorkspaceServiceUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetDiagnosticCode sets the "diagnostic_code" field.
func (_u *WorkspaceServiceUpdate) SetDiagnosticCode(v string) *WorkspaceServiceUpdate {
	_u.mutation.SetDiagnosticCode(v)
	return _u
}

// SetNillableDiagnosticCode sets the "diagnostic_code" field if the given value is not nil.
func (_u *WorkspaceServiceUpdate) SetNillableDiagnosticCode(v *string) *WorkspaceServiceUpdate {
	if v != nil {
		_u.SetDiagnosticCode(*v)
	}
	return _u
}

// ClearDiagnosticCode clears the value of the "diagnostic_code" field.
func (_u *WorkspaceServiceUpdate) ClearDiagnosticCode() *WorkspaceServiceUpdate {
	_u.mutation.ClearDiagnosticCode()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *WorkspaceServiceUpdate) SetCreatedAt(v time.Time) *WorkspaceServiceUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *WorkspaceServiceUpdate) SetNillableCreatedAt(v *time.Time) *WorkspaceServiceUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkspaceServiceUpdate) SetUpdatedAt(v time.Time) *WorkspaceServiceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *WorkspaceServiceUpdate) SetNillableUpdatedAt(v *time.Time) *WorkspaceServiceUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the WorkspaceServiceMutation object of the builder.
func (_u *WorkspaceServiceUpdate) Mutation() *WorkspaceServiceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkspaceServiceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkspaceServiceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkspaceServiceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkspaceServiceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *WorkspaceServiceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(workspaceservice.Table, workspaceservice.Columns, sqlgraph.NewFieldSpec(workspaceservice.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(workspaceservice.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConfigRevision(); ok {
		_spec.SetField(workspaceservice.FieldConfigRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedConfigRevision(); ok {
		_spec.AddField(workspaceservice.FieldConfigRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ActiveConfigRevision(); ok {
		_spec.SetField(workspaceservice.FieldActiveConfigRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedActiveConfigRevision(); ok {
		_spec.AddField(workspaceservice.FieldActiveConfigRevision, field.TypeInt64, value)
	}
	if _u.mutation.ActiveConfigRevisionCleared() {
		_spec.ClearField(workspaceservice.FieldActiveConfigRevision, field.TypeInt64)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(workspaceservice.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(workspaceservice.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.DiagnosticCode(); ok {
		_spec.SetField(workspaceservice.FieldDiagnosticCode, field.TypeString, value)
	}
	if _u.mutation.DiagnosticCodeCleared() {
		_spec.ClearField(workspaceservice.FieldDiagnosticCode, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(workspaceservice.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workspaceservice.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspaceservice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkspaceServiceUpdateOne is the builder for updating a single WorkspaceService entity.
type WorkspaceServiceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkspaceServiceMutation
}

// SetName sets the "name" field.
func (_u *WorkspaceServiceUpdateOne) SetName(v string) *WorkspaceServiceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WorkspaceServiceUpdateOne) SetNillableName(v *string) *WorkspaceServiceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetConfigRevision sets the "config_revision" field.
func (_u *WorkspaceServiceUpdateOne) SetConfigRevision(v int64) *WorkspaceServiceUpdateOne {
	_u.mutation.ResetConfigRevision()
	_u.mutation.SetConfigRevision(v)
	return _u
}

// SetNillableConfigRevision sets the "config_revision" field if the given value is not nil.
func (_u *WorkspaceServiceUpdateOne) SetNillableConfigRevision(v *int64) *WorkspaceServiceUpdateOne {
	if v != nil {
		_u.SetConfigRevision(*v)
	}
	return _u
}

// AddConfigRevision adds value to the "config_revision" field.
func (_u *WorkspaceServiceUpdateOne) AddConfigRevision(v int64) *WorkspaceServiceUpdateOne {
	_u.mutation.AddConfigRevision(v)
	return _u
}

// SetActiveConfigRevision sets the "active_config_revision" field.
func (_u *WorkspaceServiceUpdateOne) SetActiveConfigRevision(v int64) *WorkspaceServiceUpdateOne {
	_u.mutation.ResetActiveConfigRevision()
	_u.mutation.SetActiveConfigRevision(v)
	return _u
}

// SetNillableActiveConfigRevision sets the "active_config_revision" field if the given value is not nil.
func (_u *WorkspaceServiceUpdateOne) SetNillableActiveConfigRevision(v *int64) *WorkspaceServiceUpdateOne {
	if v != nil {
		_u.SetActiveConfigRevision(*v)
	}
	return _u
}

// AddActiveConfigRevision adds value to the "active_config_revision" field.
func (_u *WorkspaceServiceUpdateOne) AddActiveConfigRevision(v int64) *WorkspaceServiceUpdateOne {
	_u.mutation.AddActiveConfigRevision(v)
	return _u
}

// ClearActiveConfigRevision clears the value of the "active_config_revision" field.
func (_u *WorkspaceServiceUpdateOne) ClearActiveConfigRevision() *WorkspaceServiceUpdateOne {
	_u.mutation.ClearActiveConfigRevision()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *WorkspaceServiceUpdateOne) SetEnabled(v bool) *WorkspaceServiceUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *WorkspaceServiceUpdateOne) SetNillableEnabled(v *bool) *WorkspaceServiceUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *WorkspaceServiceUpdateOne) SetState(v string) *WorkspaceServiceUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *WorkspaceServiceUpdateOne) SetNillableState(v *string) *WorkspaceServiceUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetDiagnosticCode sets the "diagnostic_code" field.
func (_u *WorkspaceServiceUpdateOne) SetDiagnosticCode(v string) *WorkspaceServiceUpdateOne {
	_u.mutation.SetDiagnosticCode(v)
	return _u
}

// SetNillableDiagnosticCode sets the "diagnostic_code" field if the given value is not nil.
func (_u *WorkspaceServiceUpdateOne) SetNillableDiagnosticCode(v *string) *WorkspaceServiceUpdateOne {
	if v != nil {
		_u.SetDiagnosticCode(*v)
	}
	return _u
}

// ClearDiagnosticCode clears the value of the "diagnostic_code" field.
func (_u *WorkspaceServiceUpdateOne) ClearDiagnosticCode() *WorkspaceServiceUpdateOne {
	_u.mutation.ClearDiagnosticCode()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *WorkspaceServiceUpdateOne) SetCreatedAt(v time.Time) *WorkspaceServiceUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *WorkspaceServiceUpdateOne) SetNillableCreatedAt(v *time.Time) *WorkspaceServiceUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkspaceServiceUpdateOne) SetUpdatedAt(v time.Time) *WorkspaceServiceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *WorkspaceServiceUpdateOne) SetNillableUpdatedAt(v *time.Time) *WorkspaceServiceUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the WorkspaceServiceMutation object of the builder.
func (_u *WorkspaceServiceUpdateOne) Mutation() *WorkspaceServiceMutation {
	return _u.mutation
}

// Where appends a list predicates to the WorkspaceServiceUpdate builder.
func (_u *WorkspaceServiceUpdateOne) Where(ps ...predicate.WorkspaceService) *WorkspaceServiceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkspaceServiceUpdateOne) Select(field string, fields ...string) *WorkspaceServiceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorkspaceService entity.
func (_u *WorkspaceServiceUpdateOne) Save(ctx context.Context) (*WorkspaceService, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkspaceServiceUpdateOne) SaveX(ctx context.Context) *WorkspaceService {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkspaceServiceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkspaceServiceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *WorkspaceServiceUpdateOne) sqlSave(ctx context.Context) (_node *WorkspaceService, err error) {
	_spec := sqlgraph.NewUpdateSpec(workspaceservice.Table, workspaceservice.Columns, sqlgraph.NewFieldSpec(workspaceservice.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkspaceService.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workspaceservice.FieldID)
		for _, f := range fields {
			if !workspaceservice.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workspaceservice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(workspaceservice.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConfigRevision(); ok {
		_spec.SetField(workspaceservice.FieldConfigRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedConfigRevision(); ok {
		_spec.AddField(workspaceservice.FieldConfigRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ActiveConfigRevision(); ok {
		_spec.SetField(workspaceservice.FieldActiveConfigRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedActiveConfigRevision(); ok {
		_spec.AddField(workspaceservice.FieldActiveConfigRevision, field.TypeInt64, value)
	}
	if _u.mutation.ActiveConfigRevisionCleared() {
		_spec.ClearField(workspaceservice.FieldActiveConfigRevision, field.TypeInt64)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(workspaceservice.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(workspaceservice.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.DiagnosticCode(); ok {
		_spec.SetField(workspaceservice.FieldDiagnosticCode, field.TypeString, value)
	}
	if _u.mutation.DiagnosticCodeCleared() {
		_spec.ClearField(workspaceservice.FieldDiagnosticCode, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(workspaceservice.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workspaceservice.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &WorkspaceService{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspaceservice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
