// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"measix/platform/ent/predicate"
	"measix/platform/ent/workspaceaudit"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkspaceAuditUpdate is the builder for updating WorkspaceAudit entities.
type WorkspaceAuditUpdate struct {
	config
	hooks    []Hook
	mutation *WorkspaceAuditMutation
}

// Where appends a list predicates to the WorkspaceAuditUpdate builder.
func (_u *WorkspaceAuditUpdate) Where(ps ...predicate.WorkspaceAudit) *WorkspaceAuditUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *WorkspaceAuditUpdate) SetRequestID(v string) *WorkspaceAuditUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *WorkspaceAuditUpdate) SetNillableRequestID(v *string) *WorkspaceAuditUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetActorID sets the "actor_id" field.
func (_u *WorkspaceAuditUpdate) SetActorID(v string) *WorkspaceAuditUpdate {
	_u.mutation.SetActorID(v)
	return _u
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_u *WorkspaceAuditUpdate) SetNillableActorID(v *string) *WorkspaceAuditUpdate {
	if v != nil {
		_u.SetActorID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *WorkspaceAuditUpdate) SetUserID(v string) *WorkspaceAuditUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *WorkspaceAuditUpdate) SetNillableUserID(v *string) *WorkspaceAuditUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAgentSpaceID sets the "agent_space_id" field.
func (_u *WorkspaceAuditUpdate) SetAgentSpaceID(v string) *WorkspaceAuditUpdate {
	_u.mutation.SetAgentSpaceID(v)
	return _u
}

// SetNillableAgentSpaceID sets the "agent_space_id" field if the given value is not nil.
func (_u *WorkspaceAuditUpdate) SetNillableAgentSpaceID(v *string) *WorkspaceAuditUpdate {
	if v != nil {
		_u.SetAgentSpaceID(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *WorkspaceAuditUpdate) SetAction(v string) *WorkspaceAuditUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *WorkspaceAuditUpdate) SetNillableAction(v *string) *WorkspaceAuditUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *WorkspaceAuditUpdate) SetPath(v string) *WorkspaceAuditUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *WorkspaceAuditUpdate) SetNillablePath(v *string) *WorkspaceAuditUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetOutcome sets the "outcome" field.
func (_u *WorkspaceAuditUpdate) SetOutcome(v string) *WorkspaceAuditUpdate {
	_u.mutation.SetOutcome(v)
	return _u
}

// SetNillableOutcome sets the "outcome" field if the given value is not nil.
func (_u *WorkspaceAuditUpdate) SetNillableOutcome(v *string) *WorkspaceAuditUpdate {
	if v != nil {
		_u.SetOutcome(*v)
	}
	return _u
}

// SetBytes sets the "bytes" field.
func (_u *WorkspaceAuditUpdate) SetBytes(v int64) *WorkspaceAuditUpdate {
	_u.mutation.ResetBytes()
	_u.mutation.SetBytes(v)
	return _u
}

// SetNillableBytes sets the "bytes" field if the given value is not nil.
func (_u *WorkspaceAuditUpdate) SetNillableBytes(v *int64) *WorkspaceAuditUpdate {
	if v != nil {
		_u.SetBytes(*v)
	}
	return _u
}

// AddBytes adds value to the "bytes" field.
func (_u *WorkspaceAuditUpdate) AddBytes(v int64) *WorkspaceAuditUpdate {
	_u.mutation.AddBytes(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *WorkspaceAuditUpdate) SetCreatedAt(v time.Time) *WorkspaceAuditUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *WorkspaceAuditUpdate) SetNillableCreatedAt(v *time.Time) *WorkspaceAuditUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *WorkspaceAuditUpdate) SetCompletedAt(v time.Time) *WorkspaceAuditUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *WorkspaceAuditUpdate) SetNillableCompletedAt(v *time.Time) *WorkspaceAuditUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *WorkspaceAuditUpdate) ClearCompletedAt() *WorkspaceAuditUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the WorkspaceAuditMutation object of the builder.
func (_u *WorkspaceAuditUpdate) Mutation() *WorkspaceAuditMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkspaceAuditUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkspaceAuditUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkspaceAuditUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkspaceAuditUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *WorkspaceAuditUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(workspaceaudit.Table, workspaceaudit.Columns, sqlgraph.NewFieldSpec(workspaceaudit.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(workspaceaudit.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActorID(); ok {
		_spec.SetField(workspaceaudit.FieldActorID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(workspaceaudit.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AgentSpaceID(); ok {
		_spec.SetField(workspaceaudit.FieldAgentSpaceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(workspaceaudit.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(workspaceaudit.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Outcome(); ok {
		_spec.SetField(workspaceaudit.FieldOutcome, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bytes(); ok {
		_spec.SetField(workspaceaudit.FieldBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBytes(); ok {
		_spec.AddField(workspaceaudit.FieldBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(workspaceaudit.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(workspaceaudit.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(workspaceaudit.FieldCompletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspaceaudit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkspaceAuditUpdateOne is the builder for updating a single WorkspaceAudit entity.
type WorkspaceAuditUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkspaceAuditMutation
}

// SetRequestID sets the "request_id" field.
func (_u *WorkspaceAuditUpdateOne) SetRequestID(v string) *WorkspaceAuditUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *WorkspaceAuditUpdateOne) SetNillableRequestID(v *string) *WorkspaceAuditUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetActorID sets the "actor_id" field.
func (_u *WorkspaceAuditUpdateOne) SetActorID(v string) *WorkspaceAuditUpdateOne {
	_u.mutation.SetActorID(v)
	return _u
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_u *WorkspaceAuditUpdateOne) SetNillableActorID(v *string) *WorkspaceAuditUpdateOne {
	if v != nil {
		_u.SetActorID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *WorkspaceAuditUpdateOne) SetUserID(v string) *WorkspaceAuditUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *WorkspaceAuditUpdateOne) SetNillableUserID(v *string) *WorkspaceAuditUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAgentSpaceID sets the "agent_space_id" field.
func (_u *WorkspaceAuditUpdateOne) SetAgentSpaceID(v string) *WorkspaceAuditUpdateOne {
	_u.mutation.SetAgentSpaceID(v)
	return _u
}

// SetNillableAgentSpaceID sets the "agent_space_id" field if the given value is not nil.
func (_u *WorkspaceAuditUpdateOne) SetNillableAgentSpaceID(v *string) *WorkspaceAuditUpdateOne {
	if v != nil {
		_u.SetAgentSpaceID(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *WorkspaceAuditUpdateOne) SetAction(v string) *WorkspaceAuditUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *WorkspaceAuditUpdateOne) SetNillableAction(v *string) *WorkspaceAuditUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *WorkspaceAuditUpdateOne) SetPath(v string) *WorkspaceAuditUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *WorkspaceAuditUpdateOne) SetNillablePath(v *string) *WorkspaceAuditUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetOutcome sets the "outcome" field.
func (_u *WorkspaceAuditUpdateOne) SetOutcome(v string) *WorkspaceAuditUpdateOne {
	_u.mutation.SetOutcome(v)
	return _u
}

// SetNillableOutcome sets the "outcome" field if the given value is not nil.
func (_u *WorkspaceAuditUpdateOne) SetNillableOutcome(v *string) *WorkspaceAuditUpdateOne {
	if v != nil {
		_u.SetOutcome(*v)
	}
	return _u
}

// SetBytes sets the "bytes" field.
func (_u *WorkspaceAuditUpdateOne) SetBytes(v int64) *WorkspaceAuditUpdateOne {
	_u.mutation.ResetBytes()
	_u.mutation.SetBytes(v)
	return _u
}

// SetNillableBytes sets the "bytes" field if the given value is not nil.
func (_u *WorkspaceAuditUpdateOne) SetNillableBytes(v *int64) *WorkspaceAuditUpdateOne {
	if v != nil {
		_u.SetBytes(*v)
	}
	return _u
}

// AddBytes adds value to the "bytes" field.
func (_u *WorkspaceAuditUpdateOne) AddBytes(v int64) *WorkspaceAuditUpdateOne {
	_u.mutation.AddBytes(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *WorkspaceAuditUpdateOne) SetCreatedAt(v time.Time) *WorkspaceAuditUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *WorkspaceAuditUpdateOne) SetNillableCreatedAt(v *time.Time) *WorkspaceAuditUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *WorkspaceAuditUpdateOne) SetCompletedAt(v time.Time) *WorkspaceAuditUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *WorkspaceAuditUpdateOne) SetNillableCompletedAt(v *time.Time) *WorkspaceAuditUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *WorkspaceAuditUpdateOne) ClearCompletedAt() *WorkspaceAuditUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the WorkspaceAuditMutation object of the builder.
func (_u *WorkspaceAuditUpdateOne) Mutation() *WorkspaceAuditMutation {
	return _u.mutation
}

// Where appends a list predicates to the WorkspaceAuditUpdate builder.
func (_u *WorkspaceAuditUpdateOne) Where(ps ...predicate.WorkspaceAudit) *WorkspaceAuditUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkspaceAuditUpdateOne) Select(field string, fields ...string) *WorkspaceAuditUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorkspaceAudit entity.
func (_u *WorkspaceAuditUpdateOne) Save(ctx context.Context) (*WorkspaceAudit, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkspaceAuditUpdateOne) SaveX(ctx context.Context) *WorkspaceAudit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkspaceAuditUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkspaceAuditUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *WorkspaceAuditUpdateOne) sqlSave(ctx context.Context) (_node *WorkspaceAudit, err error) {
	_spec := sqlgraph.NewUpdateSpec(workspaceaudit.Table, workspaceaudit.Columns, sqlgraph.NewFieldSpec(workspaceaudit.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkspaceAudit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workspaceaudit.FieldID)
		for _, f := range fields {
			if !workspaceaudit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workspaceaudit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(workspaceaudit.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActorID(); ok {
		_spec.SetField(workspaceaudit.FieldActorID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(workspaceaudit.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AgentSpaceID(); ok {
		_spec.SetField(workspaceaudit.FieldAgentSpaceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(workspaceaudit.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(workspaceaudit.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Outcome(); ok {
		_spec.SetField(workspaceaudit.FieldOutcome, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bytes(); ok {
		_spec.SetField(workspaceaudit.FieldBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBytes(); ok {
		_spec.AddField(workspaceaudit.FieldBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(workspaceaudit.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(workspaceaudit.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(workspaceaudit.FieldCompletedAt, field.TypeTime)
	}
	_node = &WorkspaceAudit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspaceaudit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
