// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"measix/platform/ent/predicate"
	"measix/platform/ent/workspaceserviceconfig"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkspaceServiceConfigDelete is the builder for deleting a WorkspaceServiceConfig entity.
type WorkspaceServiceConfigDelete struct {
	config
	hooks    []Hook
	mutation *WorkspaceServiceConfigMutation
}

// Where appends a list predicates to the WorkspaceServiceConfigDelete builder.
func (_d *WorkspaceServiceConfigDelete) Where(ps ...predicate.WorkspaceServiceConfig) *WorkspaceServiceConfigDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *WorkspaceServiceConfigDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *WorkspaceServiceConfigDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *WorkspaceServiceConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(workspaceserviceconfig.Table, sqlgraph.NewFieldSpec(workspaceserviceconfig.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// WorkspaceServiceConfigDeleteOne is the builder for deleting a single WorkspaceServiceConfig entity.
type WorkspaceServiceConfigDeleteOne struct {
	_d *WorkspaceServiceConfigDelete
}

// Where appends a list predicates to the WorkspaceServiceConfigDelete builder.
func (_d *WorkspaceServiceConfigDeleteOne) Where(ps ...predicate.WorkspaceServiceConfig) *WorkspaceServiceConfigDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *WorkspaceServiceConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{workspaceserviceconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *WorkspaceServiceConfigDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
