// Code generated by ent, DO NOT EDIT.

package pricingrule

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the pricingrule type in the database.
	Label = "pricing_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldResourceID holds the string denoting the resource_id field in the database.
	FieldResourceID = "resource_id"
	// FieldUpstreamID holds the string denoting the upstream_id field in the database.
	FieldUpstreamID = "upstream_id"
	// FieldMeter holds the string denoting the meter field in the database.
	FieldMeter = "meter"
	// FieldUnitSize holds the string denoting the unit_size field in the database.
	FieldUnitSize = "unit_size"
	// FieldUnitPriceDecimal holds the string denoting the unit_price_decimal field in the database.
	FieldUnitPriceDecimal = "unit_price_decimal"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldEffectiveFrom holds the string denoting the effective_from field in the database.
	FieldEffectiveFrom = "effective_from"
	// FieldEffectiveTo holds the string denoting the effective_to field in the database.
	FieldEffectiveTo = "effective_to"
	// Table holds the table name of the pricingrule in the database.
	Table = "pricing_rules"
)

// Columns holds all SQL columns for pricingrule fields.
var Columns = []string{
	FieldID,
	FieldResourceID,
	FieldUpstreamID,
	FieldMeter,
	FieldUnitSize,
	FieldUnitPriceDecimal,
	FieldCurrency,
	FieldEffectiveFrom,
	FieldEffectiveTo,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the PricingRule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByResourceID orders the results by the resource_id field.
func ByResourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceID, opts...).ToFunc()
}

// ByUpstreamID orders the results by the upstream_id field.
func ByUpstreamID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamID, opts...).ToFunc()
}

// ByMeter orders the results by the meter field.
func ByMeter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMeter, opts...).ToFunc()
}

// ByUnitSize orders the results by the unit_size field.
func ByUnitSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitSize, opts...).ToFunc()
}

// ByUnitPriceDecimal orders the results by the unit_price_decimal field.
func ByUnitPriceDecimal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitPriceDecimal, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByEffectiveFrom orders the results by the effective_from field.
func ByEffectiveFrom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectiveFrom, opts...).ToFunc()
}

// ByEffectiveTo orders the results by the effective_to field.
func ByEffectiveTo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectiveTo, opts...).ToFunc()
}
