// Code generated by ent, DO NOT EDIT.

package managedrelease

import (
	"measix/platform/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldContainsFold(FieldID, id))
}

// ManagedGeneration applies equality check predicate on the "managed_generation" field. It's identical to ManagedGenerationEQ.
func ManagedGeneration(v int64) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldEQ(FieldManagedGeneration, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldEQ(FieldStatus, v))
}

// ReleaseContentJSON applies equality check predicate on the "release_content_json" field. It's identical to ReleaseContentJSONEQ.
func ReleaseContentJSON(v []byte) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldEQ(FieldReleaseContentJSON, v))
}

// SnapshotSchemaVersion applies equality check predicate on the "snapshot_schema_version" field. It's identical to SnapshotSchemaVersionEQ.
func SnapshotSchemaVersion(v int) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldEQ(FieldSnapshotSchemaVersion, v))
}

// SnapshotJSON applies equality check predicate on the "snapshot_json" field. It's identical to SnapshotJSONEQ.
func SnapshotJSON(v []byte) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldEQ(FieldSnapshotJSON, v))
}

// SnapshotHash applies equality check predicate on the "snapshot_hash" field. It's identical to SnapshotHashEQ.
func SnapshotHash(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldEQ(FieldSnapshotHash, v))
}

// SourceDraftRevision applies equality check predicate on the "source_draft_revision" field. It's identical to SourceDraftRevisionEQ.
func SourceDraftRevision(v int64) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldEQ(FieldSourceDraftRevision, v))
}

// CreatedByUserID applies equality check predicate on the "created_by_user_id" field. It's identical to CreatedByUserIDEQ.
func CreatedByUserID(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldEQ(FieldCreatedByUserID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldEQ(FieldCreatedAt, v))
}

// ManagedGenerationEQ applies the EQ predicate on the "managed_generation" field.
func ManagedGenerationEQ(v int64) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldEQ(FieldManagedGeneration, v))
}

// ManagedGenerationNEQ applies the NEQ predicate on the "managed_generation" field.
func ManagedGenerationNEQ(v int64) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldNEQ(FieldManagedGeneration, v))
}

// ManagedGenerationIn applies the In predicate on the "managed_generation" field.
func ManagedGenerationIn(vs ...int64) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldIn(FieldManagedGeneration, vs...))
}

// ManagedGenerationNotIn applies the NotIn predicate on the "managed_generation" field.
func ManagedGenerationNotIn(vs ...int64) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldNotIn(FieldManagedGeneration, vs...))
}

// ManagedGenerationGT applies the GT predicate on the "managed_generation" field.
func ManagedGenerationGT(v int64) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldGT(FieldManagedGeneration, v))
}

// ManagedGenerationGTE applies the GTE predicate on the "managed_generation" field.
func ManagedGenerationGTE(v int64) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldGTE(FieldManagedGeneration, v))
}

// ManagedGenerationLT applies the LT predicate on the "managed_generation" field.
func ManagedGenerationLT(v int64) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldLT(FieldManagedGeneration, v))
}

// ManagedGenerationLTE applies the LTE predicate on the "managed_generation" field.
func ManagedGenerationLTE(v int64) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldLTE(FieldManagedGeneration, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldContainsFold(FieldStatus, v))
}

// ReleaseContentJSONEQ applies the EQ predicate on the "release_content_json" field.
func ReleaseContentJSONEQ(v []byte) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldEQ(FieldReleaseContentJSON, v))
}

// ReleaseContentJSONNEQ applies the NEQ predicate on the "release_content_json" field.
func ReleaseContentJSONNEQ(v []byte) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldNEQ(FieldReleaseContentJSON, v))
}

// ReleaseContentJSONIn applies the In predicate on the "release_content_json" field.
func ReleaseContentJSONIn(vs ...[]byte) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldIn(FieldReleaseContentJSON, vs...))
}

// ReleaseContentJSONNotIn applies the NotIn predicate on the "release_content_json" field.
func ReleaseContentJSONNotIn(vs ...[]byte) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldNotIn(FieldReleaseContentJSON, vs...))
}

// ReleaseContentJSONGT applies the GT predicate on the "release_content_json" field.
func ReleaseContentJSONGT(v []byte) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldGT(FieldReleaseContentJSON, v))
}

// ReleaseContentJSONGTE applies the GTE predicate on the "release_content_json" field.
func ReleaseContentJSONGTE(v []byte) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldGTE(FieldReleaseContentJSON, v))
}

// ReleaseContentJSONLT applies the LT predicate on the "release_content_json" field.
func ReleaseContentJSONLT(v []byte) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldLT(FieldReleaseContentJSON, v))
}

// ReleaseContentJSONLTE applies the LTE predicate on the "release_content_json" field.
func ReleaseContentJSONLTE(v []byte) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldLTE(FieldReleaseContentJSON, v))
}

// SnapshotSchemaVersionEQ applies the EQ predicate on the "snapshot_schema_version" field.
func SnapshotSchemaVersionEQ(v int) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldEQ(FieldSnapshotSchemaVersion, v))
}

// SnapshotSchemaVersionNEQ applies the NEQ predicate on the "snapshot_schema_version" field.
func SnapshotSchemaVersionNEQ(v int) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldNEQ(FieldSnapshotSchemaVersion, v))
}

// SnapshotSchemaVersionIn applies the In predicate on the "snapshot_schema_version" field.
func SnapshotSchemaVersionIn(vs ...int) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldIn(FieldSnapshotSchemaVersion, vs...))
}

// SnapshotSchemaVersionNotIn applies the NotIn predicate on the "snapshot_schema_version" field.
func SnapshotSchemaVersionNotIn(vs ...int) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldNotIn(FieldSnapshotSchemaVersion, vs...))
}

// SnapshotSchemaVersionGT applies the GT predicate on the "snapshot_schema_version" field.
func SnapshotSchemaVersionGT(v int) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldGT(FieldSnapshotSchemaVersion, v))
}

// SnapshotSchemaVersionGTE applies the GTE predicate on the "snapshot_schema_version" field.
func SnapshotSchemaVersionGTE(v int) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldGTE(FieldSnapshotSchemaVersion, v))
}

// SnapshotSchemaVersionLT applies the LT predicate on the "snapshot_schema_version" field.
func SnapshotSchemaVersionLT(v int) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldLT(FieldSnapshotSchemaVersion, v))
}

// SnapshotSchemaVersionLTE applies the LTE predicate on the "snapshot_schema_version" field.
func SnapshotSchemaVersionLTE(v int) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldLTE(FieldSnapshotSchemaVersion, v))
}

// SnapshotJSONEQ applies the EQ predicate on the "snapshot_json" field.
func SnapshotJSONEQ(v []byte) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldEQ(FieldSnapshotJSON, v))
}

// SnapshotJSONNEQ applies the NEQ predicate on the "snapshot_json" field.
func SnapshotJSONNEQ(v []byte) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldNEQ(FieldSnapshotJSON, v))
}

// SnapshotJSONIn applies the In predicate on the "snapshot_json" field.
func SnapshotJSONIn(vs ...[]byte) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldIn(FieldSnapshotJSON, vs...))
}

// SnapshotJSONNotIn applies the NotIn predicate on the "snapshot_json" field.
func SnapshotJSONNotIn(vs ...[]byte) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldNotIn(FieldSnapshotJSON, vs...))
}

// SnapshotJSONGT applies the GT predicate on the "snapshot_json" field.
func SnapshotJSONGT(v []byte) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldGT(FieldSnapshotJSON, v))
}

// SnapshotJSONGTE applies the GTE predicate on the "snapshot_json" field.
func SnapshotJSONGTE(v []byte) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldGTE(FieldSnapshotJSON, v))
}

// SnapshotJSONLT applies the LT predicate on the "snapshot_json" field.
func SnapshotJSONLT(v []byte) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldLT(FieldSnapshotJSON, v))
}

// SnapshotJSONLTE applies the LTE predicate on the "snapshot_json" field.
func SnapshotJSONLTE(v []byte) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldLTE(FieldSnapshotJSON, v))
}

// SnapshotHashEQ applies the EQ predicate on the "snapshot_hash" field.
func SnapshotHashEQ(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldEQ(FieldSnapshotHash, v))
}

// SnapshotHashNEQ applies the NEQ predicate on the "snapshot_hash" field.
func SnapshotHashNEQ(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldNEQ(FieldSnapshotHash, v))
}

// SnapshotHashIn applies the In predicate on the "snapshot_hash" field.
func SnapshotHashIn(vs ...string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldIn(FieldSnapshotHash, vs...))
}

// SnapshotHashNotIn applies the NotIn predicate on the "snapshot_hash" field.
func SnapshotHashNotIn(vs ...string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldNotIn(FieldSnapshotHash, vs...))
}

// SnapshotHashGT applies the GT predicate on the "snapshot_hash" field.
func SnapshotHashGT(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldGT(FieldSnapshotHash, v))
}

// SnapshotHashGTE applies the GTE predicate on the "snapshot_hash" field.
func SnapshotHashGTE(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldGTE(FieldSnapshotHash, v))
}

// SnapshotHashLT applies the LT predicate on the "snapshot_hash" field.
func SnapshotHashLT(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldLT(FieldSnapshotHash, v))
}

// SnapshotHashLTE applies the LTE predicate on the "snapshot_hash" field.
func SnapshotHashLTE(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldLTE(FieldSnapshotHash, v))
}

// SnapshotHashContains applies the Contains predicate on the "snapshot_hash" field.
func SnapshotHashContains(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldContains(FieldSnapshotHash, v))
}

// SnapshotHashHasPrefix applies the HasPrefix predicate on the "snapshot_hash" field.
func SnapshotHashHasPrefix(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldHasPrefix(FieldSnapshotHash, v))
}

// SnapshotHashHasSuffix applies the HasSuffix predicate on the "snapshot_hash" field.
func SnapshotHashHasSuffix(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldHasSuffix(FieldSnapshotHash, v))
}

// SnapshotHashEqualFold applies the EqualFold predicate on the "snapshot_hash" field.
func SnapshotHashEqualFold(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldEqualFold(FieldSnapshotHash, v))
}

// SnapshotHashContainsFold applies the ContainsFold predicate on the "snapshot_hash" field.
func SnapshotHashContainsFold(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldContainsFold(FieldSnapshotHash, v))
}

// SourceDraftRevisionEQ applies the EQ predicate on the "source_draft_revision" field.
func SourceDraftRevisionEQ(v int64) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldEQ(FieldSourceDraftRevision, v))
}

// SourceDraftRevisionNEQ applies the NEQ predicate on the "source_draft_revision" field.
func SourceDraftRevisionNEQ(v int64) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldNEQ(FieldSourceDraftRevision, v))
}

// SourceDraftRevisionIn applies the In predicate on the "source_draft_revision" field.
func SourceDraftRevisionIn(vs ...int64) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldIn(FieldSourceDraftRevision, vs...))
}

// SourceDraftRevisionNotIn applies the NotIn predicate on the "source_draft_revision" field.
func SourceDraftRevisionNotIn(vs ...int64) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldNotIn(FieldSourceDraftRevision, vs...))
}

// SourceDraftRevisionGT applies the GT predicate on the "source_draft_revision" field.
func SourceDraftRevisionGT(v int64) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldGT(FieldSourceDraftRevision, v))
}

// SourceDraftRevisionGTE applies the GTE predicate on the "source_draft_revision" field.
func SourceDraftRevisionGTE(v int64) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldGTE(FieldSourceDraftRevision, v))
}

// SourceDraftRevisionLT applies the LT predicate on the "source_draft_revision" field.
func SourceDraftRevisionLT(v int64) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldLT(FieldSourceDraftRevision, v))
}

// SourceDraftRevisionLTE applies the LTE predicate on the "source_draft_revision" field.
func SourceDraftRevisionLTE(v int64) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldLTE(FieldSourceDraftRevision, v))
}

// CreatedByUserIDEQ applies the EQ predicate on the "created_by_user_id" field.
func CreatedByUserIDEQ(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldEQ(FieldCreatedByUserID, v))
}

// CreatedByUserIDNEQ applies the NEQ predicate on the "created_by_user_id" field.
func CreatedByUserIDNEQ(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldNEQ(FieldCreatedByUserID, v))
}

// CreatedByUserIDIn applies the In predicate on the "created_by_user_id" field.
func CreatedByUserIDIn(vs ...string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldIn(FieldCreatedByUserID, vs...))
}

// CreatedByUserIDNotIn applies the NotIn predicate on the "created_by_user_id" field.
func CreatedByUserIDNotIn(vs ...string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldNotIn(FieldCreatedByUserID, vs...))
}

// CreatedByUserIDGT applies the GT predicate on the "created_by_user_id" field.
func CreatedByUserIDGT(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldGT(FieldCreatedByUserID, v))
}

// CreatedByUserIDGTE applies the GTE predicate on the "created_by_user_id" field.
func CreatedByUserIDGTE(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldGTE(FieldCreatedByUserID, v))
}

// CreatedByUserIDLT applies the LT predicate on the "created_by_user_id" field.
func CreatedByUserIDLT(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldLT(FieldCreatedByUserID, v))
}

// CreatedByUserIDLTE applies the LTE predicate on the "created_by_user_id" field.
func CreatedByUserIDLTE(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldLTE(FieldCreatedByUserID, v))
}

// CreatedByUserIDContains applies the Contains predicate on the "created_by_user_id" field.
func CreatedByUserIDContains(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldContains(FieldCreatedByUserID, v))
}

// CreatedByUserIDHasPrefix applies the HasPrefix predicate on the "created_by_user_id" field.
func CreatedByUserIDHasPrefix(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldHasPrefix(FieldCreatedByUserID, v))
}

// CreatedByUserIDHasSuffix applies the HasSuffix predicate on the "created_by_user_id" field.
func CreatedByUserIDHasSuffix(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldHasSuffix(FieldCreatedByUserID, v))
}

// CreatedByUserIDEqualFold applies the EqualFold predicate on the "created_by_user_id" field.
func CreatedByUserIDEqualFold(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldEqualFold(FieldCreatedByUserID, v))
}

// CreatedByUserIDContainsFold applies the ContainsFold predicate on the "created_by_user_id" field.
func CreatedByUserIDContainsFold(v string) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldContainsFold(FieldCreatedByUserID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ManagedRelease) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ManagedRelease) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ManagedRelease) predicate.ManagedRelease {
	return predicate.ManagedRelease(sql.NotPredicates(p))
}
