// Code generated by ent, DO NOT EDIT.

package budgetrequest

import (
	"measix/platform/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldContainsFold(FieldID, id))
}

// RequestHash applies equality check predicate on the "request_hash" field. It's identical to RequestHashEQ.
func RequestHash(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldRequestHash, v))
}

// DeploymentID applies equality check predicate on the "deployment_id" field. It's identical to DeploymentIDEQ.
func DeploymentID(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldDeploymentID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldUserID, v))
}

// InteractionID applies equality check predicate on the "interaction_id" field. It's identical to InteractionIDEQ.
func InteractionID(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldInteractionID, v))
}

// DeviceID applies equality check predicate on the "device_id" field. It's identical to DeviceIDEQ.
func DeviceID(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldDeviceID, v))
}

// ResourceID applies equality check predicate on the "resource_id" field. It's identical to ResourceIDEQ.
func ResourceID(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldResourceID, v))
}

// ClientProtocol applies equality check predicate on the "client_protocol" field. It's identical to ClientProtocolEQ.
func ClientProtocol(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldClientProtocol, v))
}

// UpstreamID applies equality check predicate on the "upstream_id" field. It's identical to UpstreamIDEQ.
func UpstreamID(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldUpstreamID, v))
}

// ManagedGeneration applies equality check predicate on the "managed_generation" field. It's identical to ManagedGenerationEQ.
func ManagedGeneration(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldManagedGeneration, v))
}

// ControlRevision applies equality check predicate on the "control_revision" field. It's identical to ControlRevisionEQ.
func ControlRevision(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldControlRevision, v))
}

// UserBudgetID applies equality check predicate on the "user_budget_id" field. It's identical to UserBudgetIDEQ.
func UserBudgetID(v int) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldUserBudgetID, v))
}

// BudgetRevision applies equality check predicate on the "budget_revision" field. It's identical to BudgetRevisionEQ.
func BudgetRevision(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldBudgetRevision, v))
}

// DecisionJSON applies equality check predicate on the "decision_json" field. It's identical to DecisionJSONEQ.
func DecisionJSON(v []byte) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldDecisionJSON, v))
}

// AdmittedAt applies equality check predicate on the "admitted_at" field. It's identical to AdmittedAtEQ.
func AdmittedAt(v time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldAdmittedAt, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldStartedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldCompletedAt, v))
}

// LastSettlementRevision applies equality check predicate on the "last_settlement_revision" field. It's identical to LastSettlementRevisionEQ.
func LastSettlementRevision(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldLastSettlementRevision, v))
}

// LastLifecycleRevision applies equality check predicate on the "last_lifecycle_revision" field. It's identical to LastLifecycleRevisionEQ.
func LastLifecycleRevision(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldLastLifecycleRevision, v))
}

// LastLifecycleHash applies equality check predicate on the "last_lifecycle_hash" field. It's identical to LastLifecycleHashEQ.
func LastLifecycleHash(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldLastLifecycleHash, v))
}

// TerminalReason applies equality check predicate on the "terminal_reason" field. It's identical to TerminalReasonEQ.
func TerminalReason(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldTerminalReason, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldUpdatedAt, v))
}

// RequestHashEQ applies the EQ predicate on the "request_hash" field.
func RequestHashEQ(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldRequestHash, v))
}

// RequestHashNEQ applies the NEQ predicate on the "request_hash" field.
func RequestHashNEQ(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNEQ(FieldRequestHash, v))
}

// RequestHashIn applies the In predicate on the "request_hash" field.
func RequestHashIn(vs ...string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIn(FieldRequestHash, vs...))
}

// RequestHashNotIn applies the NotIn predicate on the "request_hash" field.
func RequestHashNotIn(vs ...string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotIn(FieldRequestHash, vs...))
}

// RequestHashGT applies the GT predicate on the "request_hash" field.
func RequestHashGT(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGT(FieldRequestHash, v))
}

// RequestHashGTE applies the GTE predicate on the "request_hash" field.
func RequestHashGTE(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGTE(FieldRequestHash, v))
}

// RequestHashLT applies the LT predicate on the "request_hash" field.
func RequestHashLT(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLT(FieldRequestHash, v))
}

// RequestHashLTE applies the LTE predicate on the "request_hash" field.
func RequestHashLTE(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLTE(FieldRequestHash, v))
}

// RequestHashContains applies the Contains predicate on the "request_hash" field.
func RequestHashContains(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldContains(FieldRequestHash, v))
}

// RequestHashHasPrefix applies the HasPrefix predicate on the "request_hash" field.
func RequestHashHasPrefix(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldHasPrefix(FieldRequestHash, v))
}

// RequestHashHasSuffix applies the HasSuffix predicate on the "request_hash" field.
func RequestHashHasSuffix(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldHasSuffix(FieldRequestHash, v))
}

// RequestHashEqualFold applies the EqualFold predicate on the "request_hash" field.
func RequestHashEqualFold(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEqualFold(FieldRequestHash, v))
}

// RequestHashContainsFold applies the ContainsFold predicate on the "request_hash" field.
func RequestHashContainsFold(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldContainsFold(FieldRequestHash, v))
}

// DeploymentIDEQ applies the EQ predicate on the "deployment_id" field.
func DeploymentIDEQ(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldDeploymentID, v))
}

// DeploymentIDNEQ applies the NEQ predicate on the "deployment_id" field.
func DeploymentIDNEQ(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNEQ(FieldDeploymentID, v))
}

// DeploymentIDIn applies the In predicate on the "deployment_id" field.
func DeploymentIDIn(vs ...string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIn(FieldDeploymentID, vs...))
}

// DeploymentIDNotIn applies the NotIn predicate on the "deployment_id" field.
func DeploymentIDNotIn(vs ...string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotIn(FieldDeploymentID, vs...))
}

// DeploymentIDGT applies the GT predicate on the "deployment_id" field.
func DeploymentIDGT(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGT(FieldDeploymentID, v))
}

// DeploymentIDGTE applies the GTE predicate on the "deployment_id" field.
func DeploymentIDGTE(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGTE(FieldDeploymentID, v))
}

// DeploymentIDLT applies the LT predicate on the "deployment_id" field.
func DeploymentIDLT(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLT(FieldDeploymentID, v))
}

// DeploymentIDLTE applies the LTE predicate on the "deployment_id" field.
func DeploymentIDLTE(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLTE(FieldDeploymentID, v))
}

// DeploymentIDContains applies the Contains predicate on the "deployment_id" field.
func DeploymentIDContains(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldContains(FieldDeploymentID, v))
}

// DeploymentIDHasPrefix applies the HasPrefix predicate on the "deployment_id" field.
func DeploymentIDHasPrefix(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldHasPrefix(FieldDeploymentID, v))
}

// DeploymentIDHasSuffix applies the HasSuffix predicate on the "deployment_id" field.
func DeploymentIDHasSuffix(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldHasSuffix(FieldDeploymentID, v))
}

// DeploymentIDEqualFold applies the EqualFold predicate on the "deployment_id" field.
func DeploymentIDEqualFold(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEqualFold(FieldDeploymentID, v))
}

// DeploymentIDContainsFold applies the ContainsFold predicate on the "deployment_id" field.
func DeploymentIDContainsFold(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldContainsFold(FieldDeploymentID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldContainsFold(FieldUserID, v))
}

// InteractionIDEQ applies the EQ predicate on the "interaction_id" field.
func InteractionIDEQ(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldInteractionID, v))
}

// InteractionIDNEQ applies the NEQ predicate on the "interaction_id" field.
func InteractionIDNEQ(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNEQ(FieldInteractionID, v))
}

// InteractionIDIn applies the In predicate on the "interaction_id" field.
func InteractionIDIn(vs ...string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIn(FieldInteractionID, vs...))
}

// InteractionIDNotIn applies the NotIn predicate on the "interaction_id" field.
func InteractionIDNotIn(vs ...string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotIn(FieldInteractionID, vs...))
}

// InteractionIDGT applies the GT predicate on the "interaction_id" field.
func InteractionIDGT(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGT(FieldInteractionID, v))
}

// InteractionIDGTE applies the GTE predicate on the "interaction_id" field.
func InteractionIDGTE(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGTE(FieldInteractionID, v))
}

// InteractionIDLT applies the LT predicate on the "interaction_id" field.
func InteractionIDLT(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLT(FieldInteractionID, v))
}

// InteractionIDLTE applies the LTE predicate on the "interaction_id" field.
func InteractionIDLTE(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLTE(FieldInteractionID, v))
}

// InteractionIDContains applies the Contains predicate on the "interaction_id" field.
func InteractionIDContains(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldContains(FieldInteractionID, v))
}

// InteractionIDHasPrefix applies the HasPrefix predicate on the "interaction_id" field.
func InteractionIDHasPrefix(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldHasPrefix(FieldInteractionID, v))
}

// InteractionIDHasSuffix applies the HasSuffix predicate on the "interaction_id" field.
func InteractionIDHasSuffix(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldHasSuffix(FieldInteractionID, v))
}

// InteractionIDIsNil applies the IsNil predicate on the "interaction_id" field.
func InteractionIDIsNil() predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIsNull(FieldInteractionID))
}

// InteractionIDNotNil applies the NotNil predicate on the "interaction_id" field.
func InteractionIDNotNil() predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotNull(FieldInteractionID))
}

// InteractionIDEqualFold applies the EqualFold predicate on the "interaction_id" field.
func InteractionIDEqualFold(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEqualFold(FieldInteractionID, v))
}

// InteractionIDContainsFold applies the ContainsFold predicate on the "interaction_id" field.
func InteractionIDContainsFold(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldContainsFold(FieldInteractionID, v))
}

// DeviceIDEQ applies the EQ predicate on the "device_id" field.
func DeviceIDEQ(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldDeviceID, v))
}

// DeviceIDNEQ applies the NEQ predicate on the "device_id" field.
func DeviceIDNEQ(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNEQ(FieldDeviceID, v))
}

// DeviceIDIn applies the In predicate on the "device_id" field.
func DeviceIDIn(vs ...string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIn(FieldDeviceID, vs...))
}

// DeviceIDNotIn applies the NotIn predicate on the "device_id" field.
func DeviceIDNotIn(vs ...string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotIn(FieldDeviceID, vs...))
}

// DeviceIDGT applies the GT predicate on the "device_id" field.
func DeviceIDGT(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGT(FieldDeviceID, v))
}

// DeviceIDGTE applies the GTE predicate on the "device_id" field.
func DeviceIDGTE(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGTE(FieldDeviceID, v))
}

// DeviceIDLT applies the LT predicate on the "device_id" field.
func DeviceIDLT(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLT(FieldDeviceID, v))
}

// DeviceIDLTE applies the LTE predicate on the "device_id" field.
func DeviceIDLTE(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLTE(FieldDeviceID, v))
}

// DeviceIDContains applies the Contains predicate on the "device_id" field.
func DeviceIDContains(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldContains(FieldDeviceID, v))
}

// DeviceIDHasPrefix applies the HasPrefix predicate on the "device_id" field.
func DeviceIDHasPrefix(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldHasPrefix(FieldDeviceID, v))
}

// DeviceIDHasSuffix applies the HasSuffix predicate on the "device_id" field.
func DeviceIDHasSuffix(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldHasSuffix(FieldDeviceID, v))
}

// DeviceIDIsNil applies the IsNil predicate on the "device_id" field.
func DeviceIDIsNil() predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIsNull(FieldDeviceID))
}

// DeviceIDNotNil applies the NotNil predicate on the "device_id" field.
func DeviceIDNotNil() predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotNull(FieldDeviceID))
}

// DeviceIDEqualFold applies the EqualFold predicate on the "device_id" field.
func DeviceIDEqualFold(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEqualFold(FieldDeviceID, v))
}

// DeviceIDContainsFold applies the ContainsFold predicate on the "device_id" field.
func DeviceIDContainsFold(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldContainsFold(FieldDeviceID, v))
}

// CapabilityEQ applies the EQ predicate on the "capability" field.
func CapabilityEQ(v Capability) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldCapability, v))
}

// CapabilityNEQ applies the NEQ predicate on the "capability" field.
func CapabilityNEQ(v Capability) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNEQ(FieldCapability, v))
}

// CapabilityIn applies the In predicate on the "capability" field.
func CapabilityIn(vs ...Capability) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIn(FieldCapability, vs...))
}

// CapabilityNotIn applies the NotIn predicate on the "capability" field.
func CapabilityNotIn(vs ...Capability) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotIn(FieldCapability, vs...))
}

// ResourceIDEQ applies the EQ predicate on the "resource_id" field.
func ResourceIDEQ(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldResourceID, v))
}

// ResourceIDNEQ applies the NEQ predicate on the "resource_id" field.
func ResourceIDNEQ(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNEQ(FieldResourceID, v))
}

// ResourceIDIn applies the In predicate on the "resource_id" field.
func ResourceIDIn(vs ...string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIn(FieldResourceID, vs...))
}

// ResourceIDNotIn applies the NotIn predicate on the "resource_id" field.
func ResourceIDNotIn(vs ...string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotIn(FieldResourceID, vs...))
}

// ResourceIDGT applies the GT predicate on the "resource_id" field.
func ResourceIDGT(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGT(FieldResourceID, v))
}

// ResourceIDGTE applies the GTE predicate on the "resource_id" field.
func ResourceIDGTE(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGTE(FieldResourceID, v))
}

// ResourceIDLT applies the LT predicate on the "resource_id" field.
func ResourceIDLT(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLT(FieldResourceID, v))
}

// ResourceIDLTE applies the LTE predicate on the "resource_id" field.
func ResourceIDLTE(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLTE(FieldResourceID, v))
}

// ResourceIDContains applies the Contains predicate on the "resource_id" field.
func ResourceIDContains(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldContains(FieldResourceID, v))
}

// ResourceIDHasPrefix applies the HasPrefix predicate on the "resource_id" field.
func ResourceIDHasPrefix(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldHasPrefix(FieldResourceID, v))
}

// ResourceIDHasSuffix applies the HasSuffix predicate on the "resource_id" field.
func ResourceIDHasSuffix(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldHasSuffix(FieldResourceID, v))
}

// ResourceIDEqualFold applies the EqualFold predicate on the "resource_id" field.
func ResourceIDEqualFold(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEqualFold(FieldResourceID, v))
}

// ResourceIDContainsFold applies the ContainsFold predicate on the "resource_id" field.
func ResourceIDContainsFold(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldContainsFold(FieldResourceID, v))
}

// ClientProtocolEQ applies the EQ predicate on the "client_protocol" field.
func ClientProtocolEQ(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldClientProtocol, v))
}

// ClientProtocolNEQ applies the NEQ predicate on the "client_protocol" field.
func ClientProtocolNEQ(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNEQ(FieldClientProtocol, v))
}

// ClientProtocolIn applies the In predicate on the "client_protocol" field.
func ClientProtocolIn(vs ...string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIn(FieldClientProtocol, vs...))
}

// ClientProtocolNotIn applies the NotIn predicate on the "client_protocol" field.
func ClientProtocolNotIn(vs ...string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotIn(FieldClientProtocol, vs...))
}

// ClientProtocolGT applies the GT predicate on the "client_protocol" field.
func ClientProtocolGT(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGT(FieldClientProtocol, v))
}

// ClientProtocolGTE applies the GTE predicate on the "client_protocol" field.
func ClientProtocolGTE(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGTE(FieldClientProtocol, v))
}

// ClientProtocolLT applies the LT predicate on the "client_protocol" field.
func ClientProtocolLT(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLT(FieldClientProtocol, v))
}

// ClientProtocolLTE applies the LTE predicate on the "client_protocol" field.
func ClientProtocolLTE(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLTE(FieldClientProtocol, v))
}

// ClientProtocolContains applies the Contains predicate on the "client_protocol" field.
func ClientProtocolContains(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldContains(FieldClientProtocol, v))
}

// ClientProtocolHasPrefix applies the HasPrefix predicate on the "client_protocol" field.
func ClientProtocolHasPrefix(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldHasPrefix(FieldClientProtocol, v))
}

// ClientProtocolHasSuffix applies the HasSuffix predicate on the "client_protocol" field.
func ClientProtocolHasSuffix(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldHasSuffix(FieldClientProtocol, v))
}

// ClientProtocolEqualFold applies the EqualFold predicate on the "client_protocol" field.
func ClientProtocolEqualFold(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEqualFold(FieldClientProtocol, v))
}

// ClientProtocolContainsFold applies the ContainsFold predicate on the "client_protocol" field.
func ClientProtocolContainsFold(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldContainsFold(FieldClientProtocol, v))
}

// UpstreamIDEQ applies the EQ predicate on the "upstream_id" field.
func UpstreamIDEQ(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldUpstreamID, v))
}

// UpstreamIDNEQ applies the NEQ predicate on the "upstream_id" field.
func UpstreamIDNEQ(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNEQ(FieldUpstreamID, v))
}

// UpstreamIDIn applies the In predicate on the "upstream_id" field.
func UpstreamIDIn(vs ...string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIn(FieldUpstreamID, vs...))
}

// UpstreamIDNotIn applies the NotIn predicate on the "upstream_id" field.
func UpstreamIDNotIn(vs ...string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotIn(FieldUpstreamID, vs...))
}

// UpstreamIDGT applies the GT predicate on the "upstream_id" field.
func UpstreamIDGT(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGT(FieldUpstreamID, v))
}

// UpstreamIDGTE applies the GTE predicate on the "upstream_id" field.
func UpstreamIDGTE(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGTE(FieldUpstreamID, v))
}

// UpstreamIDLT applies the LT predicate on the "upstream_id" field.
func UpstreamIDLT(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLT(FieldUpstreamID, v))
}

// UpstreamIDLTE applies the LTE predicate on the "upstream_id" field.
func UpstreamIDLTE(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLTE(FieldUpstreamID, v))
}

// UpstreamIDContains applies the Contains predicate on the "upstream_id" field.
func UpstreamIDContains(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldContains(FieldUpstreamID, v))
}

// UpstreamIDHasPrefix applies the HasPrefix predicate on the "upstream_id" field.
func UpstreamIDHasPrefix(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldHasPrefix(FieldUpstreamID, v))
}

// UpstreamIDHasSuffix applies the HasSuffix predicate on the "upstream_id" field.
func UpstreamIDHasSuffix(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldHasSuffix(FieldUpstreamID, v))
}

// UpstreamIDEqualFold applies the EqualFold predicate on the "upstream_id" field.
func UpstreamIDEqualFold(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEqualFold(FieldUpstreamID, v))
}

// UpstreamIDContainsFold applies the ContainsFold predicate on the "upstream_id" field.
func UpstreamIDContainsFold(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldContainsFold(FieldUpstreamID, v))
}

// ManagedGenerationEQ applies the EQ predicate on the "managed_generation" field.
func ManagedGenerationEQ(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldManagedGeneration, v))
}

// ManagedGenerationNEQ applies the NEQ predicate on the "managed_generation" field.
func ManagedGenerationNEQ(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNEQ(FieldManagedGeneration, v))
}

// ManagedGenerationIn applies the In predicate on the "managed_generation" field.
func ManagedGenerationIn(vs ...int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIn(FieldManagedGeneration, vs...))
}

// ManagedGenerationNotIn applies the NotIn predicate on the "managed_generation" field.
func ManagedGenerationNotIn(vs ...int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotIn(FieldManagedGeneration, vs...))
}

// ManagedGenerationGT applies the GT predicate on the "managed_generation" field.
func ManagedGenerationGT(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGT(FieldManagedGeneration, v))
}

// ManagedGenerationGTE applies the GTE predicate on the "managed_generation" field.
func ManagedGenerationGTE(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGTE(FieldManagedGeneration, v))
}

// ManagedGenerationLT applies the LT predicate on the "managed_generation" field.
func ManagedGenerationLT(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLT(FieldManagedGeneration, v))
}

// ManagedGenerationLTE applies the LTE predicate on the "managed_generation" field.
func ManagedGenerationLTE(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLTE(FieldManagedGeneration, v))
}

// ControlRevisionEQ applies the EQ predicate on the "control_revision" field.
func ControlRevisionEQ(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldControlRevision, v))
}

// ControlRevisionNEQ applies the NEQ predicate on the "control_revision" field.
func ControlRevisionNEQ(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNEQ(FieldControlRevision, v))
}

// ControlRevisionIn applies the In predicate on the "control_revision" field.
func ControlRevisionIn(vs ...int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIn(FieldControlRevision, vs...))
}

// ControlRevisionNotIn applies the NotIn predicate on the "control_revision" field.
func ControlRevisionNotIn(vs ...int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotIn(FieldControlRevision, vs...))
}

// ControlRevisionGT applies the GT predicate on the "control_revision" field.
func ControlRevisionGT(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGT(FieldControlRevision, v))
}

// ControlRevisionGTE applies the GTE predicate on the "control_revision" field.
func ControlRevisionGTE(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGTE(FieldControlRevision, v))
}

// ControlRevisionLT applies the LT predicate on the "control_revision" field.
func ControlRevisionLT(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLT(FieldControlRevision, v))
}

// ControlRevisionLTE applies the LTE predicate on the "control_revision" field.
func ControlRevisionLTE(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLTE(FieldControlRevision, v))
}

// UserBudgetIDEQ applies the EQ predicate on the "user_budget_id" field.
func UserBudgetIDEQ(v int) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldUserBudgetID, v))
}

// UserBudgetIDNEQ applies the NEQ predicate on the "user_budget_id" field.
func UserBudgetIDNEQ(v int) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNEQ(FieldUserBudgetID, v))
}

// UserBudgetIDIn applies the In predicate on the "user_budget_id" field.
func UserBudgetIDIn(vs ...int) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIn(FieldUserBudgetID, vs...))
}

// UserBudgetIDNotIn applies the NotIn predicate on the "user_budget_id" field.
func UserBudgetIDNotIn(vs ...int) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotIn(FieldUserBudgetID, vs...))
}

// UserBudgetIDGT applies the GT predicate on the "user_budget_id" field.
func UserBudgetIDGT(v int) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGT(FieldUserBudgetID, v))
}

// UserBudgetIDGTE applies the GTE predicate on the "user_budget_id" field.
func UserBudgetIDGTE(v int) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGTE(FieldUserBudgetID, v))
}

// UserBudgetIDLT applies the LT predicate on the "user_budget_id" field.
func UserBudgetIDLT(v int) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLT(FieldUserBudgetID, v))
}

// UserBudgetIDLTE applies the LTE predicate on the "user_budget_id" field.
func UserBudgetIDLTE(v int) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLTE(FieldUserBudgetID, v))
}

// UserBudgetIDIsNil applies the IsNil predicate on the "user_budget_id" field.
func UserBudgetIDIsNil() predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIsNull(FieldUserBudgetID))
}

// UserBudgetIDNotNil applies the NotNil predicate on the "user_budget_id" field.
func UserBudgetIDNotNil() predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotNull(FieldUserBudgetID))
}

// BudgetRevisionEQ applies the EQ predicate on the "budget_revision" field.
func BudgetRevisionEQ(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldBudgetRevision, v))
}

// BudgetRevisionNEQ applies the NEQ predicate on the "budget_revision" field.
func BudgetRevisionNEQ(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNEQ(FieldBudgetRevision, v))
}

// BudgetRevisionIn applies the In predicate on the "budget_revision" field.
func BudgetRevisionIn(vs ...int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIn(FieldBudgetRevision, vs...))
}

// BudgetRevisionNotIn applies the NotIn predicate on the "budget_revision" field.
func BudgetRevisionNotIn(vs ...int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotIn(FieldBudgetRevision, vs...))
}

// BudgetRevisionGT applies the GT predicate on the "budget_revision" field.
func BudgetRevisionGT(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGT(FieldBudgetRevision, v))
}

// BudgetRevisionGTE applies the GTE predicate on the "budget_revision" field.
func BudgetRevisionGTE(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGTE(FieldBudgetRevision, v))
}

// BudgetRevisionLT applies the LT predicate on the "budget_revision" field.
func BudgetRevisionLT(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLT(FieldBudgetRevision, v))
}

// BudgetRevisionLTE applies the LTE predicate on the "budget_revision" field.
func BudgetRevisionLTE(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLTE(FieldBudgetRevision, v))
}

// ModeEQ applies the EQ predicate on the "mode" field.
func ModeEQ(v Mode) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldMode, v))
}

// ModeNEQ applies the NEQ predicate on the "mode" field.
func ModeNEQ(v Mode) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNEQ(FieldMode, v))
}

// ModeIn applies the In predicate on the "mode" field.
func ModeIn(vs ...Mode) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIn(FieldMode, vs...))
}

// ModeNotIn applies the NotIn predicate on the "mode" field.
func ModeNotIn(vs ...Mode) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotIn(FieldMode, vs...))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v Source) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v Source) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...Source) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...Source) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotIn(FieldSource, vs...))
}

// DecisionJSONEQ applies the EQ predicate on the "decision_json" field.
func DecisionJSONEQ(v []byte) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldDecisionJSON, v))
}

// DecisionJSONNEQ applies the NEQ predicate on the "decision_json" field.
func DecisionJSONNEQ(v []byte) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNEQ(FieldDecisionJSON, v))
}

// DecisionJSONIn applies the In predicate on the "decision_json" field.
func DecisionJSONIn(vs ...[]byte) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIn(FieldDecisionJSON, vs...))
}

// DecisionJSONNotIn applies the NotIn predicate on the "decision_json" field.
func DecisionJSONNotIn(vs ...[]byte) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotIn(FieldDecisionJSON, vs...))
}

// DecisionJSONGT applies the GT predicate on the "decision_json" field.
func DecisionJSONGT(v []byte) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGT(FieldDecisionJSON, v))
}

// DecisionJSONGTE applies the GTE predicate on the "decision_json" field.
func DecisionJSONGTE(v []byte) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGTE(FieldDecisionJSON, v))
}

// DecisionJSONLT applies the LT predicate on the "decision_json" field.
func DecisionJSONLT(v []byte) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLT(FieldDecisionJSON, v))
}

// DecisionJSONLTE applies the LTE predicate on the "decision_json" field.
func DecisionJSONLTE(v []byte) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLTE(FieldDecisionJSON, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v State) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v State) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...State) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...State) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotIn(FieldState, vs...))
}

// AdmittedAtEQ applies the EQ predicate on the "admitted_at" field.
func AdmittedAtEQ(v time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldAdmittedAt, v))
}

// AdmittedAtNEQ applies the NEQ predicate on the "admitted_at" field.
func AdmittedAtNEQ(v time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNEQ(FieldAdmittedAt, v))
}

// AdmittedAtIn applies the In predicate on the "admitted_at" field.
func AdmittedAtIn(vs ...time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIn(FieldAdmittedAt, vs...))
}

// AdmittedAtNotIn applies the NotIn predicate on the "admitted_at" field.
func AdmittedAtNotIn(vs ...time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotIn(FieldAdmittedAt, vs...))
}

// AdmittedAtGT applies the GT predicate on the "admitted_at" field.
func AdmittedAtGT(v time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGT(FieldAdmittedAt, v))
}

// AdmittedAtGTE applies the GTE predicate on the "admitted_at" field.
func AdmittedAtGTE(v time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGTE(FieldAdmittedAt, v))
}

// AdmittedAtLT applies the LT predicate on the "admitted_at" field.
func AdmittedAtLT(v time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLT(FieldAdmittedAt, v))
}

// AdmittedAtLTE applies the LTE predicate on the "admitted_at" field.
func AdmittedAtLTE(v time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLTE(FieldAdmittedAt, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotNull(FieldStartedAt))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotNull(FieldCompletedAt))
}

// LastSettlementRevisionEQ applies the EQ predicate on the "last_settlement_revision" field.
func LastSettlementRevisionEQ(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldLastSettlementRevision, v))
}

// LastSettlementRevisionNEQ applies the NEQ predicate on the "last_settlement_revision" field.
func LastSettlementRevisionNEQ(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNEQ(FieldLastSettlementRevision, v))
}

// LastSettlementRevisionIn applies the In predicate on the "last_settlement_revision" field.
func LastSettlementRevisionIn(vs ...int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIn(FieldLastSettlementRevision, vs...))
}

// LastSettlementRevisionNotIn applies the NotIn predicate on the "last_settlement_revision" field.
func LastSettlementRevisionNotIn(vs ...int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotIn(FieldLastSettlementRevision, vs...))
}

// LastSettlementRevisionGT applies the GT predicate on the "last_settlement_revision" field.
func LastSettlementRevisionGT(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGT(FieldLastSettlementRevision, v))
}

// LastSettlementRevisionGTE applies the GTE predicate on the "last_settlement_revision" field.
func LastSettlementRevisionGTE(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGTE(FieldLastSettlementRevision, v))
}

// LastSettlementRevisionLT applies the LT predicate on the "last_settlement_revision" field.
func LastSettlementRevisionLT(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLT(FieldLastSettlementRevision, v))
}

// LastSettlementRevisionLTE applies the LTE predicate on the "last_settlement_revision" field.
func LastSettlementRevisionLTE(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLTE(FieldLastSettlementRevision, v))
}

// LastLifecycleRevisionEQ applies the EQ predicate on the "last_lifecycle_revision" field.
func LastLifecycleRevisionEQ(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldLastLifecycleRevision, v))
}

// LastLifecycleRevisionNEQ applies the NEQ predicate on the "last_lifecycle_revision" field.
func LastLifecycleRevisionNEQ(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNEQ(FieldLastLifecycleRevision, v))
}

// LastLifecycleRevisionIn applies the In predicate on the "last_lifecycle_revision" field.
func LastLifecycleRevisionIn(vs ...int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIn(FieldLastLifecycleRevision, vs...))
}

// LastLifecycleRevisionNotIn applies the NotIn predicate on the "last_lifecycle_revision" field.
func LastLifecycleRevisionNotIn(vs ...int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotIn(FieldLastLifecycleRevision, vs...))
}

// LastLifecycleRevisionGT applies the GT predicate on the "last_lifecycle_revision" field.
func LastLifecycleRevisionGT(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGT(FieldLastLifecycleRevision, v))
}

// LastLifecycleRevisionGTE applies the GTE predicate on the "last_lifecycle_revision" field.
func LastLifecycleRevisionGTE(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGTE(FieldLastLifecycleRevision, v))
}

// LastLifecycleRevisionLT applies the LT predicate on the "last_lifecycle_revision" field.
func LastLifecycleRevisionLT(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLT(FieldLastLifecycleRevision, v))
}

// LastLifecycleRevisionLTE applies the LTE predicate on the "last_lifecycle_revision" field.
func LastLifecycleRevisionLTE(v int64) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLTE(FieldLastLifecycleRevision, v))
}

// LastLifecycleHashEQ applies the EQ predicate on the "last_lifecycle_hash" field.
func LastLifecycleHashEQ(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldLastLifecycleHash, v))
}

// LastLifecycleHashNEQ applies the NEQ predicate on the "last_lifecycle_hash" field.
func LastLifecycleHashNEQ(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNEQ(FieldLastLifecycleHash, v))
}

// LastLifecycleHashIn applies the In predicate on the "last_lifecycle_hash" field.
func LastLifecycleHashIn(vs ...string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIn(FieldLastLifecycleHash, vs...))
}

// LastLifecycleHashNotIn applies the NotIn predicate on the "last_lifecycle_hash" field.
func LastLifecycleHashNotIn(vs ...string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotIn(FieldLastLifecycleHash, vs...))
}

// LastLifecycleHashGT applies the GT predicate on the "last_lifecycle_hash" field.
func LastLifecycleHashGT(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGT(FieldLastLifecycleHash, v))
}

// LastLifecycleHashGTE applies the GTE predicate on the "last_lifecycle_hash" field.
func LastLifecycleHashGTE(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGTE(FieldLastLifecycleHash, v))
}

// LastLifecycleHashLT applies the LT predicate on the "last_lifecycle_hash" field.
func LastLifecycleHashLT(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLT(FieldLastLifecycleHash, v))
}

// LastLifecycleHashLTE applies the LTE predicate on the "last_lifecycle_hash" field.
func LastLifecycleHashLTE(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLTE(FieldLastLifecycleHash, v))
}

// LastLifecycleHashContains applies the Contains predicate on the "last_lifecycle_hash" field.
func LastLifecycleHashContains(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldContains(FieldLastLifecycleHash, v))
}

// LastLifecycleHashHasPrefix applies the HasPrefix predicate on the "last_lifecycle_hash" field.
func LastLifecycleHashHasPrefix(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldHasPrefix(FieldLastLifecycleHash, v))
}

// LastLifecycleHashHasSuffix applies the HasSuffix predicate on the "last_lifecycle_hash" field.
func LastLifecycleHashHasSuffix(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldHasSuffix(FieldLastLifecycleHash, v))
}

// LastLifecycleHashIsNil applies the IsNil predicate on the "last_lifecycle_hash" field.
func LastLifecycleHashIsNil() predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIsNull(FieldLastLifecycleHash))
}

// LastLifecycleHashNotNil applies the NotNil predicate on the "last_lifecycle_hash" field.
func LastLifecycleHashNotNil() predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotNull(FieldLastLifecycleHash))
}

// LastLifecycleHashEqualFold applies the EqualFold predicate on the "last_lifecycle_hash" field.
func LastLifecycleHashEqualFold(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEqualFold(FieldLastLifecycleHash, v))
}

// LastLifecycleHashContainsFold applies the ContainsFold predicate on the "last_lifecycle_hash" field.
func LastLifecycleHashContainsFold(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldContainsFold(FieldLastLifecycleHash, v))
}

// TerminalReasonEQ applies the EQ predicate on the "terminal_reason" field.
func TerminalReasonEQ(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldTerminalReason, v))
}

// TerminalReasonNEQ applies the NEQ predicate on the "terminal_reason" field.
func TerminalReasonNEQ(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNEQ(FieldTerminalReason, v))
}

// TerminalReasonIn applies the In predicate on the "terminal_reason" field.
func TerminalReasonIn(vs ...string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIn(FieldTerminalReason, vs...))
}

// TerminalReasonNotIn applies the NotIn predicate on the "terminal_reason" field.
func TerminalReasonNotIn(vs ...string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotIn(FieldTerminalReason, vs...))
}

// TerminalReasonGT applies the GT predicate on the "terminal_reason" field.
func TerminalReasonGT(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGT(FieldTerminalReason, v))
}

// TerminalReasonGTE applies the GTE predicate on the "terminal_reason" field.
func TerminalReasonGTE(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGTE(FieldTerminalReason, v))
}

// TerminalReasonLT applies the LT predicate on the "terminal_reason" field.
func TerminalReasonLT(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLT(FieldTerminalReason, v))
}

// TerminalReasonLTE applies the LTE predicate on the "terminal_reason" field.
func TerminalReasonLTE(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLTE(FieldTerminalReason, v))
}

// TerminalReasonContains applies the Contains predicate on the "terminal_reason" field.
func TerminalReasonContains(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldContains(FieldTerminalReason, v))
}

// TerminalReasonHasPrefix applies the HasPrefix predicate on the "terminal_reason" field.
func TerminalReasonHasPrefix(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldHasPrefix(FieldTerminalReason, v))
}

// TerminalReasonHasSuffix applies the HasSuffix predicate on the "terminal_reason" field.
func TerminalReasonHasSuffix(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldHasSuffix(FieldTerminalReason, v))
}

// TerminalReasonIsNil applies the IsNil predicate on the "terminal_reason" field.
func TerminalReasonIsNil() predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIsNull(FieldTerminalReason))
}

// TerminalReasonNotNil applies the NotNil predicate on the "terminal_reason" field.
func TerminalReasonNotNil() predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotNull(FieldTerminalReason))
}

// TerminalReasonEqualFold applies the EqualFold predicate on the "terminal_reason" field.
func TerminalReasonEqualFold(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEqualFold(FieldTerminalReason, v))
}

// TerminalReasonContainsFold applies the ContainsFold predicate on the "terminal_reason" field.
func TerminalReasonContainsFold(v string) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldContainsFold(FieldTerminalReason, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasReconciliation applies the HasEdge predicate on the "reconciliation" edge.
func HasReconciliation() predicate.BudgetRequest {
	return predicate.BudgetRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, ReconciliationTable, ReconciliationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReconciliationWith applies the HasEdge predicate on the "reconciliation" edge with a given conditions (other predicates).
func HasReconciliationWith(preds ...predicate.BudgetReconciliation) predicate.BudgetRequest {
	return predicate.BudgetRequest(func(s *sql.Selector) {
		step := newReconciliationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BudgetRequest) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BudgetRequest) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BudgetRequest) predicate.BudgetRequest {
	return predicate.BudgetRequest(sql.NotPredicates(p))
}
