// Code generated by ent, DO NOT EDIT.

package usagedetail

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the usagedetail type in the database.
	Label = "usage_detail"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldSettlementRevision holds the string denoting the settlement_revision field in the database.
	FieldSettlementRevision = "settlement_revision"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldQuantityUnits holds the string denoting the quantity_units field in the database.
	FieldQuantityUnits = "quantity_units"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldCompleteness holds the string denoting the completeness field in the database.
	FieldCompleteness = "completeness"
	// FieldOccurredAt holds the string denoting the occurred_at field in the database.
	FieldOccurredAt = "occurred_at"
	// Table holds the table name of the usagedetail in the database.
	Table = "usage_details"
)

// Columns holds all SQL columns for usagedetail fields.
var Columns = []string{
	FieldID,
	FieldRequestID,
	FieldSettlementRevision,
	FieldName,
	FieldQuantityUnits,
	FieldSource,
	FieldCompleteness,
	FieldOccurredAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the UsageDetail queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// BySettlementRevision orders the results by the settlement_revision field.
func BySettlementRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettlementRevision, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByQuantityUnits orders the results by the quantity_units field.
func ByQuantityUnits(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantityUnits, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByCompleteness orders the results by the completeness field.
func ByCompleteness(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompleteness, opts...).ToFunc()
}

// ByOccurredAt orders the results by the occurred_at field.
func ByOccurredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOccurredAt, opts...).ToFunc()
}
