// Package relaycontrolapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package relaycontrolapi

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
)

// Defines values for BudgetContextCapability.
const (
	BudgetContextCapabilityASR   BudgetContextCapability = "ASR"
	BudgetContextCapabilityMCP   BudgetContextCapability = "MCP"
	BudgetContextCapabilityMODEL BudgetContextCapability = "MODEL"
	BudgetContextCapabilityTTS   BudgetContextCapability = "TTS"
)

// Valid indicates whether the value is a known member of the BudgetContextCapability enum.
func (e BudgetContextCapability) Valid() bool {
	switch e {
	case BudgetContextCapabilityASR:
		return true
	case BudgetContextCapabilityMCP:
		return true
	case BudgetContextCapabilityMODEL:
		return true
	case BudgetContextCapabilityTTS:
		return true
	default:
		return false
	}
}

// Defines values for BudgetContextMode.
const (
	LIMITED   BudgetContextMode = "LIMITED"
	UNLIMITED BudgetContextMode = "UNLIMITED"
)

// Valid indicates whether the value is a known member of the BudgetContextMode enum.
func (e BudgetContextMode) Valid() bool {
	switch e {
	case LIMITED:
		return true
	case UNLIMITED:
		return true
	default:
		return false
	}
}

// Defines values for BudgetLimitStateMeter.
const (
	AUDIOSECONDS BudgetLimitStateMeter = "AUDIO_SECONDS"
	CACHEDTOKENS BudgetLimitStateMeter = "CACHED_TOKENS"
	CHARACTERS   BudgetLimitStateMeter = "CHARACTERS"
	INPUTTOKENS  BudgetLimitStateMeter = "INPUT_TOKENS"
	OUTPUTTOKENS BudgetLimitStateMeter = "OUTPUT_TOKENS"
	REQUESTS     BudgetLimitStateMeter = "REQUESTS"
	TOTALTOKENS  BudgetLimitStateMeter = "TOTAL_TOKENS"
)

// Valid indicates whether the value is a known member of the BudgetLimitStateMeter enum.
func (e BudgetLimitStateMeter) Valid() bool {
	switch e {
	case AUDIOSECONDS:
		return true
	case CACHEDTOKENS:
		return true
	case CHARACTERS:
		return true
	case INPUTTOKENS:
		return true
	case OUTPUTTOKENS:
		return true
	case REQUESTS:
		return true
	case TOTALTOKENS:
		return true
	default:
		return false
	}
}

// Defines values for BudgetLimitStatePeriod.
const (
	DAY      BudgetLimitStatePeriod = "DAY"
	LIFETIME BudgetLimitStatePeriod = "LIFETIME"
	MONTH    BudgetLimitStatePeriod = "MONTH"
	WEEK     BudgetLimitStatePeriod = "WEEK"
)

// Valid indicates whether the value is a known member of the BudgetLimitStatePeriod enum.
func (e BudgetLimitStatePeriod) Valid() bool {
	switch e {
	case DAY:
		return true
	case LIFETIME:
		return true
	case MONTH:
		return true
	case WEEK:
		return true
	default:
		return false
	}
}

// Defines values for ControlStatusSpoolState.
const (
	METERINGDEGRADED ControlStatusSpoolState = "METERING_DEGRADED"
	OK               ControlStatusSpoolState = "OK"
)

// Valid indicates whether the value is a known member of the ControlStatusSpoolState enum.
func (e ControlStatusSpoolState) Valid() bool {
	switch e {
	case METERINGDEGRADED:
		return true
	case OK:
		return true
	default:
		return false
	}
}

// Defines values for PublicJwkAlg.
const (
	EdDSA PublicJwkAlg = "EdDSA"
)

// Valid indicates whether the value is a known member of the PublicJwkAlg enum.
func (e PublicJwkAlg) Valid() bool {
	switch e {
	case EdDSA:
		return true
	default:
		return false
	}
}

// Defines values for PublicJwkCrv.
const (
	Ed25519 PublicJwkCrv = "Ed25519"
)

// Valid indicates whether the value is a known member of the PublicJwkCrv enum.
func (e PublicJwkCrv) Valid() bool {
	switch e {
	case Ed25519:
		return true
	default:
		return false
	}
}

// Defines values for PublicJwkKty.
const (
	OKP PublicJwkKty = "OKP"
)

// Valid indicates whether the value is a known member of the PublicJwkKty enum.
func (e PublicJwkKty) Valid() bool {
	switch e {
	case OKP:
		return true
	default:
		return false
	}
}

// Defines values for PublicJwkUse.
const (
	Sig PublicJwkUse = "sig"
)

// Valid indicates whether the value is a known member of the PublicJwkUse enum.
func (e PublicJwkUse) Valid() bool {
	switch e {
	case Sig:
		return true
	default:
		return false
	}
}

// Defines values for ResourceRouteClientProtocol.
const (
	ANTHROPICMESSAGES           ResourceRouteClientProtocol = "ANTHROPIC_MESSAGES"
	DASHSCOPEHTTPASR            ResourceRouteClientProtocol = "DASHSCOPE_HTTP_ASR"
	DASHSCOPEREALTIMEASR        ResourceRouteClientProtocol = "DASHSCOPE_REALTIME_ASR"
	GEMINIGENERATECONTENTTTS    ResourceRouteClientProtocol = "GEMINI_GENERATE_CONTENT_TTS"
	GOOGLEGENERATECONTENT       ResourceRouteClientProtocol = "GOOGLE_GENERATE_CONTENT"
	MCPSTREAMABLEHTTP           ResourceRouteClientProtocol = "MCP_STREAMABLE_HTTP"
	MIMOCHATCOMPLETIONSTTS      ResourceRouteClientProtocol = "MIMO_CHAT_COMPLETIONS_TTS"
	OPENAIAUDIOSPEECH           ResourceRouteClientProtocol = "OPENAI_AUDIO_SPEECH"
	OPENAIAUDIOTRANSCRIPTIONS   ResourceRouteClientProtocol = "OPENAI_AUDIO_TRANSCRIPTIONS"
	OPENAICHATCOMPLETIONS       ResourceRouteClientProtocol = "OPENAI_CHAT_COMPLETIONS"
	OPENAIREALTIMETRANSCRIPTION ResourceRouteClientProtocol = "OPENAI_REALTIME_TRANSCRIPTION"
	OPENAIRESPONSES             ResourceRouteClientProtocol = "OPENAI_RESPONSES"
)

// Valid indicates whether the value is a known member of the ResourceRouteClientProtocol enum.
func (e ResourceRouteClientProtocol) Valid() bool {
	switch e {
	case ANTHROPICMESSAGES:
		return true
	case DASHSCOPEHTTPASR:
		return true
	case DASHSCOPEREALTIMEASR:
		return true
	case GEMINIGENERATECONTENTTTS:
		return true
	case GOOGLEGENERATECONTENT:
		return true
	case MCPSTREAMABLEHTTP:
		return true
	case MIMOCHATCOMPLETIONSTTS:
		return true
	case OPENAIAUDIOSPEECH:
		return true
	case OPENAIAUDIOTRANSCRIPTIONS:
		return true
	case OPENAICHATCOMPLETIONS:
		return true
	case OPENAIREALTIMETRANSCRIPTION:
		return true
	case OPENAIRESPONSES:
		return true
	default:
		return false
	}
}

// Defines values for ResourceRouteResourceKind.
const (
	ResourceRouteResourceKindASR   ResourceRouteResourceKind = "ASR"
	ResourceRouteResourceKindMCP   ResourceRouteResourceKind = "MCP"
	ResourceRouteResourceKindMODEL ResourceRouteResourceKind = "MODEL"
	ResourceRouteResourceKindTTS   ResourceRouteResourceKind = "TTS"
)

// Valid indicates whether the value is a known member of the ResourceRouteResourceKind enum.
func (e ResourceRouteResourceKind) Valid() bool {
	switch e {
	case ResourceRouteResourceKindASR:
		return true
	case ResourceRouteResourceKindMCP:
		return true
	case ResourceRouteResourceKindMODEL:
		return true
	case ResourceRouteResourceKindTTS:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeAudioProfileChannels.
const (
	N1 RuntimeAudioProfileChannels = 1
)

// Valid indicates whether the value is a known member of the RuntimeAudioProfileChannels enum.
func (e RuntimeAudioProfileChannels) Valid() bool {
	switch e {
	case N1:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeAudioProfileEncoding.
const (
	PCM16LE    RuntimeAudioProfileEncoding = "PCM16_LE"
	WAVPCM16LE RuntimeAudioProfileEncoding = "WAV_PCM16_LE"
)

// Valid indicates whether the value is a known member of the RuntimeAudioProfileEncoding enum.
func (e RuntimeAudioProfileEncoding) Valid() bool {
	switch e {
	case PCM16LE:
		return true
	case WAVPCM16LE:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeAudioProfileSampleRates.
const (
	N16000 RuntimeAudioProfileSampleRates = 16000
	N24000 RuntimeAudioProfileSampleRates = 24000
	N8000  RuntimeAudioProfileSampleRates = 8000
)

// Valid indicates whether the value is a known member of the RuntimeAudioProfileSampleRates enum.
func (e RuntimeAudioProfileSampleRates) Valid() bool {
	switch e {
	case N16000:
		return true
	case N24000:
		return true
	case N8000:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeRouteSpecTransportPolicy.
const (
	HTTPBINARYSTREAM    RuntimeRouteSpecTransportPolicy = "HTTP_BINARY_STREAM"
	HTTPMULTIPART       RuntimeRouteSpecTransportPolicy = "HTTP_MULTIPART"
	HTTPREQUESTRESPONSE RuntimeRouteSpecTransportPolicy = "HTTP_REQUEST_RESPONSE"
	HTTPSTREAMINGSSE    RuntimeRouteSpecTransportPolicy = "HTTP_STREAMING_SSE"
	WEBSOCKET           RuntimeRouteSpecTransportPolicy = "WEBSOCKET"
)

// Valid indicates whether the value is a known member of the RuntimeRouteSpecTransportPolicy enum.
func (e RuntimeRouteSpecTransportPolicy) Valid() bool {
	switch e {
	case HTTPBINARYSTREAM:
		return true
	case HTTPMULTIPART:
		return true
	case HTTPREQUESTRESPONSE:
		return true
	case HTTPSTREAMINGSSE:
		return true
	case WEBSOCKET:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeUpstreamAuthType.
const (
	BASIC        RuntimeUpstreamAuthType = "BASIC"
	BEARER       RuntimeUpstreamAuthType = "BEARER"
	NONE         RuntimeUpstreamAuthType = "NONE"
	STATICHEADER RuntimeUpstreamAuthType = "STATIC_HEADER"
)

// Valid indicates whether the value is a known member of the RuntimeUpstreamAuthType enum.
func (e RuntimeUpstreamAuthType) Valid() bool {
	switch e {
	case BASIC:
		return true
	case BEARER:
		return true
	case NONE:
		return true
	case STATICHEADER:
		return true
	default:
		return false
	}
}

// Defines values for ValidationIssueSeverity.
const (
	ERROR   ValidationIssueSeverity = "ERROR"
	WARNING ValidationIssueSeverity = "WARNING"
)

// Valid indicates whether the value is a known member of the ValidationIssueSeverity enum.
func (e ValidationIssueSeverity) Valid() bool {
	switch e {
	case ERROR:
		return true
	case WARNING:
		return true
	default:
		return false
	}
}

// ActivationId defines model for ActivationId.
type ActivationId = string

// AsrId defines model for AsrId.
type AsrId = string

// BudgetContext defines model for BudgetContext.
type BudgetContext struct {
	AsOf           *time.Time               `json:"asOf,omitempty"`
	BlockingLimits *[]BudgetLimitState      `json:"blockingLimits,omitempty"`
	Capability     *BudgetContextCapability `json:"capability,omitempty"`
	Mode           *BudgetContextMode       `json:"mode,omitempty"`
	ResetAt        *time.Time               `json:"resetAt,omitempty"`
	ResourceId     *string                  `json:"resourceId,omitempty"`
}

// BudgetContextCapability defines model for BudgetContext.Capability.
type BudgetContextCapability string

// BudgetContextMode defines model for BudgetContext.Mode.
type BudgetContextMode string

// BudgetLimitState defines model for BudgetLimitState.
type BudgetLimitState struct {
	Limit    int64                  `json:"limit"`
	Meter    BudgetLimitStateMeter  `json:"meter"`
	Period   BudgetLimitStatePeriod `json:"period"`
	Reserved int64                  `json:"reserved"`
	ResetAt  *time.Time             `json:"resetAt,omitempty"`
	Used     int64                  `json:"used"`
}

// BudgetLimitStateMeter defines model for BudgetLimitState.Meter.
type BudgetLimitStateMeter string

// BudgetLimitStatePeriod defines model for BudgetLimitState.Period.
type BudgetLimitStatePeriod string

// ControlAck defines model for ControlAck.
type ControlAck struct {
	ActiveManagedGeneration int        `json:"activeManagedGeneration"`
	AppliedAt               time.Time  `json:"appliedAt"`
	AppliedControlRevision  int        `json:"appliedControlRevision"`
	BundleHash              Sha256Hash `json:"bundleHash"`
}

// ControlStatus defines model for ControlStatus.
type ControlStatus struct {
	ActiveManagedGeneration int `json:"activeManagedGeneration"`
	AppliedControlRevision  int `json:"appliedControlRevision"`

	// BuildVersion Build identity of the running Relay process; dev for a development build.
	BuildVersion            string                   `json:"buildVersion"`
	BundleHash              string                   `json:"bundleHash"`
	OldestPendingAgeSeconds *int                     `json:"oldestPendingAgeSeconds,omitempty"`
	Ready                   bool                     `json:"ready"`
	SpoolPendingCount       *int                     `json:"spoolPendingCount,omitempty"`
	SpoolState              *ControlStatusSpoolState `json:"spoolState,omitempty"`
	StartedAt               time.Time                `json:"startedAt"`
}

// ControlStatusSpoolState defines model for ControlStatus.SpoolState.
type ControlStatusSpoolState string

// DeploymentId defines model for DeploymentId.
type DeploymentId = string

// DeviceId defines model for DeviceId.
type DeviceId = string

// DraftId defines model for DraftId.
type DraftId = string

// EnrollmentId defines model for EnrollmentId.
type EnrollmentId = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// InstallationId defines model for InstallationId.
type InstallationId = string

// InteractionId defines model for InteractionId.
type InteractionId = string

// McpServerId defines model for McpServerId.
type McpServerId = string

// ModelId defines model for ModelId.
type ModelId = string

// OperationalLimits defines model for OperationalLimits.
type OperationalLimits struct {
	MaxRequestBytes int `json:"maxRequestBytes"`
}

// PolicyId defines model for PolicyId.
type PolicyId = string

// PricingRuleId defines model for PricingRuleId.
type PricingRuleId = string

// PrincipalState defines model for PrincipalState.
type PrincipalState struct {
	DeletedUserIds    []UserId    `json:"deletedUserIds"`
	DisabledUserIds   []UserId    `json:"disabledUserIds"`
	RevokedDeviceIds  []DeviceId  `json:"revokedDeviceIds"`
	RevokedSessionIds []SessionId `json:"revokedSessionIds"`
}

// Problem defines model for Problem.
type Problem struct {
	ActivationId            *ActivationId  `json:"activationId,omitempty"`
	Budget                  *BudgetContext `json:"budget,omitempty"`
	Code                    string         `json:"code"`
	CurrentDraftRevision    *int           `json:"currentDraftRevision,omitempty"`
	Detail                  *string        `json:"detail,omitempty"`
	Forwarded               *bool          `json:"forwarded,omitempty"`
	RequestId               *RequestId     `json:"requestId,omitempty"`
	Status                  int            `json:"status"`
	TargetManagedGeneration *int           `json:"targetManagedGeneration,omitempty"`
	Title                   string         `json:"title"`
	Type                    string         `json:"type"`
}

// ProviderId defines model for ProviderId.
type ProviderId = string

// PublicJwk defines model for PublicJwk.
type PublicJwk struct {
	Alg PublicJwkAlg `json:"alg"`
	Crv PublicJwkCrv `json:"crv"`
	Kid string       `json:"kid"`
	Kty PublicJwkKty `json:"kty"`
	Use PublicJwkUse `json:"use"`
	X   string       `json:"x"`
}

// PublicJwkAlg defines model for PublicJwk.Alg.
type PublicJwkAlg string

// PublicJwkCrv defines model for PublicJwk.Crv.
type PublicJwkCrv string

// PublicJwkKty defines model for PublicJwk.Kty.
type PublicJwkKty string

// PublicJwkUse defines model for PublicJwk.Use.
type PublicJwkUse string

// ReleaseId defines model for ReleaseId.
type ReleaseId = string

// RequestId defines model for RequestId.
type RequestId = string

// ResourceRoute defines model for ResourceRoute.
type ResourceRoute struct {
	AudioProfile   *RuntimeAudioProfile        `json:"audioProfile,omitempty"`
	ClientProtocol ResourceRouteClientProtocol `json:"clientProtocol"`
	LlmProfile     *RuntimeLlmProfile          `json:"llmProfile,omitempty"`
	ResourceId     string                      `json:"resourceId"`
	ResourceKind   ResourceRouteResourceKind   `json:"resourceKind"`
	RuntimeRouteId RuntimeRouteId              `json:"runtimeRouteId"`
}

// ResourceRouteClientProtocol defines model for ResourceRoute.ClientProtocol.
type ResourceRouteClientProtocol string

// ResourceRouteResourceKind defines model for ResourceRoute.ResourceKind.
type ResourceRouteResourceKind string

// RuntimeAudioProfile defines model for RuntimeAudioProfile.
type RuntimeAudioProfile struct {
	Channels    RuntimeAudioProfileChannels      `json:"channels"`
	Encoding    RuntimeAudioProfileEncoding      `json:"encoding"`
	SampleRates []RuntimeAudioProfileSampleRates `json:"sampleRates"`
}

// RuntimeAudioProfileChannels defines model for RuntimeAudioProfile.Channels.
type RuntimeAudioProfileChannels int

// RuntimeAudioProfileEncoding defines model for RuntimeAudioProfile.Encoding.
type RuntimeAudioProfileEncoding string

// RuntimeAudioProfileSampleRates defines model for RuntimeAudioProfile.SampleRates.
type RuntimeAudioProfileSampleRates int

// RuntimeControlState defines model for RuntimeControlState.
type RuntimeControlState struct {
	ActiveManagedGeneration int                   `json:"activeManagedGeneration"`
	AuthKeys                []PublicJwk           `json:"authKeys"`
	BundleHash              Sha256Hash            `json:"bundleHash"`
	ControlRevision         int                   `json:"controlRevision"`
	DeploymentId            DeploymentId          `json:"deploymentId"`
	OperationalLimits       OperationalLimits     `json:"operationalLimits"`
	PrincipalState          PrincipalState        `json:"principalState"`
	ResourceRoutes          []ResourceRoute       `json:"resourceRoutes"`
	Routes                  []RuntimeRouteSpec    `json:"routes"`
	Upstreams               []RuntimeUpstreamSpec `json:"upstreams"`
}

// RuntimeLlmProfile defines model for RuntimeLlmProfile.
type RuntimeLlmProfile struct {
	AnthropicCacheFieldsMayBeAbsent bool `json:"anthropicCacheFieldsMayBeAbsent"`
	GeminiThoughtsMayBeAbsent       bool `json:"geminiThoughtsMayBeAbsent"`
}

// RuntimeRouteId defines model for RuntimeRouteId.
type RuntimeRouteId = string

// RuntimeRouteSpec defines model for RuntimeRouteSpec.
type RuntimeRouteSpec struct {
	AllowedMethods      []string                        `json:"allowedMethods"`
	AllowedPathPrefixes []string                        `json:"allowedPathPrefixes"`
	RuntimeRouteId      RuntimeRouteId                  `json:"runtimeRouteId"`
	TimeoutPolicy       TimeoutPolicy                   `json:"timeoutPolicy"`
	TransportPolicy     RuntimeRouteSpecTransportPolicy `json:"transportPolicy"`
	UpstreamId          UpstreamId                      `json:"upstreamId"`
}

// RuntimeRouteSpecTransportPolicy defines model for RuntimeRouteSpec.TransportPolicy.
type RuntimeRouteSpecTransportPolicy string

// RuntimeUpstreamAuth defines model for RuntimeUpstreamAuth.
type RuntimeUpstreamAuth struct {
	Type                 RuntimeUpstreamAuthType `json:"type"`
	AdditionalProperties map[string]interface{}  `json:"-"`
}

// RuntimeUpstreamAuthType defines model for RuntimeUpstreamAuth.Type.
type RuntimeUpstreamAuthType string

// RuntimeUpstreamSpec defines model for RuntimeUpstreamSpec.
type RuntimeUpstreamSpec struct {
	Auth                  RuntimeUpstreamAuth `json:"auth"`
	BaseUrl               string              `json:"baseUrl"`
	Enabled               bool                `json:"enabled"`
	SecretRef             *SecretRef          `json:"secretRef,omitempty"`
	TransportCapabilities []string            `json:"transportCapabilities"`
	UpstreamId            UpstreamId          `json:"upstreamId"`
}

// SecretId defines model for SecretId.
type SecretId = string

// SecretRef defines model for SecretRef.
type SecretRef struct {
	SecretId      SecretId `json:"secretId"`
	SecretVersion int      `json:"secretVersion"`
}

// SessionId defines model for SessionId.
type SessionId = string

// Sha256Hash defines model for Sha256Hash.
type Sha256Hash = string

// TimeoutPolicy defines model for TimeoutPolicy.
type TimeoutPolicy struct {
	ConnectMs        int  `json:"connectMs"`
	IdleMs           int  `json:"idleMs"`
	OverallMs        *int `json:"overallMs,omitempty"`
	ResponseHeaderMs int  `json:"responseHeaderMs"`
}

// TtsId defines model for TtsId.
type TtsId = string

// UpstreamId defines model for UpstreamId.
type UpstreamId = string

// UserId defines model for UserId.
type UserId = string

// ValidationIssue defines model for ValidationIssue.
type ValidationIssue struct {
	Code     string                  `json:"code"`
	Message  string                  `json:"message"`
	Path     string                  `json:"path"`
	Severity ValidationIssueSeverity `json:"severity"`
}

// ValidationIssueSeverity defines model for ValidationIssue.Severity.
type ValidationIssueSeverity string

// ApplyControlStateJSONRequestBody defines body for ApplyControlState for application/json ContentType.
type ApplyControlStateJSONRequestBody = RuntimeControlState

// Getter for additional properties for RuntimeUpstreamAuth. Returns the specified
// element and whether it was found
func (a RuntimeUpstreamAuth) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for RuntimeUpstreamAuth
func (a *RuntimeUpstreamAuth) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for RuntimeUpstreamAuth to handle AdditionalProperties
func (a *RuntimeUpstreamAuth) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for RuntimeUpstreamAuth to handle AdditionalProperties
func (a RuntimeUpstreamAuth) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (PUT /internal/v1/control/state)
	ApplyControlState(w http.ResponseWriter, r *http.Request)

	// (GET /internal/v1/control/status)
	GetControlStatus(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (PUT /internal/v1/control/state)
func (_ Unimplemented) ApplyControlState(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /internal/v1/control/status)
func (_ Unimplemented) GetControlStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ApplyControlState operation middleware
func (siw *ServerInterfaceWrapper) ApplyControlState(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApplyControlState(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetControlStatus operation middleware
func (siw *ServerInterfaceWrapper) GetControlStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetControlStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/internal/v1/control/state", wrapper.ApplyControlState)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/internal/v1/control/status", wrapper.GetControlStatus)
	})

	return r
}
