// Code generated by ent, DO NOT EDIT.

package requestusage

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the requestusage type in the database.
	Label = "request_usage"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldInteractionID holds the string denoting the interaction_id field in the database.
	FieldInteractionID = "interaction_id"
	// FieldDeploymentID holds the string denoting the deployment_id field in the database.
	FieldDeploymentID = "deployment_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldDeviceID holds the string denoting the device_id field in the database.
	FieldDeviceID = "device_id"
	// FieldResourceID holds the string denoting the resource_id field in the database.
	FieldResourceID = "resource_id"
	// FieldRuntimeRouteID holds the string denoting the runtime_route_id field in the database.
	FieldRuntimeRouteID = "runtime_route_id"
	// FieldUpstreamID holds the string denoting the upstream_id field in the database.
	FieldUpstreamID = "upstream_id"
	// FieldManagedGeneration holds the string denoting the managed_generation field in the database.
	FieldManagedGeneration = "managed_generation"
	// FieldControlRevision holds the string denoting the control_revision field in the database.
	FieldControlRevision = "control_revision"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldForwarded holds the string denoting the forwarded field in the database.
	FieldForwarded = "forwarded"
	// FieldHTTPStatus holds the string denoting the http_status field in the database.
	FieldHTTPStatus = "http_status"
	// FieldUpstreamHTTPStatus holds the string denoting the upstream_http_status field in the database.
	FieldUpstreamHTTPStatus = "upstream_http_status"
	// FieldRequestBytes holds the string denoting the request_bytes field in the database.
	FieldRequestBytes = "request_bytes"
	// FieldResponseBytes holds the string denoting the response_bytes field in the database.
	FieldResponseBytes = "response_bytes"
	// FieldDurationMs holds the string denoting the duration_ms field in the database.
	FieldDurationMs = "duration_ms"
	// FieldErrorClass holds the string denoting the error_class field in the database.
	FieldErrorClass = "error_class"
	// FieldIngestedAt holds the string denoting the ingested_at field in the database.
	FieldIngestedAt = "ingested_at"
	// Table holds the table name of the requestusage in the database.
	Table = "request_usages"
)

// Columns holds all SQL columns for requestusage fields.
var Columns = []string{
	FieldID,
	FieldRequestID,
	FieldInteractionID,
	FieldDeploymentID,
	FieldUserID,
	FieldDeviceID,
	FieldResourceID,
	FieldRuntimeRouteID,
	FieldUpstreamID,
	FieldManagedGeneration,
	FieldControlRevision,
	FieldStartedAt,
	FieldCompletedAt,
	FieldForwarded,
	FieldHTTPStatus,
	FieldUpstreamHTTPStatus,
	FieldRequestBytes,
	FieldResponseBytes,
	FieldDurationMs,
	FieldErrorClass,
	FieldIngestedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the RequestUsage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByInteractionID orders the results by the interaction_id field.
func ByInteractionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInteractionID, opts...).ToFunc()
}

// ByDeploymentID orders the results by the deployment_id field.
func ByDeploymentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeploymentID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByDeviceID orders the results by the device_id field.
func ByDeviceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceID, opts...).ToFunc()
}

// ByResourceID orders the results by the resource_id field.
func ByResourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceID, opts...).ToFunc()
}

// ByRuntimeRouteID orders the results by the runtime_route_id field.
func ByRuntimeRouteID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuntimeRouteID, opts...).ToFunc()
}

// ByUpstreamID orders the results by the upstream_id field.
func ByUpstreamID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamID, opts...).ToFunc()
}

// ByManagedGeneration orders the results by the managed_generation field.
func ByManagedGeneration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManagedGeneration, opts...).ToFunc()
}

// ByControlRevision orders the results by the control_revision field.
func ByControlRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldControlRevision, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByForwarded orders the results by the forwarded field.
func ByForwarded(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldForwarded, opts...).ToFunc()
}

// ByHTTPStatus orders the results by the http_status field.
func ByHTTPStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHTTPStatus, opts...).ToFunc()
}

// ByUpstreamHTTPStatus orders the results by the upstream_http_status field.
func ByUpstreamHTTPStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamHTTPStatus, opts...).ToFunc()
}

// ByRequestBytes orders the results by the request_bytes field.
func ByRequestBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestBytes, opts...).ToFunc()
}

// ByResponseBytes orders the results by the response_bytes field.
func ByResponseBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseBytes, opts...).ToFunc()
}

// ByDurationMs orders the results by the duration_ms field.
func ByDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMs, opts...).ToFunc()
}

// ByErrorClass orders the results by the error_class field.
func ByErrorClass(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorClass, opts...).ToFunc()
}

// ByIngestedAt orders the results by the ingested_at field.
func ByIngestedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIngestedAt, opts...).ToFunc()
}
